/* en — traduit du français. Toute clé du français doit exister ici :
   le build refuse de construire une langue incomplète. */
module.exports = {
  'locale.name': 'English',
  'site.name': 'Toutadmin',
  'site.tagline': 'The CMS that runs the whole company',
  'nav.product': 'Product',
  'nav.features': 'Features',
  'nav.screens': 'Screens',
  'nav.security': 'Security',
  'nav.pricing': 'Pricing',
  'nav.contact': 'Contact',
  'nav.demo': 'Demo',
  'nav.menu': 'Menu',
  'nav.language': 'Language',
  'nav.theme': 'Theme',
  'nav.themeLight': 'Light',
  'nav.themeDark': 'Dark',
  'nav.themeSystem': 'System',
  'hero.eyebrow': 'Business management software',
  'hero.title': 'Your whole company,\nin a single piece of software.',
  'hero.lede': 'People, HR, finance, operations, governance, compliance, facilities. Thirty-five workspaces that talk to each other, one database, no apps to glue together. In sixteen languages, and €5 per employee per month to run all of it.',
  'hero.ctaPrimary': 'Start free',
  'hero.ctaSecondary': 'See the features',
  'hero.note': 'No credit card. Your data stays yours — and can stay on your own servers.',
  'hero.badge1': 'SaaS, ready in five minutes',
  'hero.badge2': 'or hosted by you',
  'hero.badge3': 'GDPR by design',
  'stats.title': 'What the product covers, in numbers',
  'stats.spaces': 'workspaces',
  'stats.spacesNote': 'from the employee\'s own page to corporate records',
  'stats.languages': 'interface languages',
  'stats.languagesNote': 'Arabic included, page fully mirrored',
  'stats.tests': 'integration tests',
  'stats.testsNote': 'run on every release',
  'stats.modules': 'optional modules',
  'stats.modulesNote': 'accounting, payroll, treasury, CRM…',
  'stats.deps': 'external services required',
  'stats.depsNote': 'one machine, one database, nothing else',
  'stats.keys': 'translated labels',
  'stats.keysNote': 'down to the confirmation dialogs',
  'pillars.title': 'Why Toutadmin rather than five tools bolted together',
  'pillars.lede': 'Five pieces of software that don\'t talk to each other cost more than one, and lose the thing that matters: the overall picture. Toutadmin starts from the opposite idea — one database, workspaces, and rights.',
  'pillars.1.title': 'One place, one truth',
  'pillars.1.body': 'A department\'s budget adds up its own invoices and its members\' approved expenses. A goods receipt enters stock in the same gesture. Nobody re-keys anything, so nobody contradicts anybody.',
  'pillars.2.title': 'Rights are not decoration',
  'pillars.2.body': 'Every route carries its own server-side guard, and reporting lines are re-read on every request. A departure cuts access immediately — not when the cookie expires. What you may not see is not searched at all.',
  'pillars.3.title': 'Deadlines come to you',
  'pillars.3.body': 'Contract notice periods, certifications to renew, medical check-ups, vehicle inspections, corporate mandates, supplier certificates: one engine gathers them all and warns the right person, once, without duplicates.',
  'pillars.4.title': 'Every screen says what it does not do',
  'pillars.4.body': 'A module shows its limits when you switch it on, not buried in a manual. We prefer an honest sentence to a ticked box: that is what saves you from nasty surprises in month three.',
  'pillars.5.title': 'Sixteen languages, properly',
  'pillars.5.body': 'Not just the landing screen: statuses, error messages, confirmation dialogs. Arabic mirrors the entire page, because the stylesheet only uses logical properties.',
  'pillars.6.title': 'Your data, on your own servers if you want',
  'pillars.6.body': 'As SaaS, everything is ready in five minutes. On paid plans you can also host the database on your own server: same software, same updates, data inside your walls.',
  'tour.title': 'Dense software, not a toy',
  'tour.lede': 'Screens built for people who keep them open eight hours a day: information at a glance, no pointless modal windows, and the same vocabulary everywhere.',
  'tour.hint': 'Pick a tab to change screen.',
  'tour.all': 'See all 40 screens',
  'features.title': 'Everything Toutadmin does',
  'features.lede': 'The complete list, domain by domain. Every line is code that shipped and is tested, not an intention.',
  'features.legend': 'Items marked “module” are switched on from the console when you need them.',
  'features.module': 'module',
  'features.seeAll': 'See the full list',
  'features.intro': 'Fourteen domains, more than a hundred and thirty functions.',
  'features.ctaTitle': 'Something missing?',
  'features.ctaBody': 'Tell us. The product moves in batches, and requests from the companies using it come first.',
  'screens.title': 'The screens, untouched',
  'screens.lede': 'Every screenshot on this site comes from a real instance filled with demo data. No mock-ups, no retouching.',
  'screens.light': 'Light theme',
  'screens.dark': 'Dark theme',
  'screens.member': 'The employee\'s workspace',
  'screens.admin': 'Administration and steering',
  'screens.modules': 'Optional modules',
  'screens.open': 'Enlarge',
  'screens.close': 'Close',
  'screens.prev': 'Previous',
  'screens.next': 'Next',
  'security.title': 'Security is not a paid extra',
  'security.lede': 'Everything below is in the product, whatever the plan — including the free one.',
  'security.1.title': 'Hardened authentication',
  'security.1.body': 'Hashed passwords (bcrypt), complexity policy, lockout after repeated failures, TOTP two-factor with recovery codes, sessions revocable one by one or all at once.',
  'security.2.title': 'Sealed audit log',
  'security.2.body': 'Every entry carries the fingerprint of the previous one. Changing a line, or removing one from the middle, breaks the chain at that exact point, and the check says which. What it does not do: stop whoever holds the server from rewriting — it makes the rewrite visible.',
  'security.3.title': 'Personal data',
  'security.3.body': 'Register of processing activities, right of access exported source by source, erasure that keeps what the law requires kept and says so. The account is anonymised rather than deleted, so the records that reference it stay consistent.',
  'security.4.title': 'Internal whistleblowing channel',
  'security.4.body': 'Mandatory in France from fifty employees. Content encrypted in the database, readable only by the appointed officers — not by administrators, since a report may be about one of them. Anonymous follow-up by code, without an account and without logging.',
  'security.5.title': 'Verified backups',
  'security.5.body': 'Hourly archive, integrity checked against a manifest, restore that puts back both database and files, off-site copy over FTPS or Google Drive, and administrators alerted on failure.',
  'security.6.title': 'Encrypted secrets',
  'security.6.body': 'Third-party service passwords, API tokens, webhook secrets: encrypted with AES-256-GCM, never shown again in the clear, unreadable once tampered with.',
  'security.hostTitle': 'SaaS, or on your own servers',
  'security.hostBody': 'On SaaS we host in Europe, backups included. On paid plans, local hosting is available: you install on your server, the database never leaves your walls, and you get the same updates. One machine is enough — Node 22 and SQLite, no external database to administer.',
  'security.limitsTitle': 'What we do not claim to do',
  'security.limitsBody': 'Electronic signature is simple, not qualified in the eIDAS sense. The vault seals and dates documents, but timestamping enforceable against a third party requires a certification authority. No tax or social filing: the software produces the data, submitting it stays with your accountant. That is written here rather than after you sign.',
  'pricing.title': 'Clear pricing, no surprises',
  'pricing.lede': 'One price, per employee per month, to run the whole company. No à la carte modules, no per-feature surcharge: the entire product is in every plan.',
  'pricing.perMonth': '/ month',
  'pricing.free': 'Free',
  'pricing.vat': 'Prices excluding tax. No minimum term on the monthly plans.',
  'pricing.cta': 'Get started',
  'pricing.ctaCustom': 'Talk to us',
  'pricing.popular': 'Most chosen',
  'pricing.p1.name': 'Free',
  'pricing.p1.for': 'Under 5 employees',
  'pricing.p1.body': 'The whole product, free, with no time limit and nothing crippled. The plan for a young company, an association or a practice getting started.',
  'pricing.p2.name': 'Subscription',
  'pricing.p2.for': 'From 5 employees',
  'pricing.p2.body': '€5 per employee per month, then €4 from two hundred and fifty to five hundred, and €3 beyond. You pay for the headcount you have, not for the one you might have one day.',
  'pricing.p4.name': 'Lifetime licence',
  'pricing.p4.for': 'One-off payment',
  'pricing.p4.body': '€10,000 once. No subscription, no time limit, no headcount ceiling. The software is yours for as long as you want to use it.',
  'pricing.tableTitle': 'What each plan includes',
  'pricing.col.feature': '',
  'pricing.yes': 'Included',
  'pricing.no': 'No',
  'pricing.option': 'Optional',
  'pricing.f.allSpaces': 'All 35 workspaces and 7 modules',
  'pricing.f.languages': 'All 16 languages and 3 palettes',
  'pricing.f.security': 'Full security, sealed log, GDPR',
  'pricing.f.updates': 'Updates included',
  'pricing.f.saas': 'SaaS hosting in Europe',
  'pricing.f.local': 'Local hosting of your data',
  'pricing.f.backupOff': 'Off-site backups',
  'pricing.f.support': 'Support',
  'pricing.f.supportMail': 'By email',
  'pricing.f.supportPrio': 'Priority',
  'pricing.f.supportDedicated': 'Dedicated contact',
  'pricing.f.supportCommunity': 'Documentation',
  'pricing.f.migration': 'Migration of your data',
  'pricing.f.sla': 'Service level agreement',
  'pricing.f.api': 'Read API and webhooks',
  'pricing.f.multisite': 'Several sites, several entities',
  'pricing.countTitle': 'How we count employees',
  'pricing.countBody': 'Active accounts, including freelancers and interns, administrators excluded. A closed account no longer counts, even though it keeps access to its vault. Crossing a threshold? The change applies the following month, never retroactively — and you come back down the same way.',
  'faq.title': 'Frequently asked questions',
  'faq.q1': 'Is the free plan time-limited?',
  'faq.a1': 'No. Under five employees the product is free with no time limit and nothing crippled. We would rather see a small outfit grow with the software than a trial that dies after thirty days.',
  'faq.q2': 'Can I host my data on my own server?',
  'faq.a2': 'Yes, on paid plans. The software runs on a single machine with Node 22 and SQLite: no database server, no external service. You keep the database, the documents and the backups.',
  'faq.q3': 'What happens if I leave?',
  'faq.a3': 'You export the entire instance as JSON, documents included, from the admin console. Nothing is held hostage: it is your database, and it leaves with you in a readable format.',
  'faq.q4': 'Does it replace my accountant?',
  'faq.a4': 'No. Double-entry accounting, payroll and VAT are there to keep your records and prepare the documents. There is no statutory filing and no electronic submission: the export feeds your accountant.',
  'faq.q5': 'Do teams need training?',
  'faq.a5': 'The employee workspace explains itself: leave requests, documents, schedule, directory. The administration workspaces take about half a day to learn, which we cover on the paid plans.',
  'faq.q6': 'Can I switch on only part of the product?',
  'faq.a6': 'Yes. Seven modules — accounting, payroll, e-invoicing, stock and purchasing, treasury, fixed assets, CRM — are off by default and switch on one at a time. While a module is off, its URLs answer 404.',
  'faq.q7': 'How does migrating my current data work?',
  'faq.a7': 'A bulk CSV import checks every row before writing, and writes nothing if a single row is invalid. On the paid plans we prepare the files with you.',
  'faq.q8': 'What about integrations with our tools?',
  'faq.a8': 'A scoped read-only REST API and signed outgoing webhooks are included in every plan. For specific exchanges — HR systems, ERP, invoicing — write to us: that work is quoted case by case.',
  'contact.title': 'Let\'s talk about your company',
  'contact.lede': 'A demo takes thirty minutes, on your own cases rather than on invented data. Tell us what you are trying to fix.',
  'contact.emailLabel': 'By email',
  'contact.demoTitle': 'Book a demonstration',
  'contact.demoBody': 'Give us your name, your company, your headcount and what is causing you trouble today. We answer within one working day.',
  'contact.write': 'Write to the team',
  'contact.docTitle': 'Read the documentation',
  'contact.docBody': 'The documentation site covers installation, configuration, security, the API and the full glossary in sixteen languages.',
  'contact.docCta': 'Open the documentation',
  'contact.selfTitle': 'Install it yourself',
  'contact.selfBody': 'Node 22, one machine, five minutes: the installer creates the database and the admin account, and checks the environment.',
  'contact.selfCta': 'See the requirements',
  'cta.title': 'Start free, change plan when you grow',
  'cta.body': 'Under five employees everything is free. Above that, €5 per employee per month — tapering from two hundred and fifty — or €10,000 once for the lifetime licence. No credit card to try.',
  'cta.primary': 'Create my instance',
  'cta.secondary': 'Talk to someone',
  'foot.product': 'Product',
  'foot.company': 'About',
  'foot.resources': 'Resources',
  'foot.legal': 'Legal',
  'foot.docs': 'Documentation',
  'foot.status': 'What is covered',
  'foot.rights': 'All rights reserved.',
  'foot.madeWith': 'Node 22 · Express · SQLite. No needless dependency.',
  'foot.langTitle': 'This site exists in sixteen languages',
  'dom.socle.title': 'Foundation and organisation',
  'dom.socle.lede': 'What holds the rest together: accounts, reporting lines, and the vocabulary shared by every workspace.',
  'dom.socle.items': [
    'Accounts and stackable roles: admin, HR, finance, IT, whistleblowing officer',
    'Manager status derived from actual reporting lines, never granted by hand',
    'Departments and teams, several managers per scope, links re-read on every request',
    'Visual org chart, management included, and the people attached to nothing',
    'Directory with search and filters, visibility controlled by administrators alone',
    'Internal messaging, and work email address configured by the administration',
    'Global search partitioned at the source: what you cannot see is not searched',
    'Per-person notification centre, with read receipts',
    'Bulk CSV import: checked preview, all-or-nothing write',
    'Installation wizard, instance settings, seven unlockable modules',
    '16 languages, 3 palettes, light/dark/system theme, responsive interface',
  ],
  'dom.espace.title': 'The employee\'s workspace',
  'dom.espace.lede': 'The page everyone opens in the morning: what concerns them, and nothing else.',
  'dom.espace.items': [
    'Personal dashboard: manager, news, requests, documents awaiting acknowledgement',
    'Leave, time-off, absence and remote-work requests: working days computed, weekends excluded',
    'Up-to-date leave balance, history of adjustments with their reason',
    'Payslips available, and kept fifty years in the digital vault',
    'Personal calendar and shared team calendar',
    'Weekly schedule, on-call duty, standby shifts',
    'Assigned tools with their own login — no third-party password stored',
    'Profile: photo, bio, phone, language, password, closing all sessions',
    'Stopwatch time tracking for freelancers, one running entry at a time',
    'Declaration of interests and gifts, visible to oneself only',
  ],
  'dom.rh.title': 'Human resources',
  'dom.rh.lede': 'The employee file, from arrival to departure, with the deadlines that go with it.',
  'dom.rh.items': [
    'Request approval with balance deduction, reasoned refusal, cancellation that credits back',
    'Payslips: creation, payment tracking, batch generation',
    'Company documents with named acknowledgement of receipt',
    'Training: catalogue, sessions, enrolment, cost and duration',
    'Annual reviews: campaign, template, written record',
    'Onboarding and offboarding: tracked checklists, owner and due date per task',
    'Skills and certifications, with renewal dates and early warning',
    'One-to-ones: shared summary, manager\'s private notes kept apart',
    'Digital vault still reachable after departure, documents sealed by their fingerprint',
    'Simple electronic signature: ordered circuit, fingerprint, seal, certificate',
    'Fixed-term contracts: the account closes itself on the day',
  ],
  'dom.talent.title': 'Recruitment and talent',
  'dom.talent.lede': 'From applications to day one, with no spreadsheet in between.',
  'dom.talent.items': [
    'Job openings and applications tracked stage by stage',
    'CV intake: PDF, DOCX or text, written outside the repository',
    'Content extraction and a searchable CV library',
    'Weighted criteria, score, threshold, ranked applications',
    'A hired candidate flows straight into the onboarding checklist',
    'Internal surveys and workplace barometer, anonymous by construction',
    'Under five answers, no result is shown',
  ],
  'dom.sst.title': 'Health, safety and works council',
  'dom.sst.lede': 'Obligations that must be written down, and that remind you of themselves.',
  'dom.sst.items': [
    'Risk assessment register: work units, hazards, rating, measures, dated review',
    'Register of accidents at work and near misses, days lost',
    'Protective equipment: named issue, validity period, replacement',
    'Medical check-ups: hiring, periodic, return to work, on request',
    'Works council: elections, electorate, anonymous ballot, mandates and their expiry',
    'Council meetings, benefits and services for employees',
    'The management workspace closes itself when the mandate ends',
  ],
  'dom.finance.title': 'Finance and administration',
  'dom.finance.lede': 'Third parties, contracts, the money coming in and the money going out.',
  'dom.finance.items': [
    'Customers and suppliers, full record: contacts, contracts, invoices',
    'Contracts and above all notice periods: the deadline to terminate is computed and flagged',
    'Invoices both ways, gross computed, lateness derived from the due date',
    'Budgets by department and financial year, consumption aggregated automatically',
    'Expense claims: submission, approval, reimbursement — never one without the other',
    'Supplier compliance documents, dated and flagged forty-five days before expiry',
    'Scored supplier reviews, the latest one standing rather than the average',
    'Multi-currency with the rate frozen when each document is issued',
    'Recurring billing: the subscription is the mould, the invoice is the document',
    'Automatic reading of incoming invoices and IMAP capture of an accounting mailbox',
  ],
  'dom.compta.title': 'Accounting, payroll and VAT',
  'dom.compta.lede': 'Modules, off by default, that switch on when you need them.',
  'dom.compta.items': [
    'Double-entry accounting: chart of accounts, journals, trial balance, general ledger',
    'An unbalanced entry is refused, and the message says by how much',
    'An invoice becomes a journal entry in one click; CSV export for your accountant',
    'Payroll engine: configurable rates, gross to net, employer contributions, total cost',
    'Detailed payslip line by line, batch generation, simulator',
    'VAT returns: output, input, split by rate, credit carried forward',
    'A filed return is never recomputed: it is a record, not a dashboard',
    'E-invoicing: EN 16931 checks and CII XML export',
    'Treasury: accounts, movements, reconciliation, twelve-week forecast',
    'Fixed assets: straight-line and declining depreciation, net book value',
  ],
  'dom.achats.title': 'Purchasing, stock and collections',
  'dom.achats.lede': 'What you order, what you receive, what you are invoiced — and what you are owed.',
  'dom.achats.items': [
    'Purchase requests approved by the manager, then by finance above the threshold',
    'Purchase orders, goods receipts, and three-way match: ordered, received, invoiced',
    'Receiving more than ordered is refused; an invoicing gap is named, not blocked',
    'Items, movements, reorder level: stock is the sum of its movements',
    'A line linked to an item enters stock the moment it is received',
    'Aged customer balance by lateness bracket',
    'Staged reminders: first notice, chaser, formal notice, based on what was already sent',
    'Every reminder recorded with its level and date',
  ],
  'dom.projets.title': 'Projects, time and profitability',
  'dom.projets.lede': 'Knowing where a project stands, and what it actually cost.',
  'dom.projets.items': [
    'Projects attached to a client, a department, a team and a lead',
    'Dated milestones and tasks in columns by status, with priority and estimate',
    'Time logged against project and task, at most 24 h per entry',
    'Profitability: hours, cost at the hourly rate, remaining margin, share of budget used',
    'Three circles of rights: finance, the lead, the members',
    'Time per person, and project health on the management dashboard',
  ],
  'dom.support.title': 'Support and knowledge',
  'dom.support.lede': 'Internal and customer requests in one flow, and answers that stay.',
  'dom.support.items': [
    'Internal and customer tickets, priority, origin, assignment',
    'First-response target derived from priority, recomputed from the opening time',
    'Internal notes invisible to the requester, and not counted as a reply',
    'Partitioned by category: an HR request does not leave HR',
    'Knowledge base by category, full-text search, adjustable scope',
    'Indicators: open tickets, overdue, average delay',
  ],
  'dom.ops.title': 'Operations and facilities',
  'dom.ops.lede': 'Scheduling, quality, rooms, vehicles, the front desk.',
  'dom.ops.items': [
    'Schedule per person and per day: shifts, on-call, standby, remote work',
    'Overlap or approved absence: the slot is refused as it is created',
    'Reusable rotations, night shifts, weekly publication',
    'Who is on call right now, with their number',
    'Quality: non-conformities, root causes, corrective actions and effectiveness checks',
    'Internal audits: findings, summary, a finding promoted into a non-conformity',
    'Equipment assigned and returned, with the history of holders',
    'Rooms and bookings, an overlap refused while naming who holds the slot',
    'Fleet: servicing, roadworthiness, insurance, claims, mileage',
    'Front desk: visitor register, an on-site list, incoming and outgoing mail',
  ],
  'dom.direction.title': 'Management and governance',
  'dom.direction.lede': 'What management looks at, and what it decides.',
  'dom.direction.items': [
    'Dashboard: headcount, absences, invoiced, margin, payroll cost, cash, support load',
    'Objectives and key results, each on its own scale, decreasing ones included',
    'Meetings: convening, agenda, attendance ticked, minutes',
    'Register of decisions with their rationale — what you look for two years later',
    'Assigned actions with owner and due date, attached to their decision',
    'Risk register: gross and residual rating, 5 × 5 matrix, treatment, review',
    'Company events: capacity, automatic waiting list, attendance, budget',
    'Deadlines from every workspace consolidated into one sorted list',
  ],
  'dom.it.title': 'IT and development',
  'dom.it.lede': 'The software estate, the accounts, the incidents, and what the team ships.',
  'dom.it.items': [
    'Software estate: seats treated as a constraint, annualised cost, renewals',
    'Application access review: closed accounts first, then admin rights',
    'IT incidents, timestamped, with mean time to restore actually measured',
    'Service catalogue: criticality, owner, repository, documentation',
    'Release register per environment and delivery indicators',
    'Backups: hourly archive, integrity verified, restore, off-site copy',
    'Scoped read-only REST API, signed outgoing webhooks',
    'Full instance export as JSON, documents included, secrets excluded',
  ],
  'dom.conformite.title': 'Compliance, corporate and personal data',
  'dom.conformite.lede': 'What a company must be able to prove, kept up as you go.',
  'dom.conformite.items': [
    'Share register: holdings derived from movements, a transfer written in both legs',
    'Corporate mandates with duration, revocation, and expiry flagged in advance',
    'General meetings: quorum in shares, resolutions, votes, minutes',
    'Delegations of authority: scope, ceiling, duration, expiry flagged',
    'Conflicts of interest and gifts: everyone declares for themselves, administration reviews',
    'Encrypted internal whistleblowing channel, appointed officers, anonymous follow-up by code',
    'Timestamped audit log, exportable, and sealed by fingerprint chaining',
    'GDPR: processing register, right of access exported, reasoned erasure',
    'Configurable approval flows: forms, thresholds, approvers by role',
  ],
  'shot.membre-espace': 'Employee workspace',
  'shot.membre-equipe': 'Manager workspace',
  'shot.membre-demandes': 'Internal requests',
  'shot.membre-agenda': 'Personal and shared calendar',
  'shot.membre-salles': 'Rooms and bookings',
  'shot.membre-messagerie': 'Internal messaging',
  'shot.membre-connaissances': 'Knowledge base',
  'shot.membre-coffre-fort': 'Digital vault',
  'shot.membre-profil': 'Profile and account security',
  'shot.membre-juridique-membre': 'My declarations',
  'shot.annuaire': 'Company directory',
  'shot.organigramme': 'Org chart',
  'shot.connexion': 'Sign-in screen',
  'shot.pilotage': 'Management dashboard',
  'shot.admin': 'Administration console',
  'shot.rh': 'Human resources',
  'shot.gestion': 'Finance and administration',
  'shot.direction': 'Management and governance',
  'shot.projets': 'Projects, milestones and profitability',
  'shot.support': 'Support and tickets',
  'shot.planning': 'Scheduling, rotations and on-call',
  'shot.qualite': 'Quality and internal audits',
  'shot.sante-securite': 'Health and safety at work',
  'shot.informatique': 'Software estate and access',
  'shot.developpement': 'Services and releases',
  'shot.evenements': 'Company events',
  'shot.juridique': 'Corporate and compliance',
  'shot.alertes': 'Whistleblowing channel',
  'shot.securite': 'Security console',
  'shot.rgpd': 'Personal data',
  'shot.parapheur': 'Signature folder',
  'shot.sauvegardes': 'Backups and restore',
  'shot.comptabilite': 'Double-entry accounting',
  'shot.paie': 'Payroll engine',
  'shot.tresorerie': 'Treasury and forecast',
  'shot.immobilisations': 'Fixed assets and depreciation',
  'shot.crm': 'Sales CRM',
  'shot.stock': 'Stock and purchasing',
  'shot.accueil': 'Front desk, visitors and mail',
  'shot.flotte': 'Vehicle fleet',
  'shot.parcours': 'Career paths and skills',
  'shot.import': 'Data import',
  'shot.integrations': 'Interfaces and connectors',
  'shot.pieces': 'Incoming documents',
  'shot.facturation': 'Electronic invoicing',
  'shot.recherche': 'Search across everything',
  'shot.notifications': 'Notification centre',
  'shot.membre-cse': 'Works council',
  'shot.pilotage-sombre': 'Dashboard — dark theme',
  'shot.membre-espace-sombre': 'Employee workspace — dark theme',
  'shot.gestion-sombre': 'Finance — dark theme',
  'shot.projets-sombre': 'Projects — dark theme',
  'shot.juridique-sombre': 'Corporate — dark theme',
  'shot.securite-sombre': 'Security — dark theme',
  'tour.pilotage': 'Headcount, invoiced, margin, cash, support: what management looks at, on one page. A dash marks missing data — never a zero that would pass for a figure.',
  'tour.membre-espace': 'The page everyone opens in the morning: their manager, the news that concerns them, their requests, the documents to acknowledge, their tools and logins.',
  'tour.rh': 'Requests to handle, balances, payslips, documents, training, reviews: the employee file lives here, and the deadlines surface by themselves.',
  'tour.gestion': 'Third parties, contracts and notice periods, invoices both ways, departmental budgets, expenses, collections. A budget\'s consumption adds itself up.',
  'tour.projets': 'Milestones, tasks in columns, time logged and profitability against budget. Cost is not typed in: it follows from the hours and the hourly rate.',
  'tour.juridique': 'Capital, corporate mandates, general meetings and minutes, delegations, declarations of interest. What a company must be able to prove, kept up as you go.',
  'pricing.perEmployee': '€5 per employee per month',
  'pricing.perEmployeeShort': 'per employee / month',
  'pricing.argTitle': 'Five euros per employee, for everything',
  'pricing.argBody': 'An HR tool, an accounting package, a project tracker, a support desk, a payslip vault: five subscriptions at €8 or €15 per user, five databases that don\'t talk to each other, five invoices. Toutadmin replaces the whole stack for the price of the cheapest one — and the data finally sits in one place.',
  'pricing.gridTitle': 'The grid, by headcount',
  'pricing.gridLede': 'The price follows headcount and nothing else: €5 per employee up to two hundred and forty-nine, €4 from two hundred and fifty to five hundred, €3 above. Crossing a bracket lowers the bill for everyone, not just for the newcomers.',
  'pricing.col.headcount': 'Headcount',
  'pricing.col.monthly': 'Per month',
  'pricing.col.perEmployee': 'Per employee',
  'pricing.upTo': 'Up to {count} employees',
  'pricing.under': 'Under {count} employees',
  'pricing.once': 'one-off',
  'pricing.lifetimeTitle': 'Why a lifetime licence',
  'pricing.lifetimeBody': 'Ten thousand euros once, no subscription and no time limit: the same instance, the same updates, no headcount ceiling. At a hundred employees it pays for itself in twenty months, at five hundred in five. It is the offer for those who prefer an investment to a recurring line in the accounts — and who would rather depend on nobody to keep working.',
  'faq.q9': 'What happens if my headcount changes during the year?',
  'faq.a9': 'The price follows, both ways, from the following month and never retroactively. A hire that pushes you over a threshold is billed the month after; a departure that brings you back down, likewise. Nobody pays for closed accounts.',
  'faq.q10': 'Does the lifetime licence include updates?',
  'faq.a10': 'Yes, with no time limit: that is what the word lifetime means. You get the same versions as the monthly plans, and you can host the database yourself. What the licence does not include is priority support, which stays a separate service.',
  'pricing.someEmployees': '{count} employees',
  'nav.docs': 'Documentation',
  'menu.title': 'The whole site',
  'menu.close': 'Close the site map',
  'menu.domains': 'The fourteen domains',
  'menu.home.d': 'What the product covers, in numbers, and a look at the screens.',
  'menu.features.d': 'The complete list, domain by domain: more than a hundred and thirty functions shipped and tested.',
  'menu.screens.d': 'Forty screenshots from a real instance, in light and dark themes.',
  'menu.security.d': 'Authentication, sealed log, personal data, whistleblowing channel, backups — and the limits we own up to.',
  'menu.pricing.d': 'The per-employee price, the grid by headcount and the lifetime licence.',
  'menu.contact.d': 'Book a demonstration on your own cases, or write to us.',
  'menu.docs.d': 'Installation, configuration, security, API and the full glossary. Separate site.',
  'menu.home': 'Home',
  'menu.group.product': 'The product',
  'menu.group.decide': 'To decide',
  'menu.group.more': 'Going further',
};
