/* es — traduit du français. Toute clé du français doit exister ici :
   le build refuse de construire une langue incomplète. */
module.exports = {
  'locale.name': 'Español',
  'site.name': 'Toutadmin',
  'site.tagline': 'El CMS que administra toda la empresa',
  'nav.product': 'Producto',
  'nav.features': 'Funciones',
  'nav.screens': 'Las pantallas',
  'nav.security': 'Seguridad',
  'nav.pricing': 'Precios',
  'nav.contact': 'Contacto',
  'nav.demo': 'Pedir una demo',
  'nav.menu': 'Menú',
  'nav.language': 'Idioma',
  'nav.theme': 'Tema',
  'nav.themeLight': 'Claro',
  'nav.themeDark': 'Oscuro',
  'nav.themeSystem': 'Sistema',
  'hero.eyebrow': 'Software de gestión empresarial',
  'hero.title': 'Toda su empresa,\nen un solo software.',
  'hero.lede': 'Personal, recursos humanos, finanzas, operaciones, gobernanza, cumplimiento, servicios generales. Treinta y cinco espacios que se hablan, una sola base de datos, ninguna aplicación que pegar. En dieciséis idiomas, y 5 € por empleado y mes para gestionarlo todo.',
  'hero.ctaPrimary': 'Probar gratis',
  'hero.ctaSecondary': 'Ver las funciones',
  'hero.note': 'Sin tarjeta bancaria. Sus datos siguen siendo suyos, y pueden quedarse en su casa.',
  'hero.badge1': 'SaaS listo en cinco minutos',
  'hero.badge2': 'o alojado en su servidor',
  'hero.badge3': 'RGPD por diseño',
  'stats.title': 'Lo que cubre el producto, en cifras',
  'stats.spaces': 'espacios de trabajo',
  'stats.spacesNote': 'del espacio del empleado a la vida jurídica',
  'stats.languages': 'idiomas de interfaz',
  'stats.languagesNote': 'árabe incluido, página invertida',
  'stats.tests': 'pruebas de integración',
  'stats.testsNote': 'ejecutadas en cada entrega',
  'stats.modules': 'módulos activables',
  'stats.modulesNote': 'contabilidad, nóminas, tesorería, CRM…',
  'stats.deps': 'servicios externos necesarios',
  'stats.depsNote': 'una máquina, una base, nada más',
  'stats.keys': 'etiquetas traducidas',
  'stats.keysNote': 'hasta los cuadros de confirmación',
  'pillars.title': 'Por qué Toutadmin y no cinco herramientas pegadas',
  'pillars.lede': 'Cinco programas que no se hablan cuestan más que uno solo, y hacen perder lo que importa: la visión de conjunto. Toutadmin parte de lo contrario: una base, espacios y derechos.',
  'pillars.1.title': 'Un solo sitio, una sola verdad',
  'pillars.1.body': 'El presupuesto de un departamento agrega por sí mismo sus facturas y las notas de gastos aprobadas de sus miembros. Una recepción de pedido entra en el almacén en el mismo gesto. Nadie vuelve a teclear nada, así que nadie se contradice.',
  'pillars.2.title': 'Los permisos no son decorativos',
  'pillars.2.body': 'Cada ruta lleva su control en el servidor, y las adscripciones se releen en cada petición. Una baja corta el acceso de inmediato, no cuando caduca la cookie. Lo que no tiene derecho a ver, ni siquiera se busca.',
  'pillars.3.title': 'Los vencimientos vienen a usted',
  'pillars.3.body': 'Preaviso de contrato, habilitación por renovar, reconocimiento médico, ITV, mandato social, certificado de un proveedor: un solo motor los reúne y avisa a la persona correcta, una vez, sin duplicados.',
  'pillars.4.title': 'Cada pantalla dice lo que no hace',
  'pillars.4.body': 'Un módulo muestra su límite al activarlo, no en el fondo de un manual. Preferimos una frase honesta a una casilla marcada: es lo que evita las malas sorpresas al tercer mes.',
  'pillars.5.title': 'Dieciséis idiomas, de verdad',
  'pillars.5.body': 'No solo la pantalla de inicio: los estados, los mensajes de error, los cuadros de confirmación. El árabe invierte la página entera, porque la hoja de estilo solo usa propiedades lógicas.',
  'pillars.6.title': 'Sus datos, en su casa si quiere',
  'pillars.6.body': 'En SaaS todo está listo en cinco minutos. En los planes de pago también puede alojar la base en su propio servidor: mismo software, mismas actualizaciones, datos entre sus paredes.',
  'tour.title': 'Software denso, no un juguete',
  'tour.lede': 'Pantallas hechas para quien las abre ocho horas al día: información de un vistazo, sin ventanas modales inútiles, y el mismo vocabulario en todas partes.',
  'tour.hint': 'Pulse una pestaña para cambiar de pantalla.',
  'tour.all': 'Ver las 40 pantallas',
  'features.title': 'Todo lo que Toutadmin sabe hacer',
  'features.lede': 'La lista completa, dominio por dominio. Cada línea corresponde a código entregado y probado, no a una intención.',
  'features.legend': 'Las funciones marcadas «módulo» se activan desde la consola cuando hacen falta.',
  'features.module': 'módulo',
  'features.seeAll': 'Ver la lista completa',
  'features.intro': 'Catorce dominios, más de ciento treinta funciones.',
  'features.ctaTitle': '¿Falta algo?',
  'features.ctaBody': 'Díganoslo. El producto avanza por lotes, y las peticiones de las empresas que lo usan pasan primero.',
  'screens.title': 'Las pantallas, sin retoques',
  'screens.lede': 'Todas las capturas de este sitio salen de una instancia real con datos de demostración. Ninguna maqueta, ningún montaje.',
  'screens.light': 'Tema claro',
  'screens.dark': 'Tema oscuro',
  'screens.member': 'Espacio del empleado',
  'screens.admin': 'Administración y dirección',
  'screens.modules': 'Módulos opcionales',
  'screens.open': 'Ampliar',
  'screens.close': 'Cerrar',
  'screens.prev': 'Anterior',
  'screens.next': 'Siguiente',
  'security.title': 'La seguridad no es una opción de pago',
  'security.lede': 'Todo lo que sigue está en el producto, sea cual sea el plan, incluido el gratuito.',
  'security.1.title': 'Autenticación reforzada',
  'security.1.body': 'Contraseñas cifradas (bcrypt), política de complejidad, bloqueo tras varios fallos, doble factor TOTP con códigos de recuperación, sesiones revocables una a una o todas de golpe.',
  'security.2.title': 'Registro de auditoría sellado',
  'security.2.body': 'Cada entrada lleva la huella de la anterior. Modificar una línea, o quitar una del medio, rompe la cadena en ese punto, y la verificación dice cuál. Lo que no hace: impedir la reescritura a quien controla el servidor; la hace visible.',
  'security.3.title': 'Datos personales',
  'security.3.body': 'Registro de tratamientos, derecho de acceso exportado fuente por fuente, supresión que conserva lo que la ley obliga a conservar y lo dice. La cuenta se anonimiza en lugar de borrarse, para que los asientos que la referencian sigan siendo coherentes.',
  'security.4.title': 'Canal de alertas internas',
  'security.4.body': 'Obligatorio en Francia a partir de cincuenta empleados. Contenido cifrado en la base, legible solo por los referentes designados, no por los administradores, ya que una alerta puede señalar a uno. Seguimiento anónimo por código, sin cuenta y sin registro.',
  'security.5.title': 'Copias de seguridad verificadas',
  'security.5.body': 'Archivo cada hora, control de integridad por manifiesto, restauración que devuelve base y ficheros, externalización por FTPS o Google Drive, y aviso a los administradores si falla.',
  'security.6.title': 'Secretos cifrados',
  'security.6.body': 'Contraseñas de servicios externos, tokens de API, secretos de webhooks: cifrados en AES-256-GCM, nunca vueltos a mostrar en claro, ilegibles tras cualquier alteración.',
  'security.hostTitle': 'SaaS, o en su casa',
  'security.hostBody': 'En SaaS alojamos en Europa, copias incluidas. En los planes de pago es posible el alojamiento local: usted instala en su servidor, la base nunca sale de sus paredes, y recibe las mismas actualizaciones. Basta una máquina: Node 22 y SQLite, ninguna base externa que administrar.',
  'security.limitsTitle': 'Lo que no pretendemos hacer',
  'security.limitsBody': 'La firma electrónica es simple, no cualificada según eIDAS. La caja fuerte sella y fecha los documentos, pero un sellado de tiempo oponible a terceros exige una autoridad de certificación. Ninguna presentación fiscal o social: el software produce los datos, su depósito sigue siendo cosa de su asesoría. Está escrito aquí y no después de firmar.',
  'pricing.title': 'Precios legibles, sin sorpresas',
  'pricing.lede': 'Un solo precio, por empleado y por mes, para gestionar toda la empresa. Sin módulos a la carta, sin recargo por función: todo el producto está en todos los planes.',
  'pricing.perMonth': '/ mes',
  'pricing.free': 'Gratis',
  'pricing.vat': 'Precios sin impuestos. Sin permanencia en los planes mensuales.',
  'pricing.cta': 'Empezar',
  'pricing.ctaCustom': 'Escríbanos',
  'pricing.popular': 'El más elegido',
  'pricing.p1.name': 'Gratis',
  'pricing.p1.for': 'Menos de 5 empleados',
  'pricing.p1.body': 'Todo el producto, gratis, sin límite de tiempo y sin funciones recortadas. El plan para una empresa joven, una asociación o un despacho que empieza.',
  'pricing.p2.name': 'Suscripción',
  'pricing.p2.for': 'A partir de 5 empleados',
  'pricing.p2.body': '5 € por empleado y mes, luego 4 € de doscientos cincuenta a quinientos, y 3 € por encima. Paga la plantilla que tiene, no la que quizá tenga algún día.',
  'pricing.p4.name': 'Licencia de por vida',
  'pricing.p4.for': 'Pago único',
  'pricing.p4.body': '10.000 € una vez. Sin suscripción, sin límite de tiempo, sin tope de plantilla. El software es suyo mientras quiera usarlo.',
  'pricing.tableTitle': 'Lo que incluye cada plan',
  'pricing.col.feature': '',
  'pricing.yes': 'Incluido',
  'pricing.no': 'No',
  'pricing.option': 'Opcional',
  'pricing.f.allSpaces': 'Los 35 espacios y los 7 módulos',
  'pricing.f.languages': 'Los 16 idiomas y las 3 paletas',
  'pricing.f.security': 'Seguridad completa, registro sellado, RGPD',
  'pricing.f.updates': 'Actualizaciones incluidas',
  'pricing.f.saas': 'Alojamiento SaaS en Europa',
  'pricing.f.local': 'Alojamiento local de sus datos',
  'pricing.f.backupOff': 'Externalización de las copias',
  'pricing.f.support': 'Asistencia',
  'pricing.f.supportMail': 'Por correo',
  'pricing.f.supportPrio': 'Prioritaria',
  'pricing.f.supportDedicated': 'Interlocutor dedicado',
  'pricing.f.supportCommunity': 'Documentación',
  'pricing.f.migration': 'Migración de sus datos',
  'pricing.f.sla': 'Compromiso de servicio (SLA)',
  'pricing.f.api': 'API de lectura y webhooks',
  'pricing.f.multisite': 'Varias sedes, varias entidades',
  'pricing.countTitle': 'Cómo contamos a los empleados',
  'pricing.countBody': 'Las cuentas activas, autónomos y becarios incluidos, administradores excluidos. Una cuenta cerrada ya no cuenta, aunque conserve el acceso a su caja fuerte. ¿Cruza un umbral? El cambio se aplica al mes siguiente, sin retroactividad, y se baja de la misma manera.',
  'faq.title': 'Preguntas frecuentes',
  'faq.q1': '¿El plan gratuito está limitado en el tiempo?',
  'faq.a1': 'No. Por debajo de cinco empleados, el producto es gratis sin límite de tiempo y sin funciones recortadas. Preferimos una estructura pequeña que crece con el software a una versión de prueba que se apaga a los treinta días.',
  'faq.q2': '¿Puedo alojar mis datos en mi propio servidor?',
  'faq.a2': 'Sí, en los planes de pago. El software funciona en una sola máquina con Node 22 y SQLite: ni servidor de base de datos, ni servicio externo. Usted conserva la base, los documentos y las copias.',
  'faq.q3': '¿Qué pasa si lo dejo?',
  'faq.a3': 'Exporta la instancia entera en JSON, documentos incluidos, desde la consola de administración. Nada queda retenido: es su base, y se va con usted en un formato legible.',
  'faq.q4': '¿Sustituye a mi asesor contable?',
  'faq.a4': 'No. La contabilidad por partida doble, las nóminas y el IVA están para llevar sus asientos y preparar los documentos. No hay declaraciones oficiales ni presentación telemática: la exportación alimenta a su asesoría.',
  'faq.q5': '¿Hay que formar a los equipos?',
  'faq.a5': 'El espacio del empleado se entiende solo: vacaciones, documentos, turnos, directorio. Los espacios de administración piden media jornada de toma de contacto, que acompañamos en los planes de pago.',
  'faq.q6': '¿Puedo activar solo una parte del producto?',
  'faq.a6': 'Sí. Siete módulos —contabilidad, nóminas, facturación electrónica, almacén y compras, tesorería, inmovilizado, CRM— están apagados por defecto y se activan uno a uno. Mientras un módulo está apagado, sus direcciones responden 404.',
  'faq.q7': '¿Cómo se migran mis datos actuales?',
  'faq.a7': 'Una importación masiva en CSV comprueba cada línea antes de escribir, y no escribe nada si una sola línea es inválida. En los planes de pago preparamos los ficheros con usted.',
  'faq.q8': '¿Y las integraciones con nuestras herramientas?',
  'faq.a8': 'Se incluyen en todos los planes una API REST de lectura con ámbitos y webhooks salientes firmados. Para intercambios específicos —RRHH, ERP, facturación— escríbanos: ese trabajo se presupuesta caso por caso.',
  'contact.title': 'Hablemos de su empresa',
  'contact.lede': 'Una demostración dura treinta minutos, sobre sus casos y no sobre datos inventados. Escríbanos qué quiere resolver.',
  'contact.emailLabel': 'Por correo',
  'contact.demoTitle': 'Pedir una demostración',
  'contact.demoBody': 'Indique su nombre, su empresa, su plantilla y lo que le da problemas hoy. Respondemos en un día laborable.',
  'contact.write': 'Escribir al equipo',
  'contact.docTitle': 'Leer la documentación',
  'contact.docBody': 'El sitio de documentación detalla la instalación, la configuración, la seguridad, la API y el glosario completo en los dieciséis idiomas.',
  'contact.docCta': 'Abrir la documentación',
  'contact.selfTitle': 'Instalarlo usted mismo',
  'contact.selfBody': 'Node 22, una máquina, cinco minutos: el asistente crea la base, la cuenta de administrador y comprueba el entorno.',
  'contact.selfCta': 'Ver los requisitos',
  'cta.title': 'Empiece gratis y cambie de plan cuando crezca',
  'cta.body': 'Por debajo de cinco empleados todo es gratis. Por encima, 5 € por empleado y mes —decreciente a partir de doscientos cincuenta— o 10.000 € una vez por la licencia de por vida. Ninguna tarjeta para probar.',
  'cta.primary': 'Crear mi instancia',
  'cta.secondary': 'Hablar con alguien',
  'foot.product': 'Producto',
  'foot.company': 'Quiénes somos',
  'foot.resources': 'Recursos',
  'foot.legal': 'Avisos',
  'foot.docs': 'Documentación',
  'foot.status': 'Lo que está cubierto',
  'foot.rights': 'Todos los derechos reservados.',
  'foot.madeWith': 'Node 22 · Express · SQLite. Ninguna dependencia inútil.',
  'foot.langTitle': 'Este sitio existe en dieciséis idiomas',
  'dom.socle.title': 'Base y organización',
  'dom.socle.lede': 'Lo que sostiene el resto: las cuentas, las adscripciones y el vocabulario común a todos los espacios.',
  'dom.socle.items': [
    'Cuentas y roles acumulables: administrador, RRHH, gestión, informática, referente de alertas',
    'Mánager deducido de la supervisión real, nunca concedido a mano',
    'Departamentos y equipos, varios mánagers por ámbito, adscripciones releídas en cada petición',
    'Organigrama visual, mandos incluidos, y las personas sin adscripción',
    'Directorio con búsqueda y filtros, visibilidad controlada solo por la administración',
    'Mensajería interna, y dirección profesional configurada por la administración',
    'Búsqueda global aislada en el origen: lo que no puede ver, no se busca',
    'Centro de notificaciones por persona, con acuse de lectura',
    'Importación masiva en CSV: vista previa controlada, escritura todo o nada',
    'Asistente de instalación, ajustes de la instancia, siete módulos activables',
    '16 idiomas, 3 paletas, tema claro/oscuro/sistema, interfaz adaptable',
  ],
  'dom.espace.title': 'Espacio del empleado',
  'dom.espace.lede': 'La página que todos abren por la mañana: lo que les concierne, y nada más.',
  'dom.espace.items': [
    'Panel personal: mánager, novedades, solicitudes, documentos por acusar',
    'Vacaciones, permisos, ausencias y teletrabajo: días hábiles calculados, fines de semana excluidos',
    'Saldo de vacaciones al día, historial de ajustes motivados',
    'Nóminas consultables y conservadas cincuenta años en la caja fuerte',
    'Agenda personal y agenda compartida de equipo',
    'Turnos de la semana, guardias, permanencias',
    'Herramientas asignadas con su propio usuario: no se guarda ninguna contraseña externa',
    'Perfil: foto, presentación, teléfono, idioma, contraseña, cierre de sesiones',
    'Fichaje con cronómetro para autónomos, uno solo en curso a la vez',
    'Declaración de intereses y de regalos, visible solo para uno mismo',
  ],
  'dom.rh.title': 'Recursos humanos',
  'dom.rh.lede': 'El expediente del empleado, de su llegada a su salida, con los vencimientos que conlleva.',
  'dom.rh.items': [
    'Aprobación de solicitudes con descuento del saldo, rechazo motivado, anulación que devuelve los días',
    'Nóminas: creación, seguimiento del pago, generación por lotes',
    'Documentos de empresa con acuse de recibo nominativo',
    'Formación: catálogo, sesiones, inscripciones, coste y duración',
    'Entrevistas anuales: campaña, guion, informe',
    'Alta y baja: listas de control seguidas, responsable y plazo por tarea',
    'Competencias y habilitaciones, con fecha de reciclaje y aviso anticipado',
    'Reuniones individuales: resumen compartido, notas del mánager aparte',
    'Caja fuerte digital accesible tras la salida, documentos sellados por su huella',
    'Firma electrónica simple: circuito ordenado, huella, sello, certificado',
    'Contratos temporales: la cuenta se cierra sola el día previsto',
  ],
  'dom.talent.title': 'Selección y talento',
  'dom.talent.lede': 'De las candidaturas al primer día, sin hoja de cálculo intermedia.',
  'dom.talent.items': [
    'Ofertas de empleo y seguimiento de candidaturas por etapa',
    'Recepción de CV: PDF, DOCX o texto, escritos fuera del repositorio',
    'Extracción del contenido y base de CV consultable',
    'Criterios ponderados, puntuación, umbral, clasificación de candidaturas',
    'El candidato elegido pasa al itinerario de incorporación',
    'Encuestas internas y barómetro social, anónimos por construcción',
    'Por debajo de cinco respuestas no se muestra ningún resultado',
  ],
  'dom.sst.title': 'Salud, seguridad y comité',
  'dom.sst.lede': 'Las obligaciones que se llevan por escrito y se recuerdan solas.',
  'dom.sst.items': [
    'Evaluación de riesgos: unidades de trabajo, peligros, valoración, medidas, revisión fechada',
    'Registro de accidentes de trabajo y de incidentes sin daños, días de baja',
    'Equipos de protección: entrega nominativa, validez, renovación',
    'Reconocimientos médicos: de ingreso, periódico, de reincorporación, a petición',
    'Comité: elecciones, censo, voto anónimo, mandatos y su vencimiento',
    'Reuniones del comité, ventajas y prestaciones para el personal',
    'El espacio de gestión se cierra solo al terminar el mandato',
  ],
  'dom.finance.title': 'Finanzas y gestión',
  'dom.finance.lede': 'Los terceros, los contratos, el dinero que entra y el que sale.',
  'dom.finance.items': [
    'Clientes y proveedores, ficha completa: contactos, contratos, facturas',
    'Contratos y sobre todo preavisos: la fecha límite para rescindir se calcula y se avisa',
    'Facturas en ambos sentidos, total calculado, retraso deducido del vencimiento',
    'Presupuestos por departamento y ejercicio, consumo agregado automáticamente',
    'Notas de gastos: presentación, aprobación, reembolso, nunca lo uno sin lo otro',
    'Documentos de cumplimiento de terceros, fechados y avisados cuarenta y cinco días antes',
    'Evaluaciones de proveedores puntuadas: vale la última revisión, no la media',
    'Multidivisa con el tipo fijado al emitir cada documento',
    'Facturación recurrente: la suscripción es el molde, la factura es el documento',
    'Lectura automática de facturas recibidas y captura IMAP de un buzón contable',
  ],
  'dom.compta.title': 'Contabilidad, nóminas e IVA',
  'dom.compta.lede': 'Módulos apagados por defecto, que se activan cuando hacen falta.',
  'dom.compta.items': [
    'Contabilidad por partida doble: plan contable, diarios, balance, libro mayor',
    'Un asiento descuadrado se rechaza, y el mensaje dice por cuánto',
    'Una factura pasa a asiento con un clic; exportación CSV para la asesoría',
    'Motor de nóminas: baremos configurables, del bruto al neto, cuota patronal, coste empresa',
    'Nómina detallada línea a línea, generación por lotes, simulador',
    'Declaraciones de IVA: repercutido, soportado, desglose por tipo, crédito a compensar',
    'Una declaración presentada ya no se recalcula: es un documento, no un panel',
    'Facturación electrónica: control EN 16931 y exportación del XML CII',
    'Tesorería: cuentas, movimientos, conciliación, previsión a doce semanas',
    'Inmovilizado: amortización lineal y decreciente, valor neto contable',
  ],
  'dom.achats.title': 'Compras, almacén y cobros',
  'dom.achats.lede': 'Lo que se pide, lo que llega, lo que se factura, y lo que nos deben.',
  'dom.achats.items': [
    'Solicitudes de compra validadas por el mánager y luego por gestión a partir del umbral',
    'Pedidos, recepciones y conciliación a tres: pedido, recibido, facturado',
    'Recibir más de lo pedido se rechaza; la diferencia de facturación se nombra, no se bloquea',
    'Artículos, movimientos, umbral de alerta: el stock es la suma de los movimientos',
    'Una línea ligada a un artículo entra en almacén en el momento de su recepción',
    'Balance de antigüedad de clientes por tramo de retraso',
    'Reclamaciones escalonadas: recordatorio, reclamación, requerimiento, según lo ya enviado',
    'Cada reclamación registrada con su nivel y su fecha',
  ],
  'dom.projets.title': 'Proyectos, tiempo y rentabilidad',
  'dom.projets.lede': 'Saber en qué punto está un proyecto y lo que ha costado de verdad.',
  'dom.projets.items': [
    'Proyectos ligados a un cliente, un departamento, un equipo y un responsable',
    'Hitos fechados y tareas en columnas por estado, con prioridad y estimación',
    'Tiempo imputado al proyecto y a la tarea, 24 h como máximo por registro',
    'Rentabilidad: horas, coste al precio hora, margen restante, parte del presupuesto consumida',
    'Tres círculos de derechos: la gestión, el responsable, los miembros',
    'Tiempo por persona y salud de los proyectos en el panel de dirección',
  ],
  'dom.support.title': 'Soporte y conocimiento',
  'dom.support.lede': 'Las peticiones internas y de clientes en un mismo circuito, y las respuestas que quedan.',
  'dom.support.items': [
    'Tickets internos y de clientes, prioridad, origen, asignación',
    'Plazo de primera respuesta deducido de la prioridad, recalculado desde la apertura',
    'Notas internas invisibles para quien pide, y que no cuentan como respuesta',
    'Aislamiento por categoría: una petición de RRHH no sale de RRHH',
    'Base de conocimiento por categoría, búsqueda de texto completo, alcance ajustable',
    'Indicadores: tickets abiertos, retrasados, plazo medio',
  ],
  'dom.ops.title': 'Operaciones y servicios generales',
  'dom.ops.lede': 'Los turnos, la calidad, las salas, los vehículos, la recepción.',
  'dom.ops.items': [
    'Turnos por persona y por día: puestos, guardias, permanencias, teletrabajo',
    'Solapamiento o ausencia ya concedida: el turno se rechaza al crearlo',
    'Rotaciones reutilizables, turnos de noche, publicación de la semana',
    'Quién está de guardia en este momento, con su número',
    'Calidad: no conformidades, causas raíz, acciones correctivas y verificación de eficacia',
    'Auditorías internas: hallazgos, síntesis, un hallazgo convertido en no conformidad',
    'Equipos asignados y devueltos, con historial de poseedores',
    'Salas y reservas, solapamiento rechazado diciendo quién la ocupa',
    'Flota: mantenimiento, ITV, seguro, siniestros, kilometraje',
    'Recepción: registro de visitantes, lista de presentes, correo entrante y saliente',
  ],
  'dom.direction.title': 'Dirección y gobernanza',
  'dom.direction.lede': 'Lo que la dirección mira, y lo que decide.',
  'dom.direction.items': [
    'Panel: plantilla, ausentes, facturado, margen, masa salarial, tesorería, soporte',
    'Objetivos y resultados clave, cada uno en su escala, incluso decreciente',
    'Reuniones: convocatoria, orden del día, asistencia registrada, acta',
    'Registro de decisiones con su motivo: lo que se busca dos años después',
    'Acciones encargadas con responsable y plazo, ligadas a su decisión',
    'Registro de riesgos: valoración bruta y residual, matriz 5 × 5, tratamiento, revisión',
    'Eventos de empresa: aforo, lista de espera automática, firma de asistencia, presupuesto',
    'Vencimientos de todos los espacios reunidos en una sola lista ordenada',
  ],
  'dom.it.title': 'Informática y desarrollo',
  'dom.it.lede': 'El parque de software, los accesos, las incidencias y lo que entrega el equipo.',
  'dom.it.items': [
    'Parque de software: licencias tratadas como restricción, coste anualizado, renovaciones',
    'Revisión de accesos: primero las cuentas cerradas, luego los permisos de administración',
    'Incidencias de sistemas, con hora, y tiempo medio de restablecimiento medido',
    'Catálogo de servicios: criticidad, responsable, repositorio, documentación',
    'Registro de despliegues por entorno e indicadores de entrega',
    'Copias de seguridad: archivo horario, integridad verificada, restauración, externalización',
    'API REST de lectura con ámbitos, webhooks salientes firmados',
    'Exportación íntegra de la instancia en JSON, documentos incluidos, secretos excluidos',
  ],
  'dom.conformite.title': 'Cumplimiento, jurídico y datos personales',
  'dom.conformite.lede': 'Lo que una empresa debe poder demostrar, mantenido al día.',
  'dom.conformite.items': [
    'Registro de socios: participación deducida de los movimientos, transmisión escrita en dos asientos',
    'Cargos sociales con duración, revocación y fin avisado con antelación',
    'Juntas generales: quórum en participaciones, acuerdos, votos, acta',
    'Delegaciones de poder: objeto, límite, duración, vencimiento avisado',
    'Conflictos de interés y regalos: cada cual declara lo suyo, la administración revisa',
    'Canal interno de alertas cifrado, referentes designados, seguimiento anónimo por código',
    'Registro de auditoría con hora, exportable y sellado por encadenamiento de huellas',
    'RGPD: registro de tratamientos, derecho de acceso exportado, supresión razonada',
    'Circuitos de aprobación configurables: formularios, umbrales, validadores por función',
  ],
  'shot.membre-espace': 'Espacio del empleado',
  'shot.membre-equipe': 'Espacio del mánager',
  'shot.membre-demandes': 'Solicitudes internas',
  'shot.membre-agenda': 'Agenda personal y compartida',
  'shot.membre-salles': 'Salas y reservas',
  'shot.membre-messagerie': 'Mensajería interna',
  'shot.membre-connaissances': 'Base de conocimiento',
  'shot.membre-coffre-fort': 'Caja fuerte digital',
  'shot.membre-profil': 'Perfil y seguridad de la cuenta',
  'shot.membre-juridique-membre': 'Mis declaraciones',
  'shot.annuaire': 'Directorio de la empresa',
  'shot.organigramme': 'Organigrama',
  'shot.connexion': 'Pantalla de acceso',
  'shot.pilotage': 'Panel de dirección',
  'shot.admin': 'Consola de administración',
  'shot.rh': 'Recursos humanos',
  'shot.gestion': 'Gestión administrativa y financiera',
  'shot.direction': 'Dirección y gobernanza',
  'shot.projets': 'Proyectos, hitos y rentabilidad',
  'shot.support': 'Soporte y tickets',
  'shot.planning': 'Turnos, rotaciones y guardias',
  'shot.qualite': 'Calidad y auditorías internas',
  'shot.sante-securite': 'Salud y seguridad en el trabajo',
  'shot.informatique': 'Parque de software y accesos',
  'shot.developpement': 'Servicios y despliegues',
  'shot.evenements': 'Eventos de empresa',
  'shot.juridique': 'Vida jurídica y cumplimiento',
  'shot.alertes': 'Canal de alertas internas',
  'shot.securite': 'Consola de seguridad',
  'shot.rgpd': 'Datos personales',
  'shot.parapheur': 'Carpeta de firmas',
  'shot.sauvegardes': 'Copias y restauración',
  'shot.comptabilite': 'Contabilidad por partida doble',
  'shot.paie': 'Motor de nóminas',
  'shot.tresorerie': 'Tesorería y previsión',
  'shot.immobilisations': 'Inmovilizado y amortizaciones',
  'shot.crm': 'CRM comercial',
  'shot.stock': 'Almacén y compras',
  'shot.pilotage-sombre': 'Dirección — tema oscuro',
  'shot.membre-espace-sombre': 'Espacio del empleado — tema oscuro',
  'shot.gestion-sombre': 'Gestión — tema oscuro',
  'shot.projets-sombre': 'Proyectos — tema oscuro',
  'shot.juridique-sombre': 'Vida jurídica — tema oscuro',
  'shot.securite-sombre': 'Seguridad — tema oscuro',
  'tour.pilotage': 'Plantilla, facturado, margen, tesorería, soporte: lo que la dirección mira, en una página. Un guion marca un dato ausente, nunca un cero que parecería una cifra.',
  'tour.membre-espace': 'La página que cada cual abre por la mañana: su mánager, las novedades que le conciernen, sus solicitudes, sus documentos por acusar, sus herramientas y sus usuarios.',
  'tour.rh': 'Solicitudes por tratar, saldos, nóminas, documentos, formación, entrevistas: el expediente del empleado se lleva aquí, y los vencimientos suben solos.',
  'tour.gestion': 'Terceros, contratos y preavisos, facturas en ambos sentidos, presupuestos por departamento, notas de gastos, cobros. El consumo de un presupuesto se agrega solo.',
  'tour.projets': 'Hitos, tareas en columnas, tiempo dedicado y rentabilidad frente al presupuesto. El coste no se teclea: se deduce de las horas y del precio hora.',
  'tour.juridique': 'Capital, cargos sociales, juntas y actas, delegaciones, declaraciones de intereses. Lo que una empresa debe poder demostrar, mantenido al día.',
  'pricing.perEmployee': '5 € por empleado y mes',
  'pricing.perEmployeeShort': 'por empleado / mes',
  'pricing.argTitle': 'Cinco euros por empleado, para todo',
  'pricing.argBody': 'Una herramienta de RRHH, un programa de contabilidad, un gestor de proyectos, un sistema de tickets, una caja fuerte de nóminas: cinco suscripciones a 8 o 15 € por usuario, cinco bases que no se hablan, cinco facturas. Toutadmin sustituye la pila entera por el precio de la más barata, y los datos quedan por fin en un mismo sitio.',
  'pricing.gridTitle': 'La tabla, por plantilla',
  'pricing.gridLede': 'El precio sigue la plantilla y nada más: 5 € por empleado hasta doscientos cuarenta y nueve, 4 € de doscientos cincuenta a quinientos, 3 € por encima. Cruzar un tramo baja la factura de todos, no solo la de los recién llegados.',
  'pricing.col.headcount': 'Plantilla',
  'pricing.col.monthly': 'Al mes',
  'pricing.col.perEmployee': 'Por empleado',
  'pricing.upTo': 'Hasta {count} empleados',
  'pricing.under': 'Menos de {count} empleados',
  'pricing.once': 'pago único',
  'pricing.lifetimeTitle': 'Por qué una licencia de por vida',
  'pricing.lifetimeBody': 'Diez mil euros una vez, sin suscripción y sin límite de tiempo: la misma instancia, las mismas actualizaciones, sin tope de plantilla. Con cien empleados se amortiza en veinte meses; con quinientos, en cinco. Es la oferta para quien prefiere una inversión a una línea de gasto recurrente, y para quien no quiere depender de nadie para seguir trabajando.',
  'faq.q9': '¿Qué pasa si mi plantilla cambia a mitad de año?',
  'faq.a9': 'El precio sigue, en los dos sentidos, desde el mes siguiente y nunca con efecto retroactivo. Una contratación que le hace cruzar un umbral se factura al mes siguiente; una baja que le hace bajar, también. Nadie paga por cuentas cerradas.',
  'faq.q10': '¿La licencia de por vida da derecho a las actualizaciones?',
  'faq.a10': 'Sí, sin límite de tiempo: eso significa «de por vida». Recibe las mismas versiones que los planes mensuales y puede alojar la base en su casa. Lo que la licencia no incluye es la asistencia prioritaria, que sigue siendo un servicio aparte.',
  'pricing.someEmployees': '{count} empleados',
  'nav.docs': 'Documentación',
  'menu.title': 'Todo el sitio',
  'menu.close': 'Cerrar el mapa del sitio',
  'menu.domains': 'Los catorce dominios',
  'menu.home.d': 'Lo que cubre el producto, en cifras, y un vistazo a las pantallas.',
  'menu.features.d': 'La lista completa, dominio por dominio: más de ciento treinta funciones entregadas y probadas.',
  'menu.screens.d': 'Cuarenta capturas de una instancia real, en tema claro y oscuro.',
  'menu.security.d': 'Autenticación, registro sellado, datos personales, canal de alertas, copias de seguridad — y los límites que asumimos.',
  'menu.pricing.d': 'El precio por empleado, la tabla por plantilla y la licencia de por vida.',
  'menu.contact.d': 'Pedir una demostración sobre sus casos, o escribirnos.',
  'menu.docs.d': 'Instalación, configuración, seguridad, API y glosario completo. Sitio aparte.',
  'menu.home': 'Inicio',
};
