/* Français — langue de référence de la vitrine. Toute clé ajoutée ici doit
   l'être dans les quinze autres fichiers : le build refuse de construire une
   langue incomplète plutôt que de servir une page à moitié traduite. */
module.exports = {
  'locale.name': 'Français',
  'site.name': 'Toutadmin',
  'site.tagline': "Le CMS qui administre toute l'entreprise",

  /* ------------------------------------------------------------ navigation */
  'nav.product': 'Le produit',
  'nav.features': 'Fonctionnalités',
  'nav.screens': 'Les écrans',
  'nav.security': 'Sécurité',
  'nav.pricing': 'Tarifs',
  'nav.contact': 'Contact',
  'nav.demo': 'Démo',
  'nav.menu': 'Menu',
  'nav.language': 'Langue',
  'nav.theme': 'Thème',
  'nav.themeLight': 'Clair',
  'nav.themeDark': 'Sombre',
  'nav.themeSystem': 'Système',

  /* ----------------------------------------------------------------- héros */
  'hero.eyebrow': 'Logiciel de gestion d’entreprise',
  'hero.title': 'Toute votre entreprise,\ndans un seul logiciel.',
  'hero.lede': 'Personnel, ressources humaines, finance, opérations, gouvernance, conformité, moyens généraux. Trente-cinq espaces qui se parlent, une seule base, aucune application à recoller. En seize langues, et 5 € par salarié et par mois pour tout gérer.',
  'hero.ctaPrimary': 'Essayer gratuitement',
  'hero.ctaSecondary': 'Voir les fonctionnalités',
  'hero.note': 'Sans carte bancaire. Vos données restent les vôtres, et peuvent rester chez vous.',
  'hero.badge1': 'SaaS prêt en cinq minutes',
  'hero.badge2': 'ou hébergé chez vous',
  'hero.badge3': 'RGPD par construction',

  /* --------------------------------------------------------------- chiffres */
  'stats.title': 'Ce que le produit couvre, en chiffres',
  'stats.spaces': 'espaces métier',
  'stats.spacesNote': "de l'espace du salarié à la vie juridique",
  'stats.languages': "langues d'interface",
  'stats.languagesNote': 'arabe compris, page retournée',
  'stats.tests': "tests d'intégration",
  'stats.testsNote': 'exécutés à chaque livraison',
  'stats.modules': 'modules débloquables',
  'stats.modulesNote': 'comptabilité, paie, trésorerie, CRM…',
  'stats.deps': 'service externe requis',
  'stats.depsNote': 'une machine, une base, rien d’autre',
  'stats.keys': 'libellés traduits',
  'stats.keysNote': 'jusqu’aux boîtes de confirmation',

  /* ---------------------------------------------------------------- piliers */
  'pillars.title': 'Pourquoi Toutadmin plutôt qu’un assemblage d’outils',
  'pillars.lede': "Cinq logiciels qui ne se parlent pas coûtent plus cher qu'un seul, et font perdre ce qui compte : la vue d'ensemble. Toutadmin part de l'inverse — une base, des espaces, des droits.",
  'pillars.1.title': 'Un seul endroit, une seule vérité',
  'pillars.1.body': "Le budget d'un service agrège de lui-même ses factures et les notes de frais de ses membres. Une réception de commande entre en stock dans le même geste. Personne ne ressaisit rien, donc personne ne se contredit.",
  'pillars.2.title': 'Les droits ne sont pas décoratifs',
  'pillars.2.body': "Chaque route porte son garde-fou côté serveur, et les rattachements sont relus à chaque requête. Un départ coupe l'accès immédiatement — pas à l'expiration du cookie. Ce que vous n'avez pas le droit de voir n'est pas cherché du tout.",
  'pillars.3.title': 'Les échéances viennent à vous',
  'pillars.3.body': "Préavis de contrat, habilitation à recycler, visite médicale, contrôle technique, mandat social, attestation de vigilance : un seul moteur les rassemble et prévient la bonne personne, une fois, sans doublon.",
  'pillars.4.title': 'Chaque écran dit ce qu’il ne fait pas',
  'pillars.4.body': "Un module affiche sa limite au moment de l'activer, pas au fond d'une documentation. On préfère une phrase honnête à une case cochée : c'est ce qui évite les mauvaises surprises au troisième mois.",
  'pillars.5.title': 'Seize langues, vraiment',
  'pillars.5.body': "Pas seulement l'écran d'accueil : les statuts, les messages d'erreur, les boîtes de confirmation. L'arabe retourne la page entière, parce que la feuille de style n'emploie que des propriétés logiques.",
  'pillars.6.title': 'Vos données, chez vous si vous voulez',
  'pillars.6.body': "En SaaS, tout est prêt en cinq minutes. Sur les offres payantes, vous pouvez aussi héberger la base sur votre propre serveur : même logiciel, mêmes mises à jour, données dans vos murs.",

  /* ------------------------------------------------------------- aperçu/UI */
  'tour.title': 'Un logiciel dense, pas un jouet',
  'tour.lede': "Des écrans faits pour des gens qui les ouvrent huit heures par jour : information au premier coup d'œil, pas de fenêtre modale inutile, et le même vocabulaire partout.",
  'tour.hint': 'Cliquez sur un onglet pour changer d’écran.',
  'tour.all': 'Voir les 40 écrans',

  /* ------------------------------------------------------- fonctionnalités */
  'features.title': 'Tout ce que Toutadmin sait faire',
  'features.lede': "La liste complète, domaine par domaine. Chaque ligne correspond à du code livré et testé, pas à une intention.",
  'features.legend': 'Les fonctions marquées « module » s’activent à la demande depuis la console.',
  'features.module': 'module',
  'features.seeAll': 'Voir la liste complète',
  'features.intro': 'Quatorze domaines, plus de cent trente fonctions.',
  'features.ctaTitle': 'Il manque quelque chose ?',
  'features.ctaBody': "Dites-le. Le produit avance par lots, et les demandes des entreprises qui l'utilisent passent devant.",

  /* ---------------------------------------------------------------- écrans */
  'screens.title': 'Les écrans, sans retouche',
  'screens.lede': "Toutes les captures de ce site sortent d'une instance réelle peuplée d'un jeu de démonstration. Aucune maquette, aucun montage.",
  'screens.light': 'Thème clair',
  'screens.dark': 'Thème sombre',
  'screens.member': 'Espace du salarié',
  'screens.admin': 'Administration et pilotage',
  'screens.modules': 'Modules optionnels',
  'screens.open': 'Agrandir',
  'screens.close': 'Fermer',
  'screens.prev': 'Précédente',
  'screens.next': 'Suivante',

  /* -------------------------------------------------------------- sécurité */
  'security.title': 'La sécurité n’est pas une option payante',
  'security.lede': "Tout ce qui suit est dans le produit, quelle que soit la formule — y compris la gratuite.",
  'security.1.title': 'Authentification durcie',
  'security.1.body': "Mots de passe hachés (bcrypt), politique de complexité, verrouillage après échecs répétés, double authentification TOTP avec codes de secours, sessions révocables une par une ou toutes d'un coup.",
  'security.2.title': 'Journal d’audit scellé',
  'security.2.body': "Chaque entrée porte l'empreinte de la précédente. Modifier une ligne ou en retirer une du milieu casse la chaîne à cet endroit, et la vérification dit lequel. Ce qu'il ne fait pas : empêcher la réécriture par qui tient le serveur — il la rend visible.",
  'security.3.title': 'Données personnelles',
  'security.3.body': "Registre des traitements, droit d'accès exporté source par source, effacement qui garde ce que la loi impose de garder et le dit. Le compte est anonymisé plutôt que supprimé, pour que les écritures qui le référencent restent cohérentes.",
  'security.4.title': 'Canal d’alerte interne',
  'security.4.body': "Obligatoire dès cinquante salariés en France. Contenu chiffré en base, lisible des seuls référents désignés — pas des administrateurs, puisqu'une alerte peut en viser un. Suivi anonyme par code, sans compte et sans journalisation.",
  'security.5.title': 'Sauvegardes vérifiées',
  'security.5.body': "Archive horaire, contrôle d'intégrité par manifeste, restauration qui remet base et fichiers, externalisation FTPS ou Google Drive, et alerte aux administrateurs en cas d'échec.",
  'security.6.title': 'Secrets chiffrés',
  'security.6.body': "Mots de passe de services tiers, jetons d'API, secrets de webhooks : chiffrés en AES-256-GCM, jamais réaffichés en clair, illisibles après altération.",
  'security.hostTitle': 'SaaS, ou chez vous',
  'security.hostBody': "En SaaS, nous hébergeons en Europe, sauvegardes comprises. Sur les offres payantes, l'hébergement local est possible : vous installez sur votre serveur, la base ne sort jamais de vos murs, et vous recevez les mêmes mises à jour. Une seule machine suffit — Node 22 et SQLite, aucune base externe à administrer.",
  'security.limitsTitle': 'Ce que nous ne prétendons pas faire',
  'security.limitsBody': "La signature électronique est simple, pas qualifiée au sens eIDAS. Le coffre-fort scelle et date les documents, mais l'horodatage opposable à un tiers demande une autorité de certification. Aucune télétransmission fiscale ou sociale : le logiciel produit les données, leur dépôt reste l'affaire d'un tiers déclarant. C'est écrit ici plutôt qu'après la signature.",

  /* ---------------------------------------------------------------- tarifs */
  'pricing.title': 'Des tarifs lisibles, sans surprise',
  'pricing.lede': 'Un seul tarif, par salarié et par mois, pour gérer toute l\'entreprise. Pas de module à la carte, pas de supplément par fonction : tout le produit est dans toutes les formules.',
  'pricing.perMonth': '/ mois',
  'pricing.free': 'Gratuit',
  'pricing.vat': 'Prix hors taxes. Aucun engagement de durée sur les formules mensuelles.',
  'pricing.cta': 'Commencer',
  'pricing.ctaCustom': 'Nous écrire',
  'pricing.popular': 'Le plus choisi',
  'pricing.p1.name': 'Gratuit',
  'pricing.p1.for': 'Moins de 5 salariés',
  'pricing.p1.body': 'Tout le produit, gratuitement, sans limite de durée et sans fonction bridée. La formule pour une jeune entreprise, une association ou un cabinet qui démarre.',
  'pricing.p2.name': 'Abonnement',
  'pricing.p2.for': 'À partir de 5 salariés',
  'pricing.p2.body': '5 € par salarié et par mois, puis 4 € de deux cent cinquante à cinq cents, et 3 € au-delà. Vous payez l\'effectif que vous avez, pas celui que vous aurez peut-être un jour.',
  'pricing.p4.name': 'Licence à vie',
  'pricing.p4.for': 'Paiement unique',
  'pricing.p4.body': '10 000 € une fois. Aucun abonnement, aucune limite de durée, aucun plafond d\'effectif. Le logiciel vous appartient tant que vous voulez l\'utiliser.',
  'pricing.tableTitle': 'Ce que comprend chaque formule',
  'pricing.col.feature': '',
  'pricing.yes': 'Compris',
  'pricing.no': 'Non',
  'pricing.option': 'En option',
  'pricing.f.allSpaces': 'Les 35 espaces et les 7 modules',
  'pricing.f.languages': 'Les 16 langues et les 3 palettes',
  'pricing.f.security': 'Sécurité complète, journal scellé, RGPD',
  'pricing.f.updates': 'Mises à jour incluses',
  'pricing.f.saas': 'Hébergement SaaS en Europe',
  'pricing.f.local': 'Hébergement local de vos données',
  'pricing.f.backupOff': 'Externalisation des sauvegardes',
  'pricing.f.support': 'Assistance',
  'pricing.f.supportMail': 'Par courriel',
  'pricing.f.supportPrio': 'Prioritaire',
  'pricing.f.supportDedicated': 'Interlocuteur dédié',
  'pricing.f.supportCommunity': 'Documentation',
  'pricing.f.migration': 'Reprise de vos données',
  'pricing.f.sla': 'Engagement de service (SLA)',
  'pricing.f.api': 'API de lecture et webhooks',
  'pricing.f.multisite': 'Plusieurs sites, plusieurs entités',
  'pricing.countTitle': 'Comment on compte les salariés',
  'pricing.countBody': 'Le nombre de comptes actifs, freelances et stagiaires compris, administrateurs exclus. Un compte fermé ne compte plus, même s\'il garde l\'accès à son coffre-fort. Vous franchissez un palier ? Le changement se fait au mois suivant, sans rétroactivité — et vous redescendez de la même façon.',

  /* ------------------------------------------------------------------- FAQ */
  'faq.title': 'Questions fréquentes',
  'faq.q1': 'La formule gratuite est-elle limitée dans le temps ?',
  'faq.a1': 'Non. Sous cinq salariés, le produit est gratuit sans limite de durée et sans fonction bridée. Nous préférons une petite structure qui grandit avec le logiciel à une version d\'essai qui s\'éteint au bout de trente jours.',
  'faq.q2': 'Puis-je héberger mes données sur mon propre serveur ?',
  'faq.a2': "Oui, sur les formules payantes. Le logiciel tourne sur une seule machine avec Node 22 et SQLite : ni serveur de base de données, ni service externe. Vous gardez la base, les documents et les sauvegardes chez vous.",
  'faq.q3': 'Que se passe-t-il si j’arrête ?',
  'faq.a3': "Vous exportez l'intégralité de l'instance en JSON, documents compris, depuis la console d'administration. Rien n'est retenu en otage : c'est votre base, et elle part avec vous dans un format lisible.",
  'faq.q4': 'Le logiciel remplace-t-il mon expert-comptable ?',
  'faq.a4': "Non. La comptabilité en partie double, la paie et la TVA sont là pour tenir vos écritures et préparer les pièces. Il n'y a ni liasse fiscale, ni DSN, ni télétransmission : l'export alimente votre cabinet.",
  'faq.q5': 'Faut-il former les équipes ?',
  'faq.a5': 'L\'espace du salarié se comprend seul : demandes de congés, documents, planning, annuaire. Les espaces d\'administration demandent une prise en main d\'une demi-journée, que nous accompagnons sur les formules payantes.',
  'faq.q6': 'Est-ce que je peux n’activer qu’une partie du produit ?',
  'faq.a6': "Oui. Sept modules — comptabilité, paie, facturation électronique, stock et achats, trésorerie, immobilisations, CRM — sont éteints par défaut et s'activent un à un. Tant qu'un module est éteint, ses adresses répondent 404.",
  'faq.q7': 'Comment se passe la reprise de mes données actuelles ?',
  'faq.a7': 'Un import de masse en CSV contrôle chaque ligne avant d\'écrire, et n\'écrit rien si une seule ligne est invalide. Sur les formules payantes, nous préparons les fichiers avec vous.',
  'faq.q8': 'Et les intégrations avec nos outils ?',
  'faq.a8': 'Une API REST de lecture à portées et des webhooks sortants signés sont inclus dans toutes les formules. Pour des échanges spécifiques — SIRH, ERP, facturation —, écrivez-nous : ce travail se chiffre au cas par cas.',

  /* --------------------------------------------------------------- contact */
  'contact.title': 'Parlons de votre entreprise',
  'contact.lede': "Une démonstration dure trente minutes, sur vos cas à vous plutôt que sur un jeu de données inventé. Écrivez-nous ce que vous cherchez à régler.",
  'contact.emailLabel': 'Par courriel',
  'contact.demoTitle': 'Demander une démonstration',
  'contact.demoBody': "Indiquez votre nom, votre entreprise, votre effectif et ce qui vous pose problème aujourd'hui. Nous répondons sous un jour ouvré.",
  'contact.write': 'Écrire à l’équipe',
  'contact.docTitle': 'Lire la documentation',
  'contact.docBody': "Le site de documentation détaille l'installation, la configuration, la sécurité, l'API et le lexique complet des seize langues.",
  'contact.docCta': 'Ouvrir la documentation',
  'contact.selfTitle': 'Installer vous-même',
  'contact.selfBody': "Node 22, une machine, cinq minutes : l'assistant d'installation crée la base, le compte administrateur et vérifie l'environnement.",
  'contact.selfCta': 'Voir les prérequis',

  /* -------------------------------------------------------------- bandeaux */
  'cta.title': 'Commencez gratuitement, changez de formule quand vous grandirez',
  'cta.body': 'Sous cinq salariés, tout est gratuit. Au-delà, 5 € par salarié et par mois — dégressif à partir de deux cent cinquante — ou 10 000 € une fois pour la licence à vie. Aucune carte bancaire pour essayer.',
  'cta.primary': 'Créer mon instance',
  'cta.secondary': 'Parler à quelqu’un',

  /* ------------------------------------------------------------------ pied */
  'foot.product': 'Produit',
  'foot.company': 'À propos',
  'foot.resources': 'Ressources',
  'foot.legal': 'Mentions',
  'foot.docs': 'Documentation',
  'foot.status': 'Ce qui est couvert',
  'foot.rights': 'Tous droits réservés.',
  'foot.madeWith': 'Node 22 · Express · SQLite. Aucune dépendance inutile.',
  'foot.langTitle': 'Ce site existe en seize langues',

  /* ---------------------------------------------------- liste des domaines */
  'dom.socle.title': 'Socle et organisation',
  'dom.socle.lede': "Ce qui tient le reste : les comptes, les rattachements, et le vocabulaire commun à tous les espaces.",
  'dom.socle.items': [
    'Comptes, rôles cumulables : administrateur, RH, gestion, informatique, référent d’alerte',
    'Manager déduit de l’encadrement réel, jamais accordé à la main',
    'Services et équipes, plusieurs managers par périmètre, rattachements relus à chaque requête',
    'Organigramme visuel, encadrement compris, et les personnes rattachées nulle part',
    'Annuaire avec recherche et filtres, visibilité pilotée par la seule administration',
    'Messagerie interne, et adresse professionnelle configurée par l’administration',
    'Recherche globale cloisonnée à la source : ce que vous ne pouvez pas voir n’est pas cherché',
    'Centre de notifications par personne, avec accusé de lecture',
    'Import de masse en CSV : aperçu contrôlé, écriture tout ou rien',
    'Assistant d’installation, réglages d’instance, sept modules débloquables',
    '16 langues, 3 palettes, thème clair/sombre/système, interface responsive',
  ],

  'dom.espace.title': 'Espace du salarié',
  'dom.espace.lede': "La page que tout le monde ouvre le matin : ce qui le concerne, et rien d’autre.",
  'dom.espace.items': [
    'Tableau de bord personnel : manager, actualités, demandes, documents à accuser',
    'Demandes de congés, RTT, absence, télétravail : jours ouvrés calculés, week-ends exclus',
    'Solde de congés à jour, historique des ajustements motivés',
    'Fiches de paie consultables, et conservées cinquante ans au coffre-fort',
    'Agenda personnel et agenda partagé d’équipe',
    'Planning de la semaine, astreintes, permanences',
    'Outils attribués avec identifiant propre — aucun mot de passe tiers stocké',
    'Profil : photo, présentation, téléphone, langue, mot de passe, fermeture des sessions',
    'Pointage au chronomètre pour les freelances, un seul en cours à la fois',
    'Déclaration d’intérêts et de cadeaux, visible de soi seul',
  ],

  'dom.rh.title': 'Ressources humaines',
  'dom.rh.lede': "Le dossier du salarié, de son arrivée à son départ, avec les échéances qui vont avec.",
  'dom.rh.items': [
    'Approbation des demandes avec décompte du solde, refus motivé, annulation qui recrédite',
    'Fiches de paie : création, suivi du versement, génération en lot',
    'Documents d’entreprise avec accusé de réception nominatif',
    'Formation : catalogue, sessions, inscriptions, coût et durée',
    'Entretiens annuels : campagne, trame, compte rendu',
    'Arrivée et départ : listes de contrôle suivies, porteur et échéance par tâche',
    'Compétences et habilitations, avec date de recyclage et alerte à l’avance',
    'Points individuels manager–collaborateur : résumé partagé, notes du manager séparées',
    'Coffre-fort numérique accessible après le départ, documents scellés par leur empreinte',
    'Signature électronique simple : circuit ordonné, empreinte, sceau, attestation',
    'Contrats de travail à échéance : le compte se ferme tout seul le jour dit',
  ],

  'dom.talent.title': 'Recrutement et talents',
  'dom.talent.lede': "Des candidatures au premier jour, sans tableur intermédiaire.",
  'dom.talent.items': [
    'Offres d’emploi et suivi des candidatures par étape',
    'Réception des CV : PDF, DOCX ou texte, écrits hors du dépôt',
    'Extraction du contenu et CVthèque cherchable',
    'Critères pondérés, score, seuil, classement des candidatures',
    'Passage d’un candidat retenu au parcours d’arrivée',
    'Sondages internes et baromètre social, anonymes par construction',
    'Sous cinq réponses, aucun résultat n’est affiché',
  ],

  'dom.sst.title': 'Santé, sécurité et CSE',
  'dom.sst.lede': "Les obligations qui se tiennent par écrit, et se rappellent toutes seules.",
  'dom.sst.items': [
    'Document unique : unités de travail, dangers, cotation, mesures, revue datée',
    'Registre des accidents du travail et des presque-accidents, jours d’arrêt',
    'Équipements de protection : dotation nominative, durée de validité, renouvellement',
    'Visites médicales : embauche, périodique, reprise, à la demande',
    'CSE : élections, corps électoral, scrutin anonyme, mandats et leur échéance',
    'Réunions du comité, avantages et prestations aux salariés',
    'Espace de gestion qui se referme de lui-même à la fin du mandat',
  ],

  'dom.finance.title': 'Finance et gestion',
  'dom.finance.lede': "Les tiers, les contrats, l’argent qui entre et celui qui sort.",
  'dom.finance.items': [
    'Tiers clients et fournisseurs, fiche complète : contacts, contrats, factures',
    'Contrats et surtout préavis : la date limite de dénonciation est calculée et alertée',
    'Factures dans les deux sens, TTC calculé, retard déduit de l’échéance',
    'Budgets par service et par exercice, consommé agrégé automatiquement',
    'Notes de frais : dépôt, approbation, remboursement — jamais l’un sans l’autre',
    'Pièces de conformité des tiers, datées et signalées quarante-cinq jours avant terme',
    'Évaluations fournisseurs notées, la dernière faisant foi plutôt que la moyenne',
    'Multidevise avec taux figé à l’émission de chaque pièce',
    'Facturation récurrente : l’abonnement est le moule, la facture est la pièce',
    'Lecture automatique des factures reçues et capture IMAP d’une boîte comptable',
  ],

  'dom.compta.title': 'Comptabilité, paie et TVA',
  'dom.compta.lede': "Des modules, éteints par défaut, qui s’activent quand vous en avez besoin.",
  'dom.compta.items': [
    'Comptabilité en partie double : plan comptable, journaux, balance, grand livre',
    'Une écriture déséquilibrée est refusée, et le message dit de combien',
    'Une facture se passe en écriture d’un clic ; export CSV pour le cabinet',
    'Moteur de paie : barèmes paramétrables, brut au net, part patronale, coût employeur',
    'Bulletin détaillé ligne à ligne, génération en lot, simulateur',
    'Déclarations de TVA : collectée, déductible, ventilation par taux, crédit reportable',
    'Une déclaration déposée ne se recalcule plus : c’est une pièce, pas un tableau de bord',
    'Facturation électronique : contrôle EN 16931 et export du XML CII',
    'Trésorerie : comptes, mouvements, rapprochement, prévisionnel à douze semaines',
    'Immobilisations : amortissement linéaire et dégressif, valeur nette comptable',
  ],

  'dom.achats.title': 'Achats, stock et recouvrement',
  'dom.achats.lede': "Ce qu’on commande, ce qu’on reçoit, ce qu’on facture — et ce qu’on nous doit.",
  'dom.achats.items': [
    'Demandes d’achat validées par le manager, puis par la gestion au-delà du seuil',
    'Bons de commande, réceptions, et rapprochement à trois : commandé, reçu, facturé',
    'Recevoir plus que commandé est refusé ; l’écart de facturation est nommé, pas bloqué',
    'Articles, mouvements, seuil d’alerte : le stock est la somme des mouvements',
    'Une ligne rattachée à un article entre en stock au moment de sa réception',
    'Balance âgée client par tranche de retard',
    'Relances échelonnées : rappel, relance, mise en demeure, selon ce qui a déjà été envoyé',
    'Chaque relance consignée avec son niveau et sa date',
  ],

  'dom.projets.title': 'Projets, temps et rentabilité',
  'dom.projets.lede': "Savoir où en est un projet, et ce qu’il a réellement coûté.",
  'dom.projets.items': [
    'Projets rattachés à un client, un service, une équipe et un responsable',
    'Jalons datés et tâches en colonnes par statut, avec priorité et estimation',
    'Temps passé imputé au projet et à la tâche, au plus 24 h par saisie',
    'Rentabilité : heures, coût au taux horaire, marge restante, part du budget consommée',
    'Trois cercles de droits : la gestion, le responsable, les membres',
    'Temps par personne, et santé des projets sur le tableau de bord de direction',
  ],

  'dom.support.title': 'Support et connaissances',
  'dom.support.lede': "Les demandes internes et clientes dans un même circuit, et les réponses qui restent.",
  'dom.support.items': [
    'Tickets internes et clients, priorité, origine, assignation',
    'Délai de première réponse déduit de la priorité, recalculé depuis l’ouverture',
    'Notes internes invisibles du demandeur, et qui ne comptent pas comme réponse',
    'Cloisonnement par catégorie : une demande RH ne sort pas des RH',
    'Base de connaissances par catégorie, recherche plein texte, portée réglable',
    'Indicateurs : tickets ouverts, en retard, délai moyen',
  ],

  'dom.ops.title': 'Opérations et moyens généraux',
  'dom.ops.lede': "Le planning, la qualité, les salles, les véhicules, l’accueil.",
  'dom.ops.items': [
    'Planning par personne et par jour : postes, astreintes, permanences, télétravail',
    'Chevauchement ou absence déjà accordée : le créneau est refusé à la création',
    'Roulements réutilisables, postes de nuit, publication de la semaine',
    'Qui est d’astreinte à cet instant, avec son numéro',
    'Qualité : non-conformités, causes racines, actions correctives et vérification d’efficacité',
    'Audits internes : constats, synthèse, promotion d’un constat en non-conformité',
    'Équipements affectés et repris, avec historique des détenteurs',
    'Salles et réservations, chevauchement refusé en nommant qui occupe',
    'Flotte : entretien, contrôle technique, assurance, sinistres, kilométrage',
    'Accueil : registre des visiteurs, liste « dans les murs », courrier entrant et sortant',
  ],

  'dom.direction.title': 'Direction et gouvernance',
  'dom.direction.lede': "Ce que la direction regarde, et ce qu’elle décide.",
  'dom.direction.items': [
    'Tableau de bord : effectif, absents, facturé, marge, masse salariale, trésorerie, support',
    'Objectifs et résultats clés, chacun sur sa propre échelle, y compris décroissante',
    'Réunions : convocation, ordre du jour, présences pointées, compte rendu',
    'Registre des décisions avec leur motif — ce qu’on cherche deux ans plus tard',
    'Actions confiées avec porteur et échéance, rattachées à leur décision',
    'Registre des risques : cotation brute et résiduelle, matrice 5 × 5, traitement, revue',
    'Événements d’entreprise : capacité, liste d’attente automatique, émargement, budget',
    'Échéances consolidées de tous les espaces dans une seule liste triée',
  ],

  'dom.it.title': 'Informatique et développement',
  'dom.it.lede': "Le parc logiciel, les accès, les incidents, et ce que l’équipe livre.",
  'dom.it.items': [
    'Parc logiciel : sièges tenus comme une contrainte, coût annualisé, renouvellements',
    'Revue des accès applicatifs : comptes fermés d’abord, puis droits d’administration',
    'Incidents du SI, horodatés, avec délai moyen de rétablissement mesuré',
    'Référentiel des services applicatifs : criticité, responsable, dépôt, documentation',
    'Registre des livraisons par environnement et indicateurs de livraison',
    'Sauvegardes : archive horaire, intégrité vérifiée, restauration, externalisation',
    'API REST de lecture à portées, webhooks sortants signés',
    'Export intégral de l’instance en JSON, documents compris, secrets exclus',
  ],

  'dom.conformite.title': 'Conformité, juridique et données personnelles',
  'dom.conformite.lede': "Ce qu’une entreprise doit pouvoir prouver, tenu au fil de l’eau.",
  'dom.conformite.items': [
    'Registre du capital : détention déduite des mouvements, cession en deux jambes',
    'Mandats sociaux avec durée, révocation, et fin signalée à l’avance',
    'Assemblées générales : quorum en titres, résolutions, votes, procès-verbal',
    'Délégations de pouvoir : objet, plafond, durée, échéance alertée',
    'Conflits d’intérêts et cadeaux : chacun déclare pour soi, l’administration examine',
    'Canal d’alerte interne chiffré, référents désignés, suivi anonyme par code',
    'Journal d’audit horodaté, exportable, et scellé par chaînage d’empreintes',
    'RGPD : registre des traitements, droit d’accès exporté, effacement raisonné',
    'Circuits d’approbation configurables : formulaires, seuils, validateurs par fonction',
  ],

  /* -------------------------------------------------- titres des captures */
  'shot.membre-espace': 'Espace du salarié',
  'shot.membre-equipe': 'Espace manager',
  'shot.membre-demandes': 'Demandes internes',
  'shot.membre-agenda': 'Agenda personnel et partagé',
  'shot.membre-salles': 'Salles et réservations',
  'shot.membre-messagerie': 'Messagerie interne',
  'shot.membre-connaissances': 'Base de connaissances',
  'shot.membre-coffre-fort': 'Coffre-fort numérique',
  'shot.membre-profil': 'Profil et sécurité du compte',
  'shot.membre-juridique-membre': 'Mes déclarations',
  'shot.annuaire': 'Annuaire de l’entreprise',
  'shot.organigramme': 'Organigramme',
  'shot.connexion': 'Écran de connexion',
  'shot.pilotage': 'Tableau de bord de direction',
  'shot.admin': 'Console d’administration',
  'shot.rh': 'Ressources humaines',
  'shot.gestion': 'Gestion administrative et financière',
  'shot.direction': 'Direction et gouvernance',
  'shot.projets': 'Projets, jalons et rentabilité',
  'shot.support': 'Support et tickets',
  'shot.planning': 'Planning, roulements et astreintes',
  'shot.qualite': 'Qualité et audits internes',
  'shot.sante-securite': 'Santé et sécurité au travail',
  'shot.informatique': 'Parc logiciel et accès',
  'shot.developpement': 'Services applicatifs et livraisons',
  'shot.evenements': 'Événements d’entreprise',
  'shot.juridique': 'Vie juridique et conformité',
  'shot.alertes': 'Dispositif d’alerte interne',
  'shot.securite': 'Console de sécurité',
  'shot.rgpd': 'Données personnelles',
  'shot.parapheur': 'Parapheur et signatures',
  'shot.sauvegardes': 'Sauvegardes et restauration',
  'shot.comptabilite': 'Comptabilité en partie double',
  'shot.paie': 'Moteur de paie',
  'shot.tresorerie': 'Trésorerie et prévisionnel',
  'shot.immobilisations': 'Immobilisations et amortissements',
  'shot.crm': 'CRM commercial',
  'shot.stock': 'Stock et achats',
  'shot.pilotage-sombre': 'Pilotage — thème sombre',
  'shot.membre-espace-sombre': 'Espace du salarié — thème sombre',
  'shot.gestion-sombre': 'Gestion — thème sombre',
  'shot.projets-sombre': 'Projets — thème sombre',
  'shot.juridique-sombre': 'Vie juridique — thème sombre',
  'shot.securite-sombre': 'Sécurité — thème sombre',

  /* ------------------------------------------- légendes des six onglets */
  'tour.pilotage': "Effectif, facturé, marge, trésorerie, support : ce que la direction regarde, sur une page. Un tiret marque une donnée absente — jamais un zéro qui ferait croire à un chiffre.",
  'tour.membre-espace': "La page que chacun ouvre le matin : son manager, les actualités qui le concernent, ses demandes, ses documents à accuser, ses outils et leurs identifiants.",
  'tour.rh': "Demandes à traiter, soldes, fiches de paie, documents, formation, entretiens : le dossier du salarié se tient ici, et les échéances remontent toutes seules.",
  'tour.gestion': "Tiers, contrats et préavis, factures dans les deux sens, budgets par service, notes de frais, recouvrement. Le consommé d'un budget s'agrège de lui-même.",
  'tour.projets': "Jalons, tâches en colonnes, temps passé et rentabilité face au budget. Le coût n'est pas saisi : il se déduit des heures et du taux horaire.",
  'tour.juridique': "Capital, mandats sociaux, assemblées et procès-verbaux, délégations, déclarations d'intérêts. Ce qu'une entreprise doit pouvoir prouver, tenu au fil de l'eau.",
  'pricing.perEmployee': '5 € par salarié et par mois',
  'pricing.perEmployeeShort': 'par salarié / mois',
  'pricing.argTitle': 'Cinq euros par salarié, pour tout',
  'pricing.argBody': 'Un outil RH, un logiciel de compta, un gestionnaire de projets, une billetterie de support, un coffre-fort de bulletins : cinq abonnements à 8 ou 15 € par utilisateur, cinq bases qui ne se parlent pas, cinq factures. Toutadmin remplace la pile entière pour le prix du moins cher — et les données, elles, sont enfin au même endroit.',
  'pricing.gridTitle': 'La grille, par effectif',
  'pricing.gridLede': 'Le prix suit l\'effectif et rien d\'autre : 5 € par salarié jusqu\'à deux cent quarante-neuf, 4 € de deux cent cinquante à cinq cents, 3 € au-delà. Franchir une tranche fait baisser la facture de tout le monde, pas seulement des nouveaux venus.',
  'pricing.col.headcount': 'Effectif',
  'pricing.col.monthly': 'Par mois',
  'pricing.col.perEmployee': 'Par salarié',
  'pricing.upTo': 'Jusqu\'à {count} salariés',
  'pricing.under': 'Moins de {count} salariés',
  'pricing.once': 'une fois',
  'pricing.lifetimeTitle': 'Pourquoi une licence à vie',
  'pricing.lifetimeBody': 'Dix mille euros une fois, sans abonnement et sans limite de durée : la même instance, les mêmes mises à jour, aucun effectif maximum. À cent salariés elle est amortie en vingt mois, à cinq cents en cinq. C\'est l\'offre pour qui préfère un investissement à une ligne de charge récurrente — et pour qui ne veut dépendre de personne pour continuer à travailler.',
  'faq.q9': 'Que se passe-t-il si mon effectif change en cours d\'année ?',
  'faq.a9': 'Le tarif suit, dans les deux sens, au mois suivant et sans rétroactivité. Une embauche qui vous fait passer un palier se facture le mois d\'après ; un départ qui vous en fait redescendre aussi. Personne ne paie pour des comptes fermés.',
  'faq.q10': 'La licence à vie donne-t-elle droit aux mises à jour ?',
  'faq.a10': 'Oui, sans limite de durée : c\'est le sens du mot « à vie ». Vous recevez les mêmes versions que les formules mensuelles, et vous pouvez héberger la base chez vous. Ce que la licence ne comprend pas, c\'est l\'assistance prioritaire, qui reste un service distinct.',
  'pricing.someEmployees': '{count} salariés',
  'nav.docs': 'Documentation',
  'menu.title': 'Tout le site',
  'menu.close': 'Fermer le plan du site',
  'menu.domains': 'Les quatorze domaines',
  'menu.home.d': 'Ce que le produit couvre, en chiffres, et un aperçu des écrans.',
  'menu.features.d': 'La liste complète, domaine par domaine : plus de cent trente fonctions livrées et testées.',
  'menu.screens.d': 'Quarante captures d\'une instance réelle, en thème clair et sombre.',
  'menu.security.d': 'Authentification, journal scellé, données personnelles, alerte interne, sauvegardes — et les limites assumées.',
  'menu.pricing.d': 'Le tarif par salarié, la grille par effectif et la licence à vie.',
  'menu.contact.d': 'Demander une démonstration sur vos cas, ou nous écrire.',
  'menu.docs.d': 'Installation, configuration, sécurité, API et lexique complet. Site séparé.',
  'menu.home': 'Accueil',
  'menu.group.product': 'Le produit',
  'menu.group.decide': 'Pour décider',
  'menu.group.more': 'Aller plus loin',
};
