/* it — traduit du français. Toute clé du français doit exister ici :
   le build refuse de construire une langue incomplète. */
module.exports = {
  'locale.name': 'Italiano',
  'site.name': 'Toutadmin',
  'site.tagline': 'Il CMS che amministra tutta l\'azienda',
  'nav.product': 'Prodotto',
  'nav.features': 'Funzioni',
  'nav.screens': 'Le schermate',
  'nav.security': 'Sicurezza',
  'nav.pricing': 'Prezzi',
  'nav.contact': 'Contatti',
  'nav.demo': 'Chiedi una demo',
  'nav.menu': 'Menu',
  'nav.language': 'Lingua',
  'nav.theme': 'Tema',
  'nav.themeLight': 'Chiaro',
  'nav.themeDark': 'Scuro',
  'nav.themeSystem': 'Sistema',
  'hero.eyebrow': 'Software gestionale d\'impresa',
  'hero.title': 'Tutta la tua azienda,\nin un solo software.',
  'hero.lede': 'Personale, risorse umane, finanza, operazioni, governance, conformità, servizi generali. Trentacinque spazi che si parlano, una sola base dati, nessuna applicazione da incollare. In sedici lingue, e 5 € per dipendente al mese per gestire tutto.',
  'hero.ctaPrimary': 'Prova gratis',
  'hero.ctaSecondary': 'Vedi le funzioni',
  'hero.note': 'Senza carta di credito. I tuoi dati restano tuoi, e possono restare da te.',
  'hero.badge1': 'SaaS pronto in cinque minuti',
  'hero.badge2': 'o ospitato da te',
  'hero.badge3': 'GDPR per costruzione',
  'stats.title': 'Cosa copre il prodotto, in cifre',
  'stats.spaces': 'spazi di lavoro',
  'stats.spacesNote': 'dallo spazio del dipendente alla vita societaria',
  'stats.languages': 'lingue d\'interfaccia',
  'stats.languagesNote': 'arabo compreso, pagina specchiata',
  'stats.tests': 'test d\'integrazione',
  'stats.testsNote': 'eseguiti a ogni rilascio',
  'stats.modules': 'moduli attivabili',
  'stats.modulesNote': 'contabilità, paghe, tesoreria, CRM…',
  'stats.deps': 'servizi esterni necessari',
  'stats.depsNote': 'una macchina, una base dati, nient\'altro',
  'stats.keys': 'etichette tradotte',
  'stats.keysNote': 'fino ai riquadri di conferma',
  'pillars.title': 'Perché Toutadmin invece di cinque strumenti incollati',
  'pillars.lede': 'Cinque programmi che non si parlano costano più di uno solo e fanno perdere ciò che conta: la visione d\'insieme. Toutadmin parte dall\'opposto: una base dati, degli spazi, dei diritti.',
  'pillars.1.title': 'Un solo posto, una sola verità',
  'pillars.1.body': 'Il budget di un reparto somma da sé le proprie fatture e le note spese approvate dei suoi membri. Una merce ricevuta entra a magazzino nello stesso gesto. Nessuno ridigita nulla, quindi nessuno si contraddice.',
  'pillars.2.title': 'I diritti non sono decorativi',
  'pillars.2.body': 'Ogni rotta porta il proprio controllo lato server, e le appartenenze sono rilette a ogni richiesta. Un\'uscita taglia l\'accesso subito, non alla scadenza del cookie. Ciò che non puoi vedere non viene nemmeno cercato.',
  'pillars.3.title': 'Le scadenze vengono da te',
  'pillars.3.body': 'Preavvisi contrattuali, abilitazioni da rinnovare, visite mediche, revisioni dei veicoli, cariche sociali, attestazioni dei fornitori: un solo motore le raccoglie e avvisa la persona giusta, una volta, senza doppioni.',
  'pillars.4.title': 'Ogni schermata dice ciò che non fa',
  'pillars.4.body': 'Un modulo mostra il suo limite quando lo attivi, non in fondo a un manuale. Preferiamo una frase onesta a una casella spuntata: è ciò che evita le brutte sorprese al terzo mese.',
  'pillars.5.title': 'Sedici lingue, davvero',
  'pillars.5.body': 'Non solo la schermata iniziale: gli stati, i messaggi d\'errore, i riquadri di conferma. L\'arabo specchia l\'intera pagina, perché il foglio di stile usa solo proprietà logiche.',
  'pillars.6.title': 'I tuoi dati, da te se vuoi',
  'pillars.6.body': 'In SaaS tutto è pronto in cinque minuti. Sui piani a pagamento puoi anche ospitare la base dati sul tuo server: stesso software, stessi aggiornamenti, dati dentro le tue mura.',
  'tour.title': 'Software denso, non un giocattolo',
  'tour.lede': 'Schermate pensate per chi le tiene aperte otto ore al giorno: informazione a colpo d\'occhio, nessuna finestra modale inutile, e lo stesso vocabolario ovunque.',
  'tour.hint': 'Clicca una scheda per cambiare schermata.',
  'tour.all': 'Vedi le 40 schermate',
  'features.title': 'Tutto ciò che Toutadmin sa fare',
  'features.lede': 'L\'elenco completo, ambito per ambito. Ogni riga corrisponde a codice rilasciato e testato, non a un\'intenzione.',
  'features.legend': 'Le funzioni indicate come «modulo» si attivano dalla console quando servono.',
  'features.module': 'modulo',
  'features.seeAll': 'Vedi l\'elenco completo',
  'features.intro': 'Quattordici ambiti, oltre centotrenta funzioni.',
  'features.ctaTitle': 'Manca qualcosa?',
  'features.ctaBody': 'Diccelo. Il prodotto avanza per lotti, e le richieste delle aziende che lo usano passano per prime.',
  'screens.title': 'Le schermate, senza ritocchi',
  'screens.lede': 'Tutte le immagini di questo sito escono da un\'istanza reale popolata con dati dimostrativi. Nessun mockup, nessun montaggio.',
  'screens.light': 'Tema chiaro',
  'screens.dark': 'Tema scuro',
  'screens.member': 'Spazio del dipendente',
  'screens.admin': 'Amministrazione e direzione',
  'screens.modules': 'Moduli opzionali',
  'screens.open': 'Ingrandisci',
  'screens.close': 'Chiudi',
  'screens.prev': 'Precedente',
  'screens.next': 'Successiva',
  'security.title': 'La sicurezza non è un\'opzione a pagamento',
  'security.lede': 'Tutto ciò che segue è nel prodotto, qualunque sia il piano, compreso quello gratuito.',
  'security.1.title': 'Autenticazione irrobustita',
  'security.1.body': 'Password con hash (bcrypt), politica di complessità, blocco dopo tentativi ripetuti, doppio fattore TOTP con codici di recupero, sessioni revocabili una per una o tutte insieme.',
  'security.2.title': 'Registro di audit sigillato',
  'security.2.body': 'Ogni voce porta l\'impronta della precedente. Modificare una riga, o toglierne una in mezzo, spezza la catena in quel punto, e la verifica dice quale. Ciò che non fa: impedire la riscrittura a chi controlla il server — la rende visibile.',
  'security.3.title': 'Dati personali',
  'security.3.body': 'Registro dei trattamenti, diritto d\'accesso esportato fonte per fonte, cancellazione che conserva ciò che la legge impone di conservare e lo dice. L\'account viene anonimizzato invece che eliminato, perché le scritture che lo citano restino coerenti.',
  'security.4.title': 'Canale di segnalazione interna',
  'security.4.body': 'Obbligatorio in Francia dai cinquanta dipendenti. Contenuto cifrato nella base dati, leggibile solo dai referenti designati — non dagli amministratori, perché una segnalazione può riguardarne uno. Seguito anonimo tramite codice, senza account e senza registrazione.',
  'security.5.title': 'Backup verificati',
  'security.5.body': 'Archivio orario, controllo d\'integrità tramite manifesto, ripristino che rimette base dati e file, esternalizzazione via FTPS o Google Drive, e avviso agli amministratori in caso di errore.',
  'security.6.title': 'Segreti cifrati',
  'security.6.body': 'Password di servizi terzi, token API, segreti dei webhook: cifrati in AES-256-GCM, mai più mostrati in chiaro, illeggibili dopo un\'alterazione.',
  'security.hostTitle': 'SaaS, o da te',
  'security.hostBody': 'In SaaS ospitiamo in Europa, backup compresi. Sui piani a pagamento l\'ospitalità locale è possibile: installi sul tuo server, la base dati non esce mai dalle tue mura, e ricevi gli stessi aggiornamenti. Basta una macchina — Node 22 e SQLite, nessuna base dati esterna da amministrare.',
  'security.limitsTitle': 'Ciò che non pretendiamo di fare',
  'security.limitsBody': 'La firma elettronica è semplice, non qualificata ai sensi eIDAS. La cassaforte sigilla e data i documenti, ma una marca temporale opponibile a terzi richiede un\'autorità di certificazione. Nessuna trasmissione fiscale o previdenziale: il software produce i dati, il deposito resta al tuo commercialista. È scritto qui e non dopo la firma.',
  'pricing.title': 'Prezzi leggibili, senza sorprese',
  'pricing.lede': 'Un solo prezzo, per dipendente e al mese, per gestire tutta l\'azienda. Nessun modulo a la carte, nessun supplemento per funzione: tutto il prodotto è in tutti i piani.',
  'pricing.perMonth': '/ mese',
  'pricing.free': 'Gratuito',
  'pricing.vat': 'Prezzi IVA esclusa. Nessun vincolo di durata sui piani mensili.',
  'pricing.cta': 'Inizia',
  'pricing.ctaCustom': 'Scrivici',
  'pricing.popular': 'Il più scelto',
  'pricing.p1.name': 'Gratuito',
  'pricing.p1.for': 'Meno di 5 dipendenti',
  'pricing.p1.body': 'Tutto il prodotto, gratuitamente, senza limiti di tempo e senza funzioni ridotte. Il piano per una giovane impresa, un\'associazione o uno studio che inizia.',
  'pricing.p2.name': 'Abbonamento',
  'pricing.p2.for': 'Da 5 dipendenti in su',
  'pricing.p2.body': '5 € per dipendente al mese, poi 4 € da duecentocinquanta a cinquecento e 3 € oltre. Paghi l\'organico che hai, non quello che forse avrai un giorno.',
  'pricing.p4.name': 'Licenza a vita',
  'pricing.p4.for': 'Pagamento unico',
  'pricing.p4.body': '10.000 € una volta sola. Nessun abbonamento, nessun limite di tempo, nessun tetto di organico. Il software è tuo finché vuoi usarlo.',
  'pricing.tableTitle': 'Cosa comprende ogni piano',
  'pricing.col.feature': '',
  'pricing.yes': 'Compreso',
  'pricing.no': 'No',
  'pricing.option': 'Opzionale',
  'pricing.f.allSpaces': 'I 35 spazi e i 7 moduli',
  'pricing.f.languages': 'Le 16 lingue e le 3 palette',
  'pricing.f.security': 'Sicurezza completa, registro sigillato, GDPR',
  'pricing.f.updates': 'Aggiornamenti inclusi',
  'pricing.f.saas': 'Ospitalità SaaS in Europa',
  'pricing.f.local': 'Ospitalità locale dei tuoi dati',
  'pricing.f.backupOff': 'Esternalizzazione dei backup',
  'pricing.f.support': 'Assistenza',
  'pricing.f.supportMail': 'Via e-mail',
  'pricing.f.supportPrio': 'Prioritaria',
  'pricing.f.supportDedicated': 'Interlocutore dedicato',
  'pricing.f.supportCommunity': 'Documentazione',
  'pricing.f.migration': 'Migrazione dei tuoi dati',
  'pricing.f.sla': 'Impegno di servizio (SLA)',
  'pricing.f.api': 'API di lettura e webhook',
  'pricing.f.multisite': 'Più sedi, più entità',
  'pricing.countTitle': 'Come contiamo i dipendenti',
  'pricing.countBody': 'Gli account attivi, freelance e stagisti compresi, amministratori esclusi. Un account chiuso non conta più, anche se conserva l\'accesso alla sua cassaforte. Superi una soglia? Il cambio avviene il mese successivo, senza retroattività — e si scende allo stesso modo.',
  'faq.title': 'Domande frequenti',
  'faq.q1': 'Il piano gratuito è limitato nel tempo?',
  'faq.a1': 'No. Sotto i cinque dipendenti il prodotto è gratuito senza limiti di tempo e senza funzioni ridotte. Preferiamo una piccola struttura che cresce con il software a una versione di prova che si spegne dopo trenta giorni.',
  'faq.q2': 'Posso ospitare i miei dati sul mio server?',
  'faq.a2': 'Sì, sui piani a pagamento. Il software gira su una sola macchina con Node 22 e SQLite: né server di base dati, né servizio esterno. Base dati, documenti e backup restano da te.',
  'faq.q3': 'Cosa succede se smetto?',
  'faq.a3': 'Esporti l\'intera istanza in JSON, documenti compresi, dalla console di amministrazione. Nulla è trattenuto in ostaggio: è la tua base dati, e parte con te in un formato leggibile.',
  'faq.q4': 'Sostituisce il mio commercialista?',
  'faq.a4': 'No. La contabilità in partita doppia, le paghe e l\'IVA servono a tenere le scritture e preparare i documenti. Non c\'è né bilancio depositato né trasmissione telematica: l\'esportazione alimenta il tuo studio.',
  'faq.q5': 'Bisogna formare le squadre?',
  'faq.a5': 'Lo spazio del dipendente si capisce da solo: ferie, documenti, turni, rubrica. Gli spazi di amministrazione richiedono mezza giornata di presa in mano, che accompagniamo sui piani a pagamento.',
  'faq.q6': 'Posso attivare solo una parte del prodotto?',
  'faq.a6': 'Sì. Sette moduli — contabilità, paghe, fatturazione elettronica, magazzino e acquisti, tesoreria, cespiti, CRM — sono spenti per impostazione predefinita e si attivano uno alla volta. Finché un modulo è spento, i suoi indirizzi rispondono 404.',
  'faq.q7': 'Come avviene la migrazione dei miei dati attuali?',
  'faq.a7': 'Un\'importazione di massa in CSV controlla ogni riga prima di scrivere, e non scrive nulla se una sola riga non è valida. Sui piani a pagamento prepariamo i file con te.',
  'faq.q8': 'E le integrazioni con i nostri strumenti?',
  'faq.a8': 'Un\'API REST di lettura con ambiti e webhook uscenti firmati sono inclusi in tutti i piani. Per scambi specifici — HR, ERP, fatturazione — scrivici: quel lavoro si quantifica caso per caso.',
  'contact.title': 'Parliamo della tua azienda',
  'contact.lede': 'Una dimostrazione dura trenta minuti, sui tuoi casi invece che su dati inventati. Scrivici cosa vuoi risolvere.',
  'contact.emailLabel': 'Via e-mail',
  'contact.demoTitle': 'Chiedere una dimostrazione',
  'contact.demoBody': 'Indica il tuo nome, l\'azienda, l\'organico e cosa ti crea problemi oggi. Rispondiamo entro un giorno lavorativo.',
  'contact.write': 'Scrivere al team',
  'contact.docTitle': 'Leggere la documentazione',
  'contact.docBody': 'Il sito di documentazione descrive l\'installazione, la configurazione, la sicurezza, l\'API e il glossario completo nelle sedici lingue.',
  'contact.docCta': 'Aprire la documentazione',
  'contact.selfTitle': 'Installarlo da soli',
  'contact.selfBody': 'Node 22, una macchina, cinque minuti: l\'assistente crea la base dati, l\'account amministratore e verifica l\'ambiente.',
  'contact.selfCta': 'Vedere i prerequisiti',
  'cta.title': 'Inizia gratis, cambia piano quando cresci',
  'cta.body': 'Sotto i cinque dipendenti è tutto gratuito. Oltre, 5 € per dipendente al mese — decrescente da duecentocinquanta — oppure 10.000 € una volta sola per la licenza a vita. Nessuna carta per provare.',
  'cta.primary': 'Creare la mia istanza',
  'cta.secondary': 'Parlare con qualcuno',
  'foot.product': 'Prodotto',
  'foot.company': 'Chi siamo',
  'foot.resources': 'Risorse',
  'foot.legal': 'Note legali',
  'foot.docs': 'Documentazione',
  'foot.status': 'Cosa è coperto',
  'foot.rights': 'Tutti i diritti riservati.',
  'foot.madeWith': 'Node 22 · Express · SQLite. Nessuna dipendenza inutile.',
  'foot.langTitle': 'Questo sito esiste in sedici lingue',
  'dom.socle.title': 'Fondamenta e organizzazione',
  'dom.socle.lede': 'Ciò che regge il resto: gli account, le appartenenze e il vocabolario comune a tutti gli spazi.',
  'dom.socle.items': [
    'Account e ruoli cumulabili: amministratore, HR, gestione, informatica, referente segnalazioni',
    'Responsabile dedotto dall\'inquadramento reale, mai concesso a mano',
    'Reparti e squadre, più responsabili per perimetro, appartenenze rilette a ogni richiesta',
    'Organigramma visivo, dirigenza compresa, e le persone senza alcuna appartenenza',
    'Rubrica con ricerca e filtri, visibilità gestita dalla sola amministrazione',
    'Messaggistica interna, e indirizzo professionale configurato dall\'amministrazione',
    'Ricerca globale isolata alla fonte: ciò che non puoi vedere non viene cercato',
    'Centro notifiche per persona, con conferma di lettura',
    'Importazione di massa in CSV: anteprima controllata, scrittura tutto o niente',
    'Assistente d\'installazione, impostazioni dell\'istanza, sette moduli attivabili',
    '16 lingue, 3 palette, tema chiaro/scuro/sistema, interfaccia adattiva',
  ],
  'dom.espace.title': 'Spazio del dipendente',
  'dom.espace.lede': 'La pagina che tutti aprono la mattina: ciò che li riguarda, e nient\'altro.',
  'dom.espace.items': [
    'Cruscotto personale: responsabile, novità, richieste, documenti da confermare',
    'Ferie, permessi, assenze, lavoro da remoto: giorni lavorativi calcolati, fine settimana esclusi',
    'Saldo ferie aggiornato, storico delle rettifiche motivate',
    'Buste paga consultabili e conservate cinquant\'anni nella cassaforte',
    'Agenda personale e agenda condivisa di squadra',
    'Turni della settimana, reperibilità, presidi',
    'Strumenti assegnati con credenziali proprie — nessuna password di terzi conservata',
    'Profilo: foto, presentazione, telefono, lingua, password, chiusura delle sessioni',
    'Rilevazione a cronometro per i freelance, una sola in corso alla volta',
    'Dichiarazione di interessi e regali, visibile solo a sé stessi',
  ],
  'dom.rh.title': 'Risorse umane',
  'dom.rh.lede': 'Il fascicolo del dipendente, dall\'arrivo alla partenza, con le scadenze che comporta.',
  'dom.rh.items': [
    'Approvazione delle richieste con scalo dal saldo, rifiuto motivato, annullamento che riaccredita',
    'Buste paga: creazione, monitoraggio del pagamento, generazione in blocco',
    'Documenti aziendali con conferma di ricezione nominativa',
    'Formazione: catalogo, sessioni, iscrizioni, costo e durata',
    'Colloqui annuali: campagna, traccia, verbale',
    'Ingresso e uscita: liste di controllo seguite, responsabile e scadenza per attività',
    'Competenze e abilitazioni, con data di rinnovo e avviso anticipato',
    'Colloqui individuali: sintesi condivisa, note del responsabile tenute a parte',
    'Cassaforte digitale accessibile anche dopo l\'uscita, documenti sigillati dalla loro impronta',
    'Firma elettronica semplice: circuito ordinato, impronta, sigillo, attestato',
    'Contratti a termine: l\'account si chiude da sé nel giorno previsto',
  ],
  'dom.talent.title': 'Selezione e talenti',
  'dom.talent.lede': 'Dalle candidature al primo giorno, senza foglio di calcolo in mezzo.',
  'dom.talent.items': [
    'Offerte di lavoro e candidature seguite per fase',
    'Ricezione dei CV: PDF, DOCX o testo, scritti fuori dal repository',
    'Estrazione del contenuto e banca CV consultabile',
    'Criteri ponderati, punteggio, soglia, classifica delle candidature',
    'Un candidato scelto passa direttamente al percorso d\'ingresso',
    'Sondaggi interni e barometro sociale, anonimi per costruzione',
    'Sotto cinque risposte non viene mostrato alcun risultato',
  ],
  'dom.sst.title': 'Salute, sicurezza e rappresentanza',
  'dom.sst.lede': 'Gli obblighi che vanno tenuti per iscritto, e che si ricordano da soli.',
  'dom.sst.items': [
    'Valutazione dei rischi: unità di lavoro, pericoli, punteggio, misure, revisione datata',
    'Registro degli infortuni sul lavoro e dei mancati incidenti, giorni di assenza',
    'Dispositivi di protezione: consegna nominativa, validità, sostituzione',
    'Visite mediche: assunzione, periodica, rientro, su richiesta',
    'Rappresentanza: elezioni, corpo elettorale, voto anonimo, mandati e loro scadenza',
    'Riunioni dell\'organismo, vantaggi e servizi per i dipendenti',
    'Lo spazio di gestione si chiude da sé alla fine del mandato',
  ],
  'dom.finance.title': 'Finanza e amministrazione',
  'dom.finance.lede': 'I terzi, i contratti, il denaro che entra e quello che esce.',
  'dom.finance.items': [
    'Clienti e fornitori, scheda completa: contatti, contratti, fatture',
    'Contratti e soprattutto preavvisi: la data limite per disdire è calcolata e segnalata',
    'Fatture nei due sensi, totale calcolato, ritardo dedotto dalla scadenza',
    'Budget per reparto ed esercizio, consumo aggregato automaticamente',
    'Note spese: presentazione, approvazione, rimborso — mai l\'uno senza l\'altro',
    'Documenti di conformità dei terzi, datati e segnalati quarantacinque giorni prima',
    'Valutazioni fornitori con punteggio: vale l\'ultima revisione, non la media',
    'Multivaluta con il cambio fissato all\'emissione di ogni documento',
    'Fatturazione ricorrente: l\'abbonamento è lo stampo, la fattura è il documento',
    'Lettura automatica delle fatture ricevute e raccolta IMAP di una casella contabile',
  ],
  'dom.compta.title': 'Contabilità, paghe e IVA',
  'dom.compta.lede': 'Moduli spenti per impostazione predefinita, che si accendono quando servono.',
  'dom.compta.items': [
    'Contabilità in partita doppia: piano dei conti, giornali, bilancio di verifica, libro mastro',
    'Una scrittura non quadrata viene rifiutata, e il messaggio dice di quanto',
    'Una fattura diventa scrittura con un clic; esportazione CSV per lo studio',
    'Motore paghe: scale configurabili, dal lordo al netto, quota datoriale, costo azienda',
    'Busta paga dettagliata riga per riga, generazione in blocco, simulatore',
    'Liquidazioni IVA: a debito, a credito, ripartizione per aliquota, credito riportabile',
    'Una liquidazione depositata non si ricalcola: è un documento, non un cruscotto',
    'Fatturazione elettronica: controllo EN 16931 ed esportazione dell\'XML CII',
    'Tesoreria: conti, movimenti, riconciliazione, previsione a dodici settimane',
    'Cespiti: ammortamento lineare e decrescente, valore netto contabile',
  ],
  'dom.achats.title': 'Acquisti, magazzino e recupero crediti',
  'dom.achats.lede': 'Ciò che si ordina, ciò che arriva, ciò che viene fatturato — e ciò che ci devono.',
  'dom.achats.items': [
    'Richieste d\'acquisto approvate dal responsabile, poi dalla gestione oltre la soglia',
    'Ordini, ricevimenti e riconciliazione a tre: ordinato, ricevuto, fatturato',
    'Ricevere più dell\'ordinato è rifiutato; uno scarto di fatturazione è nominato, non bloccato',
    'Articoli, movimenti, soglia di allerta: la giacenza è la somma dei movimenti',
    'Una riga collegata a un articolo entra a magazzino al momento del ricevimento',
    'Scadenzario clienti per fascia di ritardo',
    'Solleciti scalati: promemoria, sollecito, messa in mora, in base a quanto già inviato',
    'Ogni sollecito registrato con il suo livello e la sua data',
  ],
  'dom.projets.title': 'Progetti, tempo e redditività',
  'dom.projets.lede': 'Sapere a che punto è un progetto, e quanto è costato davvero.',
  'dom.projets.items': [
    'Progetti legati a un cliente, un reparto, una squadra e un responsabile',
    'Traguardi datati e attività in colonne per stato, con priorità e stima',
    'Tempo imputato al progetto e all\'attività, al massimo 24 h per registrazione',
    'Redditività: ore, costo alla tariffa oraria, margine residuo, quota di budget consumata',
    'Tre cerchi di diritti: la gestione, il responsabile, i membri',
    'Tempo per persona e salute dei progetti sul cruscotto di direzione',
  ],
  'dom.support.title': 'Assistenza e conoscenza',
  'dom.support.lede': 'Le richieste interne e dei clienti in un unico circuito, e le risposte che restano.',
  'dom.support.items': [
    'Ticket interni e clienti, priorità, origine, assegnazione',
    'Tempo di prima risposta dedotto dalla priorità, ricalcolato dall\'apertura',
    'Note interne invisibili al richiedente, e non contate come risposta',
    'Separazione per categoria: una richiesta HR non esce dalle HR',
    'Base di conoscenza per categoria, ricerca full text, portata regolabile',
    'Indicatori: ticket aperti, in ritardo, tempo medio',
  ],
  'dom.ops.title': 'Operazioni e servizi generali',
  'dom.ops.lede': 'I turni, la qualità, le sale, i veicoli, la reception.',
  'dom.ops.items': [
    'Turni per persona e per giorno: postazioni, reperibilità, presidi, lavoro da remoto',
    'Sovrapposizione o assenza già concessa: il turno è rifiutato alla creazione',
    'Rotazioni riutilizzabili, turni notturni, pubblicazione della settimana',
    'Chi è reperibile in questo momento, con il suo numero',
    'Qualità: non conformità, cause profonde, azioni correttive e verifica d\'efficacia',
    'Audit interni: rilievi, sintesi, un rilievo promosso a non conformità',
    'Attrezzature assegnate e riprese, con lo storico dei detentori',
    'Sale e prenotazioni, sovrapposizione rifiutata nominando chi occupa',
    'Flotta: manutenzione, revisione, assicurazione, sinistri, chilometraggio',
    'Reception: registro visitatori, elenco dei presenti, posta in entrata e in uscita',
  ],
  'dom.direction.title': 'Direzione e governance',
  'dom.direction.lede': 'Ciò che la direzione guarda, e ciò che decide.',
  'dom.direction.items': [
    'Cruscotto: organico, assenti, fatturato, margine, costo del personale, tesoreria, assistenza',
    'Obiettivi e risultati chiave, ciascuno sulla propria scala, anche decrescente',
    'Riunioni: convocazione, ordine del giorno, presenze rilevate, verbale',
    'Registro delle decisioni con la loro motivazione — ciò che si cerca due anni dopo',
    'Azioni affidate con responsabile e scadenza, legate alla loro decisione',
    'Registro dei rischi: punteggio lordo e residuo, matrice 5 × 5, trattamento, revisione',
    'Eventi aziendali: capienza, lista d\'attesa automatica, firma presenze, budget',
    'Scadenze di tutti gli spazi raccolte in un solo elenco ordinato',
  ],
  'dom.it.title': 'Informatica e sviluppo',
  'dom.it.lede': 'Il parco software, gli accessi, gli incidenti, e ciò che il team rilascia.',
  'dom.it.items': [
    'Parco software: postazioni trattate come vincolo, costo annualizzato, rinnovi',
    'Revisione degli accessi applicativi: prima gli account chiusi, poi i diritti di amministrazione',
    'Incidenti informatici, con orario, e tempo medio di ripristino realmente misurato',
    'Catalogo dei servizi: criticità, responsabile, repository, documentazione',
    'Registro dei rilasci per ambiente e indicatori di rilascio',
    'Backup: archivio orario, integrità verificata, ripristino, esternalizzazione',
    'API REST di lettura con ambiti, webhook uscenti firmati',
    'Esportazione integrale dell\'istanza in JSON, documenti compresi, segreti esclusi',
  ],
  'dom.conformite.title': 'Conformità, societario e dati personali',
  'dom.conformite.lede': 'Ciò che un\'azienda deve poter dimostrare, tenuto giorno per giorno.',
  'dom.conformite.items': [
    'Libro soci: partecipazione dedotta dai movimenti, cessione scritta in due gambe',
    'Cariche sociali con durata, revoca e scadenza segnalata in anticipo',
    'Assemblee: quorum in quote, delibere, voti, verbale',
    'Deleghe di poteri: oggetto, massimale, durata, scadenza segnalata',
    'Conflitti d\'interesse e regali: ciascuno dichiara per sé, l\'amministrazione esamina',
    'Canale interno di segnalazione cifrato, referenti designati, seguito anonimo tramite codice',
    'Registro di audit con orario, esportabile e sigillato da concatenamento di impronte',
    'GDPR: registro dei trattamenti, diritto d\'accesso esportato, cancellazione ragionata',
    'Circuiti di approvazione configurabili: moduli, soglie, approvatori per funzione',
  ],
  'shot.membre-espace': 'Spazio del dipendente',
  'shot.membre-equipe': 'Spazio del responsabile',
  'shot.membre-demandes': 'Richieste interne',
  'shot.membre-agenda': 'Agenda personale e condivisa',
  'shot.membre-salles': 'Sale e prenotazioni',
  'shot.membre-messagerie': 'Messaggistica interna',
  'shot.membre-connaissances': 'Base di conoscenza',
  'shot.membre-coffre-fort': 'Cassaforte digitale',
  'shot.membre-profil': 'Profilo e sicurezza dell\'account',
  'shot.membre-juridique-membre': 'Le mie dichiarazioni',
  'shot.annuaire': 'Rubrica aziendale',
  'shot.organigramme': 'Organigramma',
  'shot.connexion': 'Schermata di accesso',
  'shot.pilotage': 'Cruscotto di direzione',
  'shot.admin': 'Console di amministrazione',
  'shot.rh': 'Risorse umane',
  'shot.gestion': 'Amministrazione e finanza',
  'shot.direction': 'Direzione e governance',
  'shot.projets': 'Progetti, traguardi e redditività',
  'shot.support': 'Assistenza e ticket',
  'shot.planning': 'Turni, rotazioni e reperibilità',
  'shot.qualite': 'Qualità e audit interni',
  'shot.sante-securite': 'Salute e sicurezza sul lavoro',
  'shot.informatique': 'Parco software e accessi',
  'shot.developpement': 'Servizi e rilasci',
  'shot.evenements': 'Eventi aziendali',
  'shot.juridique': 'Vita societaria e conformità',
  'shot.alertes': 'Canale di segnalazione',
  'shot.securite': 'Console di sicurezza',
  'shot.rgpd': 'Dati personali',
  'shot.parapheur': 'Cartella delle firme',
  'shot.sauvegardes': 'Backup e ripristino',
  'shot.comptabilite': 'Contabilità in partita doppia',
  'shot.paie': 'Motore paghe',
  'shot.tresorerie': 'Tesoreria e previsione',
  'shot.immobilisations': 'Cespiti e ammortamenti',
  'shot.crm': 'CRM commerciale',
  'shot.stock': 'Magazzino e acquisti',
  'shot.pilotage-sombre': 'Direzione — tema scuro',
  'shot.membre-espace-sombre': 'Spazio del dipendente — tema scuro',
  'shot.gestion-sombre': 'Amministrazione — tema scuro',
  'shot.projets-sombre': 'Progetti — tema scuro',
  'shot.juridique-sombre': 'Vita societaria — tema scuro',
  'shot.securite-sombre': 'Sicurezza — tema scuro',
  'tour.pilotage': 'Organico, fatturato, margine, tesoreria, assistenza: ciò che la direzione guarda, su una pagina. Un trattino indica un dato assente — mai uno zero che sembrerebbe una cifra.',
  'tour.membre-espace': 'La pagina che ognuno apre la mattina: il suo responsabile, le novità che lo riguardano, le sue richieste, i documenti da confermare, i suoi strumenti e le credenziali.',
  'tour.rh': 'Richieste da trattare, saldi, buste paga, documenti, formazione, colloqui: il fascicolo del dipendente si tiene qui, e le scadenze risalgono da sole.',
  'tour.gestion': 'Terzi, contratti e preavvisi, fatture nei due sensi, budget per reparto, note spese, recupero crediti. Il consumo di un budget si somma da sé.',
  'tour.projets': 'Traguardi, attività in colonne, tempo speso e redditività rispetto al budget. Il costo non si digita: si deduce dalle ore e dalla tariffa oraria.',
  'tour.juridique': 'Capitale, cariche sociali, assemblee e verbali, deleghe, dichiarazioni di interessi. Ciò che un\'azienda deve poter dimostrare, tenuto giorno per giorno.',
  'pricing.perEmployee': '5 € per dipendente al mese',
  'pricing.perEmployeeShort': 'per dipendente / mese',
  'pricing.argTitle': 'Cinque euro per dipendente, per tutto',
  'pricing.argBody': 'Uno strumento HR, un gestionale di contabilità, un tracker di progetti, un sistema di ticket, una cassaforte per le buste paga: cinque abbonamenti da 8 o 15 € per utente, cinque banche dati che non si parlano, cinque fatture. Toutadmin sostituisce l\'intera pila al prezzo del più economico — e i dati stanno finalmente nello stesso posto.',
  'pricing.gridTitle': 'La griglia, per organico',
  'pricing.gridLede': 'Il prezzo segue l\'organico e nient\'altro: 5 € per dipendente fino a duecentoquarantanove, 4 € da duecentocinquanta a cinquecento, 3 € oltre. Superare una fascia abbassa il conto di tutti, non solo dei nuovi arrivati.',
  'pricing.col.headcount': 'Organico',
  'pricing.col.monthly': 'Al mese',
  'pricing.col.perEmployee': 'Per dipendente',
  'pricing.upTo': 'Fino a {count} dipendenti',
  'pricing.under': 'Meno di {count} dipendenti',
  'pricing.once': 'una tantum',
  'pricing.lifetimeTitle': 'Perché una licenza a vita',
  'pricing.lifetimeBody': 'Diecimila euro una volta sola, senza abbonamento e senza limiti di tempo: la stessa istanza, gli stessi aggiornamenti, nessun tetto di organico. Con cento dipendenti si ripaga in venti mesi; con cinquecento, in cinque. È l\'offerta per chi preferisce un investimento a una voce di costo ricorrente — e per chi non vuole dipendere da nessuno per continuare a lavorare.',
  'faq.q9': 'Cosa succede se il mio organico cambia durante l\'anno?',
  'faq.a9': 'Il prezzo segue, nei due sensi, dal mese successivo e mai con effetto retroattivo. Un\'assunzione che ti fa superare una soglia si fattura il mese dopo; un\'uscita che ti fa scendere, allo stesso modo. Nessuno paga per account chiusi.',
  'faq.q10': 'La licenza a vita dà diritto agli aggiornamenti?',
  'faq.a10': 'Sì, senza limiti di tempo: è il senso di «a vita». Ricevi le stesse versioni dei piani mensili e puoi ospitare la base dati da te. Ciò che la licenza non comprende è l\'assistenza prioritaria, che resta un servizio a parte.',
  'pricing.someEmployees': '{count} dipendenti',
  'nav.docs': 'Documentazione',
  'menu.title': 'Tutto il sito',
  'menu.close': 'Chiudere la mappa del sito',
  'menu.domains': 'I quattordici ambiti',
  'menu.home.d': 'Cosa copre il prodotto, in cifre, e uno sguardo alle schermate.',
  'menu.features.d': 'L\'elenco completo, ambito per ambito: oltre centotrenta funzioni rilasciate e testate.',
  'menu.screens.d': 'Quaranta immagini di un\'istanza reale, in tema chiaro e scuro.',
  'menu.security.d': 'Autenticazione, registro sigillato, dati personali, canale di segnalazione, backup — e i limiti che ci assumiamo.',
  'menu.pricing.d': 'Il prezzo per dipendente, la griglia per organico e la licenza a vita.',
  'menu.contact.d': 'Chiedere una dimostrazione sui tuoi casi, o scriverci.',
  'menu.docs.d': 'Installazione, configurazione, sicurezza, API e glossario completo. Sito separato.',
  'menu.home': 'Home',
};
