/* nl — traduit du français. Toute clé du français doit exister ici :
   le build refuse de construire une langue incomplète. */
module.exports = {
  'locale.name': 'Nederlands',
  'site.name': 'Toutadmin',
  'site.tagline': 'Het CMS dat het hele bedrijf beheert',
  'nav.product': 'Product',
  'nav.features': 'Functies',
  'nav.screens': 'De schermen',
  'nav.security': 'Beveiliging',
  'nav.pricing': 'Prijzen',
  'nav.contact': 'Contact',
  'nav.demo': 'Demo aanvragen',
  'nav.menu': 'Menu',
  'nav.language': 'Taal',
  'nav.theme': 'Thema',
  'nav.themeLight': 'Licht',
  'nav.themeDark': 'Donker',
  'nav.themeSystem': 'Systeem',
  'hero.eyebrow': 'Bedrijfsbeheersoftware',
  'hero.title': 'Uw hele bedrijf,\nin één enkele software.',
  'hero.lede': 'Personeel, HR, financiën, operations, governance, compliance, facilitair. Vijfendertig werkruimten die met elkaar praten, één database, geen apps om aan elkaar te plakken. In zestien talen, en € 5 per medewerker per maand voor het geheel.',
  'hero.ctaPrimary': 'Gratis proberen',
  'hero.ctaSecondary': 'Bekijk de functies',
  'hero.note': 'Zonder bankkaart. Uw gegevens blijven van u — en mogen bij u blijven.',
  'hero.badge1': 'SaaS, klaar in vijf minuten',
  'hero.badge2': 'of door uzelf gehost',
  'hero.badge3': 'AVG vanaf de basis',
  'stats.title': 'Wat het product dekt, in cijfers',
  'stats.spaces': 'werkruimten',
  'stats.spacesNote': 'van de eigen pagina van de medewerker tot het vennootschapsrecht',
  'stats.languages': 'interfacetalen',
  'stats.languagesNote': 'Arabisch inbegrepen, pagina gespiegeld',
  'stats.tests': 'integratietests',
  'stats.testsNote': 'uitgevoerd bij elke oplevering',
  'stats.modules': 'activeerbare modules',
  'stats.modulesNote': 'boekhouding, loon, treasury, CRM…',
  'stats.deps': 'externe diensten nodig',
  'stats.depsNote': 'één machine, één database, verder niets',
  'stats.keys': 'vertaalde labels',
  'stats.keysNote': 'tot en met de bevestigingsvensters',
  'pillars.title': 'Waarom Toutadmin en niet vijf aan elkaar geplakte tools',
  'pillars.lede': 'Vijf programma\'s die niet met elkaar praten kosten meer dan één, en doen het belangrijkste verliezen: het overzicht. Toutadmin vertrekt van het omgekeerde — één database, werkruimten, rechten.',
  'pillars.1.title': 'Eén plek, één waarheid',
  'pillars.1.body': 'Het budget van een afdeling telt zijn eigen facturen en de goedgekeurde onkosten van zijn leden vanzelf op. Een ontvangst gaat in dezelfde beweging de voorraad in. Niemand typt iets opnieuw in, dus spreekt niemand zichzelf tegen.',
  'pillars.2.title': 'Rechten zijn geen versiering',
  'pillars.2.body': 'Elke route draagt haar eigen controle aan de serverzijde, en de koppelingen worden bij elk verzoek opnieuw gelezen. Een vertrek snijdt de toegang meteen af — niet pas als de cookie verloopt. Wat u niet mag zien, wordt zelfs niet doorzocht.',
  'pillars.3.title': 'Vervaldata komen naar u toe',
  'pillars.3.body': 'Opzegtermijnen, te hernieuwen bevoegdheden, medische keuringen, technische controle, bestuursmandaten, attesten van leveranciers: één motor verzamelt ze en waarschuwt de juiste persoon, één keer, zonder dubbels.',
  'pillars.4.title': 'Elk scherm zegt wat het niet doet',
  'pillars.4.body': 'Een module toont haar grens op het moment dat u ze aanzet, niet achterin een handleiding. Een eerlijke zin is ons liever dan een aangevinkt vakje: precies dat voorkomt de nare verrassing in de derde maand.',
  'pillars.5.title': 'Zestien talen, echt waar',
  'pillars.5.body': 'Niet alleen het beginscherm: de statussen, de foutmeldingen, de bevestigingsvensters. Het Arabisch spiegelt de hele pagina, omdat de stylesheet enkel logische eigenschappen gebruikt.',
  'pillars.6.title': 'Uw gegevens, bij u als u dat wilt',
  'pillars.6.body': 'In SaaS is alles in vijf minuten klaar. In de betaalde formules kunt u de database ook op uw eigen server zetten: dezelfde software, dezelfde updates, gegevens binnen uw muren.',
  'tour.title': 'Dichte software, geen speelgoed',
  'tour.lede': 'Schermen gemaakt voor wie ze acht uur per dag openhoudt: informatie in één oogopslag, geen nutteloze pop-ups, en overal hetzelfde vocabulaire.',
  'tour.hint': 'Klik op een tab om van scherm te wisselen.',
  'tour.all': 'Alle 40 schermen bekijken',
  'features.title': 'Alles wat Toutadmin kan',
  'features.lede': 'De volledige lijst, domein per domein. Elke regel is opgeleverde en geteste code, geen voornemen.',
  'features.legend': 'Functies met «module» worden vanuit de console aangezet wanneer u ze nodig hebt.',
  'features.module': 'module',
  'features.seeAll': 'Volledige lijst bekijken',
  'features.intro': 'Veertien domeinen, meer dan honderddertig functies.',
  'features.ctaTitle': 'Ontbreekt er iets?',
  'features.ctaBody': 'Zeg het ons. Het product groeit in schijven, en de vragen van de bedrijven die het gebruiken gaan voor.',
  'screens.title': 'De schermen, onbewerkt',
  'screens.lede': 'Alle afbeeldingen op deze site komen uit een echte instantie met demogegevens. Geen mock-ups, geen montage.',
  'screens.light': 'Licht thema',
  'screens.dark': 'Donker thema',
  'screens.member': 'Werkruimte van de medewerker',
  'screens.admin': 'Beheer en sturing',
  'screens.modules': 'Optionele modules',
  'screens.open': 'Vergroten',
  'screens.close': 'Sluiten',
  'screens.prev': 'Vorige',
  'screens.next': 'Volgende',
  'security.title': 'Beveiliging is geen betaalde optie',
  'security.lede': 'Alles hieronder zit in het product, ongeacht de formule — ook de gratis formule.',
  'security.1.title': 'Geharde authenticatie',
  'security.1.body': 'Gehashte wachtwoorden (bcrypt), complexiteitsbeleid, vergrendeling na herhaalde mislukkingen, TOTP-tweestapsverificatie met herstelcodes, sessies één voor één of allemaal tegelijk intrekbaar.',
  'security.2.title': 'Verzegeld auditlogboek',
  'security.2.body': 'Elke regel draagt de vingerafdruk van de vorige. Een regel wijzigen, of er één uit het midden halen, breekt de ketting precies daar, en de controle zegt welke. Wat het niet doet: herschrijven verhinderen door wie de server beheert — het maakt het zichtbaar.',
  'security.3.title': 'Persoonsgegevens',
  'security.3.body': 'Verwerkingsregister, recht op inzage bron per bron geëxporteerd, wissing die bewaart wat de wet verplicht te bewaren en dat ook zegt. De account wordt geanonimiseerd in plaats van verwijderd, zodat de boekingen die ernaar verwijzen coherent blijven.',
  'security.4.title': 'Intern meldkanaal',
  'security.4.body': 'In Frankrijk verplicht vanaf vijftig medewerkers. Inhoud versleuteld in de database, enkel leesbaar voor de aangeduide vertrouwenspersonen — niet voor beheerders, want een melding kan er een viseren. Anonieme opvolging via code, zonder account en zonder logging.',
  'security.5.title': 'Gecontroleerde back-ups',
  'security.5.body': 'Uurlijks archief, integriteitscontrole via manifest, herstel dat database én bestanden terugzet, externalisatie via FTPS of Google Drive, en waarschuwing aan de beheerders bij mislukking.',
  'security.6.title': 'Versleutelde geheimen',
  'security.6.body': 'Wachtwoorden van externe diensten, API-tokens, webhook-geheimen: versleuteld met AES-256-GCM, nooit opnieuw leesbaar getoond, onleesbaar na manipulatie.',
  'security.hostTitle': 'SaaS, of bij u',
  'security.hostBody': 'In SaaS hosten wij in Europa, back-ups inbegrepen. In de betaalde formules is lokale hosting mogelijk: u installeert op uw server, de database verlaat uw muren nooit, en u krijgt dezelfde updates. Eén machine volstaat — Node 22 en SQLite, geen externe database om te beheren.',
  'security.limitsTitle': 'Wat wij niet beweren te doen',
  'security.limitsBody': 'De elektronische handtekening is eenvoudig, niet gekwalificeerd in de zin van eIDAS. De kluis verzegelt en dateert documenten, maar een tegenover derden afdwingbare tijdstempel vergt een certificatieautoriteit. Geen fiscale of sociale aangifte: de software maakt de gegevens, het indienen blijft de zaak van uw boekhouder. Dat staat hier en niet pas na de handtekening.',
  'pricing.title': 'Leesbare prijzen, zonder verrassingen',
  'pricing.lede': 'Eén prijs, per medewerker per maand, om het hele bedrijf te beheren. Geen modules à la carte, geen toeslag per functie: het hele product zit in elke formule.',
  'pricing.perMonth': '/ maand',
  'pricing.free': 'Gratis',
  'pricing.custom': 'Op maat',
  'pricing.vat': 'Prijzen exclusief btw. Geen looptijdverbintenis op de maandformules.',
  'pricing.cta': 'Beginnen',
  'pricing.ctaCustom': 'Schrijf ons',
  'pricing.popular': 'Meest gekozen',
  'pricing.p1.name': 'Gratis',
  'pricing.p1.for': 'Minder dan 5 medewerkers',
  'pricing.p1.body': 'Het hele product, gratis, zonder tijdslimiet en zonder afgeknepen functies. De formule voor een jong bedrijf, een vereniging of een kantoor dat begint.',
  'pricing.p2.name': 'Abonnement',
  'pricing.p2.for': '5 tot 250 medewerkers',
  'pricing.p2.body': '€ 5 per medewerker per maand, degressief vanaf tweehonderdvijftig. U betaalt het bestand dat u hebt, niet dat wat u ooit zou kunnen hebben.',
  'pricing.p3.name': 'Onbeperkt',
  'pricing.p3.for': 'Zonder personeelsgrens',
  'pricing.p3.body': '€ 1.500 per maand, ongeacht het aantal medewerkers. Voorbij driehonderd personen is dat al goedkoper dan het tarief per medewerker — en de prijs beweegt niet meer.',
  'pricing.p4.name': 'Levenslange licentie',
  'pricing.p4.for': 'Eenmalige betaling',
  'pricing.p4.body': '€ 10.000 eenmalig. Geen abonnement, geen tijdslimiet, geen maximum aan medewerkers. De software is van u zolang u ze wilt gebruiken.',
  'pricing.tableTitle': 'Wat elke formule bevat',
  'pricing.col.feature': '',
  'pricing.yes': 'Inbegrepen',
  'pricing.no': 'Nee',
  'pricing.option': 'Optioneel',
  'pricing.f.allSpaces': 'De 35 werkruimten en de 7 modules',
  'pricing.f.languages': 'De 16 talen en de 3 kleurpaletten',
  'pricing.f.security': 'Volledige beveiliging, verzegeld logboek, AVG',
  'pricing.f.updates': 'Updates inbegrepen',
  'pricing.f.saas': 'SaaS-hosting in Europa',
  'pricing.f.local': 'Lokale hosting van uw gegevens',
  'pricing.f.backupOff': 'Externalisatie van de back-ups',
  'pricing.f.support': 'Ondersteuning',
  'pricing.f.supportMail': 'Per e-mail',
  'pricing.f.supportPrio': 'Met voorrang',
  'pricing.f.supportDedicated': 'Vast aanspreekpunt',
  'pricing.f.supportCommunity': 'Documentatie',
  'pricing.f.migration': 'Overname van uw gegevens',
  'pricing.f.sla': 'Dienstverbintenis (SLA)',
  'pricing.f.api': 'Lees-API en webhooks',
  'pricing.f.multisite': 'Meerdere vestigingen, meerdere entiteiten',
  'pricing.countTitle': 'Hoe wij medewerkers tellen',
  'pricing.countBody': 'De actieve accounts, freelancers en stagiairs inbegrepen, beheerders uitgezonderd. Een gesloten account telt niet meer mee, ook al behoudt hij toegang tot zijn kluis. Een drempel overschreden? De wijziging geldt de volgende maand, nooit met terugwerkende kracht — en omlaag gaat het net zo.',
  'faq.title': 'Veelgestelde vragen',
  'faq.q1': 'Is de gratis formule in tijd beperkt?',
  'faq.a1': 'Nee. Onder vijf medewerkers is het product gratis zonder tijdslimiet en zonder afgeknepen functies. Wij verkiezen een kleine structuur die met de software meegroeit boven een proefversie die na dertig dagen uitdooft.',
  'faq.q2': 'Kan ik mijn gegevens op mijn eigen server hosten?',
  'faq.a2': 'Ja, in de betaalde formules. De software draait op één machine met Node 22 en SQLite: geen databaseserver, geen externe dienst. Database, documenten en back-ups blijven bij u.',
  'faq.q3': 'Wat gebeurt er als ik stop?',
  'faq.a3': 'U exporteert de volledige instantie als JSON, documenten inbegrepen, vanuit de beheerconsole. Niets wordt gegijzeld: het is uw database, en ze vertrekt met u in een leesbaar formaat.',
  'faq.q4': 'Vervangt het mijn boekhouder?',
  'faq.a4': 'Nee. Dubbele boekhouding, loon en btw zijn er om uw boekingen te houden en de stukken voor te bereiden. Er is geen jaarrekening en geen elektronische aangifte: de export voedt uw kantoor.',
  'faq.q5': 'Moeten de teams opgeleid worden?',
  'faq.a5': 'De werkruimte van de medewerker spreekt voor zich: verlof, documenten, planning, adresboek. De beheerruimten vragen een halve dag inwerken, die wij begeleiden in de formules Onderneming en Op maat.',
  'faq.q6': 'Kan ik slechts een deel van het product aanzetten?',
  'faq.a6': 'Ja. Zeven modules — boekhouding, loon, e-facturatie, voorraad en aankoop, treasury, vaste activa, CRM — staan standaard uit en gaan één voor één aan. Zolang een module uit staat, antwoorden haar adressen met 404.',
  'faq.q7': 'Hoe verloopt de overname van mijn huidige gegevens?',
  'faq.a7': 'Een CSV-massa-import controleert elke regel vóór het schrijven, en schrijft niets als één enkele regel ongeldig is. In de formules Onderneming en Op maat bereiden wij de bestanden samen met u voor.',
  'faq.q8': 'En de koppelingen met onze tools?',
  'faq.a8': 'Een lees-REST-API met scopes en ondertekende uitgaande webhooks zitten erin. Voor specifieke uitwisselingen — HR-systeem, ERP, facturatie — is dat het terrein van de formule Op maat.',
  'contact.title': 'Laten we over uw bedrijf praten',
  'contact.lede': 'Een demonstratie duurt dertig minuten, op uw eigen gevallen in plaats van op verzonnen gegevens. Schrijf ons wat u wilt oplossen.',
  'contact.emailLabel': 'Per e-mail',
  'contact.demoTitle': 'Een demonstratie aanvragen',
  'contact.demoBody': 'Geef uw naam, uw bedrijf, uw personeelsbestand en wat u vandaag last bezorgt. Wij antwoorden binnen één werkdag.',
  'contact.write': 'Het team schrijven',
  'contact.docTitle': 'De documentatie lezen',
  'contact.docBody': 'De documentatiesite beschrijft de installatie, de configuratie, de beveiliging, de API en het volledige lexicon in de zestien talen.',
  'contact.docCta': 'Documentatie openen',
  'contact.selfTitle': 'Zelf installeren',
  'contact.selfBody': 'Node 22, één machine, vijf minuten: de wizard maakt de database en het beheerdersaccount aan en controleert de omgeving.',
  'contact.selfCta': 'De vereisten bekijken',
  'cta.title': 'Begin gratis, verander van formule wanneer u groeit',
  'cta.body': 'Onder vijf medewerkers is alles gratis. Daarboven € 5 per medewerker per maand, of € 10.000 eenmalig voor de levenslange licentie. Geen bankkaart om te proberen.',
  'cta.primary': 'Mijn instantie aanmaken',
  'cta.secondary': 'Met iemand praten',
  'foot.product': 'Product',
  'foot.company': 'Over ons',
  'foot.resources': 'Bronnen',
  'foot.legal': 'Juridisch',
  'foot.docs': 'Documentatie',
  'foot.status': 'Wat gedekt is',
  'foot.rights': 'Alle rechten voorbehouden.',
  'foot.madeWith': 'Node 22 · Express · SQLite. Geen nutteloze afhankelijkheid.',
  'foot.langTitle': 'Deze site bestaat in zestien talen',
  'dom.socle.title': 'Fundament en organisatie',
  'dom.socle.lede': 'Wat de rest draagt: de accounts, de koppelingen en het vocabulaire dat alle werkruimten delen.',
  'dom.socle.items': [
    'Accounts en stapelbare rollen: beheerder, HR, financiën, IT, vertrouwenspersoon meldingen',
    'Leidinggevende afgeleid uit de werkelijke aansturing, nooit met de hand toegekend',
    'Afdelingen en teams, meerdere leidinggevenden per perimeter, koppelingen bij elk verzoek herlezen',
    'Visueel organigram, leiding inbegrepen, en de mensen die nergens gekoppeld zijn',
    'Adresboek met zoeken en filters, zichtbaarheid enkel door het beheer gestuurd',
    'Interne berichten, en professioneel adres door het beheer ingesteld',
    'Globale zoekfunctie aan de bron gescheiden: wat u niet mag zien, wordt niet gezocht',
    'Meldingencentrum per persoon, met leesbevestiging',
    'CSV-massa-import: gecontroleerde voorvertoning, alles-of-niets wegschrijven',
    'Installatiewizard, instellingen van de instantie, zeven activeerbare modules',
    '16 talen, 3 paletten, thema licht/donker/systeem, meegroeiende interface',
  ],
  'dom.espace.title': 'Werkruimte van de medewerker',
  'dom.espace.lede': 'De pagina die iedereen \'s ochtends opent: wat hem aangaat, en niets anders.',
  'dom.espace.items': [
    'Persoonlijk dashboard: leidinggevende, nieuws, aanvragen, te bevestigen documenten',
    'Verlof, recuperatie, afwezigheid en telewerk: werkdagen berekend, weekends uitgesloten',
    'Actueel verlofsaldo, geschiedenis van de gemotiveerde correcties',
    'Loonbrieven raadpleegbaar en vijftig jaar in de kluis bewaard',
    'Persoonlijke agenda en gedeelde teamagenda',
    'Weekplanning, wachtdienst, permanenties',
    'Toegewezen tools met eigen gebruikersnaam — geen enkel extern wachtwoord bewaard',
    'Profiel: foto, voorstelling, telefoon, taal, wachtwoord, alle sessies sluiten',
    'Tijdregistratie met chronometer voor freelancers, slechts één lopend tegelijk',
    'Verklaring van belangen en geschenken, enkel voor uzelf zichtbaar',
  ],
  'dom.rh.title': 'Human resources',
  'dom.rh.lede': 'Het dossier van de medewerker, van aankomst tot vertrek, met de vervaldata die erbij horen.',
  'dom.rh.items': [
    'Goedkeuring met afname van het saldo, gemotiveerde weigering, annulering die terugstort',
    'Loonbrieven: aanmaak, opvolging van de betaling, generatie in batch',
    'Bedrijfsdocumenten met ontvangstbevestiging op naam',
    'Opleiding: catalogus, sessies, inschrijvingen, kost en duur',
    'Jaargesprekken: campagne, leidraad, verslag',
    'Aankomst en vertrek: opgevolgde checklists, verantwoordelijke en termijn per taak',
    'Competenties en bevoegdheden, met hernieuwingsdatum en tijdige waarschuwing',
    'Individuele gesprekken: gedeelde samenvatting, notities van de leidinggevende apart',
    'Digitale kluis ook na vertrek bereikbaar, documenten verzegeld door hun vingerafdruk',
    'Eenvoudige elektronische handtekening: geordend circuit, vingerafdruk, zegel, attest',
    'Contracten van bepaalde duur: het account sluit zichzelf op de dag zelf',
  ],
  'dom.talent.title': 'Werving en talent',
  'dom.talent.lede': 'Van sollicitaties tot de eerste dag, zonder rekenblad ertussen.',
  'dom.talent.items': [
    'Vacatures en sollicitaties per fase opgevolgd',
    'Cv-ontvangst: PDF, DOCX of tekst, buiten de repository weggeschreven',
    'Extractie van de inhoud en doorzoekbare cv-databank',
    'Gewogen criteria, score, drempel, rangschikking van de sollicitaties',
    'Een aangenomen kandidaat gaat rechtstreeks naar het onthaaltraject',
    'Interne enquêtes en sociale barometer, anoniem door hun opbouw',
    'Onder vijf antwoorden wordt geen enkel resultaat getoond',
  ],
  'dom.sst.title': 'Gezondheid, veiligheid en ondernemingsraad',
  'dom.sst.lede': 'De verplichtingen die op papier moeten staan, en zichzelf in herinnering brengen.',
  'dom.sst.items': [
    'Risicoanalyse: werkeenheden, gevaren, quotering, maatregelen, gedateerde herziening',
    'Register van arbeidsongevallen en bijna-ongevallen, dagen afwezigheid',
    'Beschermingsmiddelen: uitgifte op naam, geldigheidsduur, vervanging',
    'Medische onderzoeken: aanwerving, periodiek, werkhervatting, op verzoek',
    'Ondernemingsraad: verkiezingen, kiezerslijst, anonieme stemming, mandaten en hun einde',
    'Vergaderingen van het orgaan, voordelen en diensten voor de medewerkers',
    'De beheerruimte sluit zichzelf wanneer het mandaat afloopt',
  ],
  'dom.finance.title': 'Financiën en beheer',
  'dom.finance.lede': 'De derden, de contracten, het geld dat binnenkomt en dat buitengaat.',
  'dom.finance.items': [
    'Klanten en leveranciers, volledige fiche: contactpersonen, contracten, facturen',
    'Contracten en vooral opzegtermijnen: de uiterste opzegdatum wordt berekend en gemeld',
    'Facturen in beide richtingen, totaal berekend, achterstand afgeleid uit de vervaldag',
    'Budgetten per afdeling en boekjaar, verbruik automatisch geaggregeerd',
    'Onkostennota\'s: indiening, goedkeuring, terugbetaling — nooit het een zonder het ander',
    'Nalevingsdocumenten van derden, gedateerd en vijfenveertig dagen vooraf gemeld',
    'Gescoorde leveranciersbeoordelingen: de laatste telt, niet het gemiddelde',
    'Meerdere valuta met de koers vastgezet bij uitgifte van elk stuk',
    'Terugkerende facturatie: het abonnement is de mal, de factuur is het stuk',
    'Automatisch uitlezen van ontvangen facturen en IMAP-ophaling van een boekhoudmailbox',
  ],
  'dom.compta.title': 'Boekhouding, loon en btw',
  'dom.compta.lede': 'Modules, standaard uit, die aangaan wanneer u ze nodig hebt.',
  'dom.compta.items': [
    'Dubbele boekhouding: rekeningstelsel, dagboeken, proefbalans, grootboek',
    'Een niet-sluitende boeking wordt geweigerd, en de melding zegt met hoeveel',
    'Een factuur wordt met één klik een boeking; CSV-export voor uw kantoor',
    'Loonmotor: instelbare schalen, bruto naar netto, werkgeversbijdrage, werkgeverskost',
    'Gedetailleerde loonbrief regel per regel, generatie in batch, simulator',
    'Btw-aangiften: verschuldigd, aftrekbaar, verdeling per tarief, overdraagbaar tegoed',
    'Een ingediende aangifte wordt niet herrekend: het is een stuk, geen dashboard',
    'E-facturatie: controle EN 16931 en export van de CII-XML',
    'Treasury: rekeningen, bewegingen, aansluiting, prognose op twaalf weken',
    'Vaste activa: lineaire en degressieve afschrijving, netto boekwaarde',
  ],
  'dom.achats.title': 'Aankoop, voorraad en invordering',
  'dom.achats.lede': 'Wat besteld wordt, wat toekomt, wat gefactureerd wordt — en wat men ons verschuldigd is.',
  'dom.achats.items': [
    'Aankoopaanvragen goedgekeurd door de leidinggevende, daarna door financiën boven de drempel',
    'Bestelbonnen, ontvangsten en drievoudige aansluiting: besteld, ontvangen, gefactureerd',
    'Meer ontvangen dan besteld wordt geweigerd; een factuurafwijking wordt benoemd, niet geblokkeerd',
    'Artikelen, bewegingen, meldingsdrempel: de voorraad is de som van de bewegingen',
    'Een regel gekoppeld aan een artikel gaat bij ontvangst meteen de voorraad in',
    'Ouderdomsbalans van klanten per achterstandsklasse',
    'Getrapte aanmaningen: herinnering, aanmaning, ingebrekestelling, volgens wat al verstuurd is',
    'Elke aanmaning vastgelegd met haar niveau en datum',
  ],
  'dom.projets.title': 'Projecten, tijd en rendabiliteit',
  'dom.projets.lede': 'Weten waar een project staat, en wat het werkelijk gekost heeft.',
  'dom.projets.items': [
    'Projecten gekoppeld aan een klant, een afdeling, een team en een verantwoordelijke',
    'Gedateerde mijlpalen en taken in kolommen per status, met prioriteit en raming',
    'Tijd geboekt op project en taak, hoogstens 24 u per invoer',
    'Rendabiliteit: uren, kost tegen uurtarief, resterende marge, verbruikt budgetaandeel',
    'Drie rechtenkringen: het beheer, de verantwoordelijke, de leden',
    'Tijd per persoon en gezondheid van de projecten op het directiedashboard',
  ],
  'dom.support.title': 'Support en kennis',
  'dom.support.lede': 'De interne en klantvragen in één circuit, en antwoorden die blijven.',
  'dom.support.items': [
    'Interne en klantentickets, prioriteit, herkomst, toewijzing',
    'Termijn voor eerste antwoord afgeleid uit de prioriteit, herrekend vanaf de opening',
    'Interne notities onzichtbaar voor de aanvrager, en niet geteld als antwoord',
    'Gescheiden per categorie: een HR-vraag verlaat HR niet',
    'Kennisbank per categorie, zoeken in volledige tekst, instelbaar bereik',
    'Indicatoren: openstaande tickets, te laat, gemiddelde termijn',
  ],
  'dom.ops.title': 'Operations en facilitair',
  'dom.ops.lede': 'De planning, de kwaliteit, de zalen, de voertuigen, het onthaal.',
  'dom.ops.items': [
    'Planning per persoon en per dag: shiften, wachtdienst, permanenties, telewerk',
    'Overlapping of reeds toegestane afwezigheid: het blok wordt bij het aanmaken geweigerd',
    'Herbruikbare beurtrollen, nachtshiften, publicatie van de week',
    'Wie op dit moment van wacht is, met zijn nummer',
    'Kwaliteit: afwijkingen, grondoorzaken, corrigerende acties en doeltreffendheidscontrole',
    'Interne audits: vaststellingen, synthese, een vaststelling verheven tot afwijking',
    'Toegewezen en teruggenomen uitrusting, met de geschiedenis van de houders',
    'Zalen en reservaties, overlapping geweigerd met vermelding van wie ze bezet',
    'Wagenpark: onderhoud, technische controle, verzekering, schadegevallen, kilometerstand',
    'Onthaal: bezoekersregister, lijst van aanwezigen, inkomende en uitgaande post',
  ],
  'dom.direction.title': 'Directie en governance',
  'dom.direction.lede': 'Waar de directie naar kijkt, en wat ze beslist.',
  'dom.direction.items': [
    'Dashboard: personeelsbestand, afwezigen, gefactureerd, marge, loonmassa, kas, supportlast',
    'Doelstellingen en sleutelresultaten, elk op zijn eigen schaal, ook dalend',
    'Vergaderingen: uitnodiging, agenda, aanwezigheden afgetekend, verslag',
    'Register van beslissingen met hun motief — wat men twee jaar later zoekt',
    'Toevertrouwde acties met houder en termijn, gekoppeld aan hun beslissing',
    'Risicoregister: bruto en restquotering, 5 × 5-matrix, behandeling, herziening',
    'Bedrijfsevenementen: capaciteit, automatische wachtlijst, aftekenlijst, budget',
    'Vervaldata uit alle werkruimten in één gesorteerde lijst',
  ],
  'dom.it.title': 'IT en ontwikkeling',
  'dom.it.lede': 'Het softwarepark, de toegangen, de incidenten, en wat het team oplevert.',
  'dom.it.items': [
    'Softwarepark: licenties als beperking beheerd, geannualiseerde kost, hernieuwingen',
    'Toegangsherziening: eerst de gesloten accounts, daarna de beheerdersrechten',
    'IT-incidenten met tijdstip, en werkelijk gemeten gemiddelde hersteltijd',
    'Dienstencatalogus: kritikaliteit, verantwoordelijke, repository, documentatie',
    'Register van opleveringen per omgeving en leveringsindicatoren',
    'Back-ups: uurlijks archief, geverifieerde integriteit, herstel, externalisatie',
    'Lees-REST-API met scopes, ondertekende uitgaande webhooks',
    'Volledige export van de instantie als JSON, documenten inbegrepen, geheimen uitgesloten',
  ],
  'dom.conformite.title': 'Compliance, vennootschapsrecht en persoonsgegevens',
  'dom.conformite.lede': 'Wat een bedrijf moet kunnen bewijzen, gaandeweg bijgehouden.',
  'dom.conformite.items': [
    'Aandeelhoudersregister: bezit afgeleid uit de bewegingen, overdracht in twee poten geboekt',
    'Bestuursmandaten met duur, herroeping en vooraf gemeld einde',
    'Algemene vergaderingen: quorum in aandelen, besluiten, stemmen, notulen',
    'Volmachten: voorwerp, plafond, duur, gemeld einde',
    'Belangenconflicten en geschenken: ieder verklaart voor zichzelf, het beheer onderzoekt',
    'Versleuteld intern meldkanaal, aangeduide vertrouwenspersonen, anonieme opvolging via code',
    'Auditlogboek met tijdstip, exporteerbaar en verzegeld door ketening van vingerafdrukken',
    'AVG: verwerkingsregister, geëxporteerd inzagerecht, beredeneerde wissing',
    'Instelbare goedkeuringscircuits: formulieren, drempels, goedkeurders per functie',
  ],
  'shot.membre-espace': 'Werkruimte van de medewerker',
  'shot.membre-equipe': 'Werkruimte van de leidinggevende',
  'shot.membre-demandes': 'Interne aanvragen',
  'shot.membre-agenda': 'Persoonlijke en gedeelde agenda',
  'shot.membre-salles': 'Zalen en reservaties',
  'shot.membre-messagerie': 'Interne berichten',
  'shot.membre-connaissances': 'Kennisbank',
  'shot.membre-coffre-fort': 'Digitale kluis',
  'shot.membre-profil': 'Profiel en accountbeveiliging',
  'shot.membre-juridique-membre': 'Mijn verklaringen',
  'shot.annuaire': 'Bedrijfsadresboek',
  'shot.organigramme': 'Organigram',
  'shot.connexion': 'Aanmeldscherm',
  'shot.pilotage': 'Directiedashboard',
  'shot.admin': 'Beheerconsole',
  'shot.rh': 'Human resources',
  'shot.gestion': 'Administratief en financieel beheer',
  'shot.direction': 'Directie en governance',
  'shot.projets': 'Projecten, mijlpalen en rendabiliteit',
  'shot.support': 'Support en tickets',
  'shot.planning': 'Planning, beurtrollen en wachtdienst',
  'shot.qualite': 'Kwaliteit en interne audits',
  'shot.sante-securite': 'Gezondheid en veiligheid op het werk',
  'shot.informatique': 'Softwarepark en toegangen',
  'shot.developpement': 'Diensten en opleveringen',
  'shot.evenements': 'Bedrijfsevenementen',
  'shot.juridique': 'Vennootschapsleven en compliance',
  'shot.alertes': 'Intern meldkanaal',
  'shot.securite': 'Beveiligingsconsole',
  'shot.rgpd': 'Persoonsgegevens',
  'shot.parapheur': 'Handtekeningmap',
  'shot.sauvegardes': 'Back-ups en herstel',
  'shot.comptabilite': 'Dubbele boekhouding',
  'shot.paie': 'Loonmotor',
  'shot.tresorerie': 'Treasury en prognose',
  'shot.immobilisations': 'Vaste activa en afschrijvingen',
  'shot.crm': 'Commerciële CRM',
  'shot.stock': 'Voorraad en aankoop',
  'shot.pilotage-sombre': 'Directie — donker thema',
  'shot.membre-espace-sombre': 'Werkruimte medewerker — donker thema',
  'shot.gestion-sombre': 'Beheer — donker thema',
  'shot.projets-sombre': 'Projecten — donker thema',
  'shot.juridique-sombre': 'Vennootschapsleven — donker thema',
  'shot.securite-sombre': 'Beveiliging — donker thema',
  'tour.pilotage': 'Personeelsbestand, gefactureerd, marge, kas, support: waar de directie naar kijkt, op één pagina. Een streepje markeert een ontbrekend gegeven — nooit een nul die voor een cijfer zou doorgaan.',
  'tour.membre-espace': 'De pagina die iedereen \'s ochtends opent: zijn leidinggevende, het nieuws dat hem aangaat, zijn aanvragen, de te bevestigen documenten, zijn tools en gebruikersnamen.',
  'tour.rh': 'Aanvragen te behandelen, saldi, loonbrieven, documenten, opleiding, gesprekken: het dossier van de medewerker wordt hier gehouden, en de vervaldata komen vanzelf boven.',
  'tour.gestion': 'Derden, contracten en opzegtermijnen, facturen in beide richtingen, afdelingsbudgetten, onkosten, invordering. Het verbruik van een budget telt zichzelf op.',
  'tour.projets': 'Mijlpalen, taken in kolommen, bestede tijd en rendabiliteit tegenover het budget. De kost wordt niet ingetypt: hij volgt uit de uren en het uurtarief.',
  'tour.juridique': 'Kapitaal, bestuursmandaten, vergaderingen en notulen, volmachten, belangenverklaringen. Wat een bedrijf moet kunnen bewijzen, gaandeweg bijgehouden.',
  'pricing.perEmployee': '€ 5 per medewerker per maand',
  'pricing.perEmployeeShort': 'per medewerker / maand',
  'pricing.argTitle': 'Vijf euro per medewerker, voor alles',
  'pricing.argBody': 'Een HR-tool, een boekhoudpakket, een projectbeheerder, een ticketsysteem, een kluis voor loonbrieven: vijf abonnementen van 8 of 15 € per gebruiker, vijf databases die niet met elkaar praten, vijf facturen. Toutadmin vervangt de hele stapel voor de prijs van de goedkoopste — en de gegevens staan eindelijk op één plek.',
  'pricing.gridTitle': 'De staffel, naar personeelsbestand',
  'pricing.gridLede': 'De prijs volgt het personeelsbestand en niets anders. Boven de honderd medewerkers daalt het bedrag per persoon, en boven de tweehonderdvijftig stijgt het helemaal niet meer.',
  'pricing.col.headcount': 'Personeelsbestand',
  'pricing.col.monthly': 'Per maand',
  'pricing.col.perEmployee': 'Per medewerker',
  'pricing.unlimited': 'Onbeperkt',
  'pricing.upTo': 'Tot {count} medewerkers',
  'pricing.under': 'Minder dan {count} medewerkers',
  'pricing.once': 'eenmalig',
  'pricing.lifetimeTitle': 'Waarom een levenslange licentie',
  'pricing.lifetimeBody': 'Tienduizend euro eenmalig, zonder abonnement en zonder tijdslimiet: dezelfde instantie, dezelfde updates, geen maximum aan medewerkers. Bij honderd medewerkers is ze in twintig maanden terugverdiend, zonder personeelsgrens in zeven. Het aanbod voor wie een investering verkiest boven een terugkerende kostenpost — en voor wie van niemand afhankelijk wil zijn om te blijven werken.',
  'faq.q9': 'Wat als mijn personeelsbestand in de loop van het jaar verandert?',
  'faq.a9': 'De prijs volgt, in beide richtingen, vanaf de volgende maand en nooit met terugwerkende kracht. Een aanwerving die u over een drempel tilt, wordt de maand erna gefactureerd; een vertrek dat u eronder brengt, evengoed. Niemand betaalt voor gesloten accounts.',
  'faq.q10': 'Geeft de levenslange licentie recht op updates?',
  'faq.a10': 'Ja, zonder tijdslimiet: dat is wat « levenslang » betekent. U krijgt dezelfde versies als de maandformules en u mag de database bij u hosten. Wat de licentie niet omvat, is de voorrangsondersteuning; die blijft een aparte dienst.',
};
