/* pl — traduit du français. Toute clé du français doit exister ici :
   le build refuse de construire une langue incomplète. */
module.exports = {
  'locale.name': 'Polski',
  'site.name': 'Toutadmin',
  'site.tagline': 'CMS, który prowadzi całą firmę',
  'nav.product': 'Produkt',
  'nav.features': 'Funkcje',
  'nav.screens': 'Ekrany',
  'nav.security': 'Bezpieczeństwo',
  'nav.pricing': 'Cennik',
  'nav.contact': 'Kontakt',
  'nav.demo': 'Poproś o demo',
  'nav.menu': 'Menu',
  'nav.language': 'Język',
  'nav.theme': 'Motyw',
  'nav.themeLight': 'Jasny',
  'nav.themeDark': 'Ciemny',
  'nav.themeSystem': 'Systemowy',
  'hero.eyebrow': 'Oprogramowanie do zarządzania firmą',
  'hero.title': 'Cała firma,\nw jednym programie.',
  'hero.lede': 'Kadry, HR, finanse, operacje, ład korporacyjny, zgodność, administracja. Trzydzieści pięć przestrzeni, które ze sobą rozmawiają, jedna baza danych, żadnych aplikacji do sklejania. W szesnastu językach, i 5 € za pracownika miesięcznie za całość.',
  'hero.ctaPrimary': 'Wypróbuj za darmo',
  'hero.ctaSecondary': 'Zobacz funkcje',
  'hero.note': 'Bez karty płatniczej. Dane pozostają Twoje — i mogą zostać u Ciebie.',
  'hero.badge1': 'SaaS gotowy w pięć minut',
  'hero.badge2': 'albo hostowany u Ciebie',
  'hero.badge3': 'RODO od podstaw',
  'stats.title': 'Co obejmuje produkt, w liczbach',
  'stats.spaces': 'przestrzeni roboczych',
  'stats.spacesNote': 'od przestrzeni pracownika po sprawy spółki',
  'stats.languages': 'języków interfejsu',
  'stats.languagesNote': 'w tym arabski, strona odwrócona',
  'stats.tests': 'testów integracyjnych',
  'stats.testsNote': 'uruchamianych przy każdym wydaniu',
  'stats.modules': 'modułów do włączenia',
  'stats.modulesNote': 'księgowość, płace, finanse, CRM…',
  'stats.deps': 'usług zewnętrznych wymaganych',
  'stats.depsNote': 'jedna maszyna, jedna baza, nic więcej',
  'stats.keys': 'przetłumaczonych etykiet',
  'stats.keysNote': 'aż po okna potwierdzenia',
  'pillars.title': 'Dlaczego Toutadmin zamiast pięciu sklejonych narzędzi',
  'pillars.lede': 'Pięć programów, które ze sobą nie rozmawiają, kosztuje więcej niż jeden i odbiera to, co najważniejsze: całościowy obraz. Toutadmin zaczyna od odwrotności — jedna baza, przestrzenie, uprawnienia.',
  'pillars.1.title': 'Jedno miejsce, jedna prawda',
  'pillars.1.body': 'Budżet działu sam sumuje własne faktury i zatwierdzone wydatki swoich członków. Przyjęcie dostawy trafia do magazynu tym samym ruchem. Nikt niczego nie przepisuje, więc nikt sobie nie zaprzecza.',
  'pillars.2.title': 'Uprawnienia nie są ozdobą',
  'pillars.2.body': 'Każda ścieżka ma własną kontrolę po stronie serwera, a przypisania są odczytywane przy każdym żądaniu. Odejście odcina dostęp natychmiast — nie po wygaśnięciu ciasteczka. To, czego nie wolno Ci zobaczyć, nie jest w ogóle przeszukiwane.',
  'pillars.3.title': 'Terminy przychodzą do Ciebie',
  'pillars.3.body': 'Okresy wypowiedzenia, uprawnienia do odnowienia, badania lekarskie, przeglądy pojazdów, mandaty w organach spółki, zaświadczenia dostawców: jeden mechanizm zbiera je wszystkie i ostrzega właściwą osobę, raz, bez powtórzeń.',
  'pillars.4.title': 'Każdy ekran mówi, czego nie robi',
  'pillars.4.body': 'Moduł pokazuje swoje ograniczenie w chwili włączania, a nie na końcu instrukcji. Wolimy uczciwe zdanie od odhaczonego pola: to właśnie oszczędza przykrych niespodzianek w trzecim miesiącu.',
  'pillars.5.title': 'Szesnaście języków, naprawdę',
  'pillars.5.body': 'Nie tylko ekran startowy: statusy, komunikaty błędów, okna potwierdzenia. Arabski odwraca całą stronę, bo arkusz stylów używa wyłącznie własności logicznych.',
  'pillars.6.title': 'Twoje dane, u Ciebie, jeśli chcesz',
  'pillars.6.body': 'W modelu SaaS wszystko jest gotowe w pięć minut. W planach płatnych bazę można też trzymać na własnym serwerze: to samo oprogramowanie, te same aktualizacje, dane w Twoich murach.',
  'tour.title': 'Gęste oprogramowanie, nie zabawka',
  'tour.lede': 'Ekrany zrobione dla osób, które mają je otwarte osiem godzin dziennie: informacja na pierwszy rzut oka, żadnych zbędnych okien modalnych i wszędzie to samo słownictwo.',
  'tour.hint': 'Kliknij zakładkę, aby zmienić ekran.',
  'tour.all': 'Zobacz 40 ekranów',
  'features.title': 'Wszystko, co potrafi Toutadmin',
  'features.lede': 'Pełna lista, dziedzina po dziedzinie. Każdy wiersz to wdrożony i przetestowany kod, a nie zamiar.',
  'features.legend': 'Funkcje oznaczone «moduł» włącza się z konsoli, gdy są potrzebne.',
  'features.module': 'moduł',
  'features.seeAll': 'Zobacz pełną listę',
  'features.intro': 'Czternaście dziedzin, ponad sto trzydzieści funkcji.',
  'features.ctaTitle': 'Czegoś brakuje?',
  'features.ctaBody': 'Napisz do nas. Produkt rozwija się partiami, a prośby firm, które go używają, mają pierwszeństwo.',
  'screens.title': 'Ekrany, bez retuszu',
  'screens.lede': 'Wszystkie zrzuty na tej stronie pochodzą z prawdziwej instancji wypełnionej danymi demonstracyjnymi. Żadnych makiet, żadnego montażu.',
  'screens.light': 'Motyw jasny',
  'screens.dark': 'Motyw ciemny',
  'screens.member': 'Przestrzeń pracownika',
  'screens.admin': 'Administracja i zarządzanie',
  'screens.modules': 'Moduły opcjonalne',
  'screens.open': 'Powiększ',
  'screens.close': 'Zamknij',
  'screens.prev': 'Poprzedni',
  'screens.next': 'Następny',
  'security.title': 'Bezpieczeństwo nie jest płatnym dodatkiem',
  'security.lede': 'Wszystko poniżej jest w produkcie, w każdym planie — także w bezpłatnym.',
  'security.1.title': 'Wzmocnione uwierzytelnianie',
  'security.1.body': 'Hasła haszowane (bcrypt), polityka złożoności, blokada po powtórzonych błędach, drugi składnik TOTP z kodami zapasowymi, sesje odwoływalne pojedynczo lub wszystkie naraz.',
  'security.2.title': 'Zapieczętowany dziennik audytu',
  'security.2.body': 'Każdy wpis nosi odcisk poprzedniego. Zmiana wiersza albo usunięcie jednego ze środka rozrywa łańcuch dokładnie w tym miejscu, a weryfikacja mówi, którego. Czego nie robi: nie powstrzyma przepisania przez tego, kto trzyma serwer — czyni je widocznym.',
  'security.3.title': 'Dane osobowe',
  'security.3.body': 'Rejestr czynności przetwarzania, prawo dostępu eksportowane źródło po źródle, usunięcie, które zachowuje to, co prawo każe zachować, i tak mówi. Konto jest anonimizowane zamiast kasowane, żeby zapisy, które się do niego odwołują, pozostały spójne.',
  'security.4.title': 'Wewnętrzny kanał zgłoszeń',
  'security.4.body': 'We Francji obowiązkowy od pięćdziesięciu pracowników. Treść szyfrowana w bazie, czytelna wyłącznie dla wyznaczonych osób zaufania — nie dla administratorów, bo zgłoszenie może dotyczyć któregoś z nich. Anonimowe śledzenie kodem, bez konta i bez logowania zdarzeń.',
  'security.5.title': 'Zweryfikowane kopie zapasowe',
  'security.5.body': 'Archiwum co godzinę, kontrola spójności przez manifest, odtworzenie przywracające bazę i pliki, wynoszenie kopii przez FTPS lub Google Drive oraz ostrzeżenie dla administratorów przy niepowodzeniu.',
  'security.6.title': 'Zaszyfrowane sekrety',
  'security.6.body': 'Hasła usług zewnętrznych, tokeny API, sekrety webhooków: szyfrowane AES-256-GCM, nigdy więcej niepokazywane jawnie, nieczytelne po naruszeniu.',
  'security.hostTitle': 'SaaS albo u Ciebie',
  'security.hostBody': 'W SaaS hostujemy w Europie, z kopiami zapasowymi. W planach płatnych możliwy jest hosting lokalny: instalujesz na swoim serwerze, baza nigdy nie opuszcza Twoich murów, a aktualizacje dostajesz te same. Wystarczy jedna maszyna — Node 22 i SQLite, żadnej zewnętrznej bazy do administrowania.',
  'security.limitsTitle': 'Czego nie udajemy',
  'security.limitsBody': 'Podpis elektroniczny jest zwykły, nie kwalifikowany w rozumieniu eIDAS. Sejf pieczętuje i datuje dokumenty, ale znacznik czasu skuteczny wobec osób trzecich wymaga urzędu certyfikacji. Żadnych wysyłek do urzędów: oprogramowanie przygotowuje dane, ich złożenie pozostaje sprawą księgowego. Piszemy to tutaj, a nie po podpisaniu umowy.',
  'pricing.title': 'Czytelny cennik, bez niespodzianek',
  'pricing.lede': 'Jedna cena, za pracownika i za miesiąc, aby prowadzić całą firmę. Żadnych modułów à la carte, żadnych dopłat za funkcję: cały produkt jest w każdym planie.',
  'pricing.perMonth': '/ mies.',
  'pricing.free': 'Bezpłatnie',
  'pricing.custom': 'Na miarę',
  'pricing.vat': 'Ceny netto. Bez zobowiązania czasowego w planach miesięcznych.',
  'pricing.cta': 'Zacznij',
  'pricing.ctaCustom': 'Napisz do nas',
  'pricing.popular': 'Najczęściej wybierany',
  'pricing.p1.name': 'Bezpłatnie',
  'pricing.p1.for': 'Poniżej 5 pracowników',
  'pricing.p1.body': 'Cały produkt, za darmo, bez ograniczenia czasu i bez okrojonych funkcji. Plan dla młodej firmy, stowarzyszenia albo kancelarii, która zaczyna.',
  'pricing.p2.name': 'Abonament',
  'pricing.p2.for': 'Od 5 do 250 pracowników',
  'pricing.p2.body': '5 € za pracownika miesięcznie, malejąco od dwustu pięćdziesięciu. Płacisz za zatrudnienie, które masz, a nie za to, które może kiedyś będziesz mieć.',
  'pricing.p3.name': 'Bez limitu',
  'pricing.p3.for': 'Zatrudnienie bez ograniczeń',
  'pricing.p3.body': '1500 € miesięcznie, bez względu na liczbę pracowników. Powyżej trzystu osób to już taniej niż stawka za pracownika — i cena przestaje się ruszać.',
  'pricing.p4.name': 'Licencja dożywotnia',
  'pricing.p4.for': 'Płatność jednorazowa',
  'pricing.p4.body': '10 000 € raz. Żadnego abonamentu, żadnego limitu czasu, żadnego pułapu zatrudnienia. Oprogramowanie jest Twoje tak długo, jak chcesz go używać.',
  'pricing.tableTitle': 'Co obejmuje każdy plan',
  'pricing.col.feature': '',
  'pricing.yes': 'W cenie',
  'pricing.no': 'Nie',
  'pricing.option': 'Opcjonalnie',
  'pricing.f.allSpaces': '35 przestrzeni i 7 modułów',
  'pricing.f.languages': '16 języków i 3 palety',
  'pricing.f.security': 'Pełne bezpieczeństwo, zapieczętowany dziennik, RODO',
  'pricing.f.updates': 'Aktualizacje w cenie',
  'pricing.f.saas': 'Hosting SaaS w Europie',
  'pricing.f.local': 'Lokalny hosting Twoich danych',
  'pricing.f.backupOff': 'Wynoszenie kopii zapasowych',
  'pricing.f.support': 'Wsparcie',
  'pricing.f.supportMail': 'Mailowe',
  'pricing.f.supportPrio': 'Priorytetowe',
  'pricing.f.supportDedicated': 'Dedykowany opiekun',
  'pricing.f.supportCommunity': 'Dokumentacja',
  'pricing.f.migration': 'Przeniesienie Twoich danych',
  'pricing.f.sla': 'Zobowiązanie serwisowe (SLA)',
  'pricing.f.api': 'API odczytu i webhooki',
  'pricing.f.multisite': 'Kilka lokalizacji, kilka podmiotów',
  'pricing.countTitle': 'Jak liczymy pracowników',
  'pricing.countBody': 'Konta aktywne, w tym freelancerzy i stażyści, bez administratorów. Konto zamknięte już się nie liczy, nawet jeśli zachowuje dostęp do swojego sejfu. Przekraczasz próg? Zmiana następuje od kolejnego miesiąca, nigdy wstecz — i w dół działa tak samo.',
  'faq.title': 'Najczęstsze pytania',
  'faq.q1': 'Czy plan bezpłatny jest ograniczony czasowo?',
  'faq.a1': 'Nie. Poniżej pięciu pracowników produkt jest bezpłatny bez ograniczenia czasu i bez okrojonych funkcji. Wolimy małą firmę, która rośnie razem z oprogramowaniem, niż wersję próbną gasnącą po trzydziestu dniach.',
  'faq.q2': 'Czy mogę trzymać dane na własnym serwerze?',
  'faq.a2': 'Tak, w planach płatnych. Oprogramowanie działa na jednej maszynie z Node 22 i SQLite: bez serwera bazy danych i bez usług zewnętrznych. Baza, dokumenty i kopie zostają u Ciebie.',
  'faq.q3': 'Co się stanie, jeśli zrezygnuję?',
  'faq.a3': 'Eksportujesz całą instancję do JSON, razem z dokumentami, z konsoli administracyjnej. Nic nie jest zatrzymywane: to Twoja baza i odchodzi z Tobą w czytelnym formacie.',
  'faq.q4': 'Czy zastępuje to moje biuro rachunkowe?',
  'faq.a4': 'Nie. Księgowość podwójna, płace i VAT służą do prowadzenia zapisów i przygotowania dokumentów. Nie ma ani sprawozdania finansowego, ani wysyłki elektronicznej: eksport zasila Twoje biuro.',
  'faq.q5': 'Czy trzeba szkolić zespoły?',
  'faq.a5': 'Przestrzeń pracownika tłumaczy się sama: urlopy, dokumenty, grafik, książka adresowa. Przestrzenie administracyjne wymagają pół dnia wdrożenia, które prowadzimy w planach Firma i Na miarę.',
  'faq.q6': 'Czy mogę włączyć tylko część produktu?',
  'faq.a6': 'Tak. Siedem modułów — księgowość, płace, e-faktury, magazyn i zakupy, finanse, środki trwałe, CRM — jest domyślnie wyłączonych i włącza się je pojedynczo. Dopóki moduł jest wyłączony, jego adresy odpowiadają 404.',
  'faq.q7': 'Jak wygląda przeniesienie moich obecnych danych?',
  'faq.a7': 'Import masowy z CSV sprawdza każdy wiersz przed zapisem i nie zapisuje nic, jeśli choć jeden wiersz jest błędny. W planach Firma i Na miarę przygotowujemy pliki razem z Tobą.',
  'faq.q8': 'A integracje z naszymi narzędziami?',
  'faq.a8': 'W cenie jest REST API do odczytu z zakresami i podpisane webhooki wychodzące. Do konkretnych wymian — kadry, ERP, fakturowanie — służy plan Na miarę.',
  'contact.title': 'Porozmawiajmy o Twojej firmie',
  'contact.lede': 'Prezentacja trwa trzydzieści minut i dotyczy Twoich przypadków, a nie wymyślonych danych. Napisz, co chcesz rozwiązać.',
  'contact.emailLabel': 'Mailem',
  'contact.demoTitle': 'Poproś o prezentację',
  'contact.demoBody': 'Podaj imię, firmę, liczbę pracowników i to, co dziś sprawia kłopot. Odpowiadamy w ciągu jednego dnia roboczego.',
  'contact.write': 'Napisz do zespołu',
  'contact.docTitle': 'Przeczytaj dokumentację',
  'contact.docBody': 'Strona dokumentacji opisuje instalację, konfigurację, bezpieczeństwo, API i pełny słownik w szesnastu językach.',
  'contact.docCta': 'Otwórz dokumentację',
  'contact.selfTitle': 'Zainstaluj samodzielnie',
  'contact.selfBody': 'Node 22, jedna maszyna, pięć minut: kreator tworzy bazę, konto administratora i sprawdza środowisko.',
  'contact.selfCta': 'Zobacz wymagania',
  'cta.title': 'Zacznij za darmo, zmień plan, gdy urośniesz',
  'cta.body': 'Poniżej pięciu pracowników wszystko jest bezpłatne. Powyżej 5 € za pracownika miesięcznie albo 10 000 € raz za licencję dożywotnią. Bez karty, żeby spróbować.',
  'cta.primary': 'Utwórz moją instancję',
  'cta.secondary': 'Porozmawiaj z kimś',
  'foot.product': 'Produkt',
  'foot.company': 'O nas',
  'foot.resources': 'Zasoby',
  'foot.legal': 'Informacje prawne',
  'foot.docs': 'Dokumentacja',
  'foot.status': 'Co jest objęte',
  'foot.rights': 'Wszelkie prawa zastrzeżone.',
  'foot.madeWith': 'Node 22 · Express · SQLite. Żadnej zbędnej zależności.',
  'foot.langTitle': 'Ta strona istnieje w szesnastu językach',
  'dom.socle.title': 'Fundament i organizacja',
  'dom.socle.lede': 'To, co trzyma resztę: konta, przypisania i słownictwo wspólne wszystkim przestrzeniom.',
  'dom.socle.items': [
    'Konta i łączone role: administrator, HR, finanse, informatyka, osoba zaufania ds. zgłoszeń',
    'Przełożony wynikający z rzeczywistej struktury, nigdy nadawany ręcznie',
    'Działy i zespoły, kilku przełożonych na obszar, przypisania odczytywane przy każdym żądaniu',
    'Graficzny schemat organizacyjny wraz z kadrą i osoby nigdzie nieprzypisane',
    'Książka adresowa z wyszukiwaniem i filtrami, widoczność sterowana wyłącznie przez administrację',
    'Poczta wewnętrzna i służbowy adres konfigurowany przez administrację',
    'Wyszukiwanie globalne rozdzielone u źródła: czego nie wolno Ci zobaczyć, tego się nie szuka',
    'Centrum powiadomień dla każdej osoby, z potwierdzeniem odczytu',
    'Import masowy CSV: kontrolowany podgląd, zapis wszystko albo nic',
    'Kreator instalacji, ustawienia instancji, siedem modułów do włączenia',
    '16 języków, 3 palety, motyw jasny/ciemny/systemowy, interfejs responsywny',
  ],
  'dom.espace.title': 'Przestrzeń pracownika',
  'dom.espace.lede': 'Strona, którą każdy otwiera rano: to, co jego dotyczy, i nic więcej.',
  'dom.espace.items': [
    'Pulpit osobisty: przełożony, aktualności, wnioski, dokumenty do potwierdzenia',
    'Urlopy, wolne, nieobecności i praca zdalna: dni robocze liczone, weekendy pomijane',
    'Aktualne saldo urlopu, historia uzasadnionych korekt',
    'Paski wypłaty dostępne i przechowywane pięćdziesiąt lat w sejfie',
    'Kalendarz osobisty i wspólny kalendarz zespołu',
    'Grafik tygodnia, dyżury, pogotowie',
    'Przydzielone narzędzia z własnym loginem — żadne obce hasło nie jest przechowywane',
    'Profil: zdjęcie, opis, telefon, język, hasło, zamknięcie wszystkich sesji',
    'Rejestracja czasu stoperem dla freelancerów, tylko jedna otwarta naraz',
    'Oświadczenie o interesach i prezentach, widoczne wyłącznie dla siebie',
  ],
  'dom.rh.title': 'Kadry i HR',
  'dom.rh.lede': 'Teczka pracownika, od przyjścia do odejścia, wraz z terminami, które za sobą niesie.',
  'dom.rh.items': [
    'Zatwierdzanie wniosków z odjęciem salda, odmowa z uzasadnieniem, anulowanie zwracające dni',
    'Paski wypłaty: tworzenie, śledzenie wypłaty, generowanie zbiorcze',
    'Dokumenty firmowe z imiennym potwierdzeniem odbioru',
    'Szkolenia: katalog, terminy, zapisy, koszt i czas trwania',
    'Rozmowy roczne: kampania, scenariusz, protokół',
    'Przyjęcie i odejście: prowadzone listy kontrolne, właściciel i termin dla każdego zadania',
    'Kompetencje i uprawnienia z datą odnowienia i wcześniejszym ostrzeżeniem',
    'Rozmowy indywidualne: wspólne podsumowanie, notatki przełożonego trzymane osobno',
    'Sejf cyfrowy dostępny także po odejściu, dokumenty zapieczętowane odciskiem',
    'Prosty podpis elektroniczny: uporządkowany obieg, odcisk, pieczęć, zaświadczenie',
    'Umowy terminowe: konto zamyka się samo w wyznaczonym dniu',
  ],
  'dom.talent.title': 'Rekrutacja i talenty',
  'dom.talent.lede': 'Od zgłoszeń do pierwszego dnia, bez arkusza po drodze.',
  'dom.talent.items': [
    'Ogłoszenia i zgłoszenia śledzone etapami',
    'Przyjmowanie CV: PDF, DOCX lub tekst, zapisywane poza repozytorium',
    'Wyciąganie treści i przeszukiwalna baza CV',
    'Ważone kryteria, punktacja, próg, ranking zgłoszeń',
    'Przyjęty kandydat przechodzi prosto do ścieżki wdrożenia',
    'Ankiety wewnętrzne i barometr nastrojów, anonimowe z założenia',
    'Poniżej pięciu odpowiedzi żaden wynik nie jest pokazywany',
  ],
  'dom.sst.title': 'BHP i rada pracowników',
  'dom.sst.lede': 'Obowiązki, które trzeba prowadzić na piśmie i które same się przypominają.',
  'dom.sst.items': [
    'Ocena ryzyka: stanowiska, zagrożenia, punktacja, środki, datowany przegląd',
    'Rejestr wypadków przy pracy i zdarzeń potencjalnie wypadkowych, dni absencji',
    'Środki ochrony: wydanie imienne, okres ważności, wymiana',
    'Badania lekarskie: wstępne, okresowe, kontrolne, na wniosek',
    'Rada: wybory, lista wyborców, głosowanie anonimowe, mandaty i ich wygaśnięcie',
    'Posiedzenia organu, świadczenia i korzyści dla pracowników',
    'Przestrzeń zarządzania zamyka się sama z końcem kadencji',
  ],
  'dom.finance.title': 'Finanse i administracja',
  'dom.finance.lede': 'Kontrahenci, umowy, pieniądze, które wpływają, i te, które wypływają.',
  'dom.finance.items': [
    'Klienci i dostawcy, pełna karta: kontakty, umowy, faktury',
    'Umowy, a zwłaszcza wypowiedzenia: ostateczna data jest liczona i zgłaszana',
    'Faktury w obie strony, kwota brutto liczona, opóźnienie z terminu płatności',
    'Budżety według działu i roku obrotowego, zużycie agregowane automatycznie',
    'Rozliczenia wydatków: złożenie, zatwierdzenie, zwrot — nigdy jedno bez drugiego',
    'Dokumenty zgodności kontrahentów, datowane i zgłaszane czterdzieści pięć dni wcześniej',
    'Punktowane oceny dostawców: liczy się ostatni przegląd, nie średnia',
    'Wiele walut z kursem zamrożonym przy wystawieniu każdego dokumentu',
    'Fakturowanie cykliczne: abonament to forma, faktura to dokument',
    'Automatyczne odczytywanie faktur przychodzących i pobieranie IMAP skrzynki księgowej',
  ],
  'dom.compta.title': 'Księgowość, płace i VAT',
  'dom.compta.lede': 'Moduły domyślnie wyłączone, które włącza się wtedy, gdy są potrzebne.',
  'dom.compta.items': [
    'Księgowość podwójna: plan kont, dzienniki, zestawienie obrotów, księga główna',
    'Niezbilansowany zapis jest odrzucany, a komunikat mówi o ile',
    'Faktura staje się zapisem jednym kliknięciem; eksport CSV dla biura rachunkowego',
    'Silnik płacowy: konfigurowalne stawki, brutto na netto, część pracodawcy, koszt pracodawcy',
    'Szczegółowy pasek wypłaty wiersz po wierszu, generowanie zbiorcze, symulator',
    'Deklaracje VAT: należny, naliczony, podział wg stawek, kwota do przeniesienia',
    'Złożona deklaracja nie jest przeliczana: to dokument, a nie pulpit',
    'E-faktury: kontrola EN 16931 i eksport XML CII',
    'Finanse: rachunki, operacje, uzgodnienia, prognoza na dwanaście tygodni',
    'Środki trwałe: amortyzacja liniowa i degresywna, wartość netto',
  ],
  'dom.achats.title': 'Zakupy, magazyn i windykacja',
  'dom.achats.lede': 'Co zamówiono, co przyszło, co zafakturowano — i co nam się należy.',
  'dom.achats.items': [
    'Wnioski zakupowe zatwierdzane przez przełożonego, a powyżej progu przez finanse',
    'Zamówienia, przyjęcia i uzgodnienie trójstronne: zamówione, przyjęte, zafakturowane',
    'Przyjęcie większej ilości niż zamówiona jest odrzucane; różnica w fakturze jest nazwana, nie blokowana',
    'Artykuły, ruchy, próg alarmowy: stan to suma ruchów',
    'Pozycja powiązana z artykułem trafia do magazynu w chwili przyjęcia',
    'Struktura wiekowa należności według przedziałów opóźnienia',
    'Stopniowane wezwania: przypomnienie, ponaglenie, wezwanie do zapłaty, zależnie od tego, co już wysłano',
    'Każde wezwanie zapisane wraz z poziomem i datą',
  ],
  'dom.projets.title': 'Projekty, czas i rentowność',
  'dom.projets.lede': 'Wiedzieć, na jakim etapie jest projekt i ile naprawdę kosztował.',
  'dom.projets.items': [
    'Projekty powiązane z klientem, działem, zespołem i osobą odpowiedzialną',
    'Datowane kamienie milowe i zadania w kolumnach według statusu, z priorytetem i szacunkiem',
    'Czas przypisany do projektu i zadania, najwyżej 24 h na wpis',
    'Rentowność: godziny, koszt wg stawki godzinowej, pozostała marża, zużyta część budżetu',
    'Trzy kręgi uprawnień: administracja, osoba odpowiedzialna, członkowie',
    'Czas na osobę i kondycja projektów na pulpicie zarządu',
  ],
  'dom.support.title': 'Wsparcie i wiedza',
  'dom.support.lede': 'Zgłoszenia wewnętrzne i klientów w jednym obiegu, i odpowiedzi, które zostają.',
  'dom.support.items': [
    'Zgłoszenia wewnętrzne i klientów, priorytet, źródło, przypisanie',
    'Termin pierwszej odpowiedzi wynikający z priorytetu, przeliczany od otwarcia',
    'Notatki wewnętrzne niewidoczne dla zgłaszającego i nieliczone jako odpowiedź',
    'Rozdział według kategorii: zgłoszenie kadrowe nie opuszcza działu kadr',
    'Baza wiedzy według kategorii, wyszukiwanie pełnotekstowe, regulowany zasięg',
    'Wskaźniki: zgłoszenia otwarte, opóźnione, średni czas',
  ],
  'dom.ops.title': 'Operacje i administracja',
  'dom.ops.lede': 'Grafik, jakość, sale, pojazdy, recepcja.',
  'dom.ops.items': [
    'Grafik na osobę i dzień: zmiany, dyżury, pogotowie, praca zdalna',
    'Nakładanie się albo już przyznana nieobecność: wpis jest odrzucany przy tworzeniu',
    'Powtarzalne rotacje, zmiany nocne, publikacja tygodnia',
    'Kto jest teraz pod telefonem, wraz z numerem',
    'Jakość: niezgodności, przyczyny źródłowe, działania korygujące i sprawdzenie skuteczności',
    'Audyty wewnętrzne: ustalenia, podsumowanie, ustalenie podniesione do niezgodności',
    'Sprzęt przydzielony i zwrócony, z historią posiadaczy',
    'Sale i rezerwacje, nakładanie odrzucane ze wskazaniem, kto zajmuje',
    'Flota: serwis, przegląd, ubezpieczenie, szkody, przebieg',
    'Recepcja: rejestr gości, lista obecnych w budynku, poczta przychodząca i wychodząca',
  ],
  'dom.direction.title': 'Zarząd i ład korporacyjny',
  'dom.direction.lede': 'Na co patrzy zarząd i co postanawia.',
  'dom.direction.items': [
    'Pulpit: zatrudnienie, nieobecni, zafakturowano, marża, koszty płac, gotówka, obciążenie wsparcia',
    'Cele i kluczowe wyniki, każdy we własnej skali, także malejącej',
    'Posiedzenia: zwołanie, porządek obrad, odnotowana obecność, protokół',
    'Rejestr decyzji wraz z uzasadnieniem — tym, czego szuka się dwa lata później',
    'Powierzone działania z właścicielem i terminem, powiązane ze swoją decyzją',
    'Rejestr ryzyk: ocena brutto i rezydualna, macierz 5 × 5, postępowanie, przegląd',
    'Wydarzenia firmowe: pojemność, automatyczna lista rezerwowa, lista obecności, budżet',
    'Terminy ze wszystkich przestrzeni w jednej posortowanej liście',
  ],
  'dom.it.title': 'Informatyka i rozwój',
  'dom.it.lede': 'Park oprogramowania, dostępy, incydenty i to, co wdraża zespół.',
  'dom.it.items': [
    'Park oprogramowania: stanowiska traktowane jak ograniczenie, koszt roczny, odnowienia',
    'Przegląd dostępów: najpierw konta zamknięte, potem uprawnienia administracyjne',
    'Incydenty informatyczne z godzinami i rzeczywiście mierzonym średnim czasem przywrócenia',
    'Katalog usług: krytyczność, właściciel, repozytorium, dokumentacja',
    'Rejestr wdrożeń według środowiska i wskaźniki wdrożeń',
    'Kopie zapasowe: archiwum co godzinę, sprawdzona spójność, odtworzenie, wynoszenie',
    'REST API do odczytu z zakresami, podpisane webhooki wychodzące',
    'Pełny eksport instancji do JSON, razem z dokumentami, bez sekretów',
  ],
  'dom.conformite.title': 'Zgodność, sprawy spółki i dane osobowe',
  'dom.conformite.lede': 'To, co firma musi umieć udowodnić, prowadzone na bieżąco.',
  'dom.conformite.items': [
    'Księga udziałów: stan wyliczany z ruchów, zbycie zapisane w dwóch nogach',
    'Mandaty w organach z okresem, odwołaniem i wcześniej zgłaszanym końcem',
    'Zgromadzenia wspólników: kworum w udziałach, uchwały, głosy, protokół',
    'Pełnomocnictwa: zakres, limit kwotowy, okres, zgłaszany koniec',
    'Konflikty interesów i prezenty: każdy zgłasza za siebie, administracja bada',
    'Szyfrowany wewnętrzny kanał zgłoszeń, wyznaczone osoby zaufania, anonimowe śledzenie kodem',
    'Dziennik audytu z czasem, eksportowalny i zapieczętowany łańcuchem odcisków',
    'RODO: rejestr czynności, eksportowane prawo dostępu, uzasadnione usuwanie',
    'Konfigurowalne obiegi akceptacji: formularze, progi, akceptujący według funkcji',
  ],
  'shot.membre-espace': 'Przestrzeń pracownika',
  'shot.membre-equipe': 'Przestrzeń przełożonego',
  'shot.membre-demandes': 'Wnioski wewnętrzne',
  'shot.membre-agenda': 'Kalendarz osobisty i wspólny',
  'shot.membre-salles': 'Sale i rezerwacje',
  'shot.membre-messagerie': 'Poczta wewnętrzna',
  'shot.membre-connaissances': 'Baza wiedzy',
  'shot.membre-coffre-fort': 'Sejf cyfrowy',
  'shot.membre-profil': 'Profil i bezpieczeństwo konta',
  'shot.membre-juridique-membre': 'Moje oświadczenia',
  'shot.annuaire': 'Książka adresowa firmy',
  'shot.organigramme': 'Schemat organizacyjny',
  'shot.connexion': 'Ekran logowania',
  'shot.pilotage': 'Pulpit zarządu',
  'shot.admin': 'Konsola administracyjna',
  'shot.rh': 'Kadry i HR',
  'shot.gestion': 'Administracja i finanse',
  'shot.direction': 'Zarząd i ład korporacyjny',
  'shot.projets': 'Projekty, kamienie milowe i rentowność',
  'shot.support': 'Wsparcie i zgłoszenia',
  'shot.planning': 'Grafik, rotacje i dyżury',
  'shot.qualite': 'Jakość i audyty wewnętrzne',
  'shot.sante-securite': 'Bezpieczeństwo i higiena pracy',
  'shot.informatique': 'Park oprogramowania i dostępy',
  'shot.developpement': 'Usługi i wdrożenia',
  'shot.evenements': 'Wydarzenia firmowe',
  'shot.juridique': 'Sprawy spółki i zgodność',
  'shot.alertes': 'Kanał zgłoszeń wewnętrznych',
  'shot.securite': 'Konsola bezpieczeństwa',
  'shot.rgpd': 'Dane osobowe',
  'shot.parapheur': 'Teczka podpisów',
  'shot.sauvegardes': 'Kopie i odtwarzanie',
  'shot.comptabilite': 'Księgowość podwójna',
  'shot.paie': 'Silnik płacowy',
  'shot.tresorerie': 'Finanse i prognoza',
  'shot.immobilisations': 'Środki trwałe i amortyzacja',
  'shot.crm': 'CRM handlowy',
  'shot.stock': 'Magazyn i zakupy',
  'shot.pilotage-sombre': 'Zarząd — motyw ciemny',
  'shot.membre-espace-sombre': 'Przestrzeń pracownika — motyw ciemny',
  'shot.gestion-sombre': 'Administracja — motyw ciemny',
  'shot.projets-sombre': 'Projekty — motyw ciemny',
  'shot.juridique-sombre': 'Sprawy spółki — motyw ciemny',
  'shot.securite-sombre': 'Bezpieczeństwo — motyw ciemny',
  'tour.pilotage': 'Zatrudnienie, zafakturowano, marża, gotówka, wsparcie: to, na co patrzy zarząd, na jednej stronie. Kreska oznacza brak danych — nigdy zero, które uchodziłoby za liczbę.',
  'tour.membre-espace': 'Strona, którą każdy otwiera rano: jego przełożony, aktualności, które go dotyczą, jego wnioski, dokumenty do potwierdzenia, jego narzędzia i loginy.',
  'tour.rh': 'Wnioski do rozpatrzenia, salda, paski wypłat, dokumenty, szkolenia, rozmowy: teczka pracownika jest prowadzona tutaj, a terminy same wychodzą na wierzch.',
  'tour.gestion': 'Kontrahenci, umowy i wypowiedzenia, faktury w obie strony, budżety działów, wydatki, windykacja. Zużycie budżetu sumuje się samo.',
  'tour.projets': 'Kamienie milowe, zadania w kolumnach, spędzony czas i rentowność wobec budżetu. Koszt nie jest wpisywany: wynika z godzin i stawki godzinowej.',
  'tour.juridique': 'Kapitał, mandaty w organach, zgromadzenia i protokoły, pełnomocnictwa, oświadczenia o interesach. To, co firma musi umieć udowodnić, prowadzone na bieżąco.',
  'pricing.perEmployee': '5 € za pracownika miesięcznie',
  'pricing.perEmployeeShort': 'za pracownika / mies.',
  'pricing.argTitle': 'Pięć euro za pracownika, za wszystko',
  'pricing.argBody': 'Narzędzie kadrowe, program księgowy, menedżer projektów, system zgłoszeń, sejf na paski wypłat: pięć subskrypcji po 8 lub 15 € za użytkownika, pięć baz, które ze sobą nie rozmawiają, pięć faktur. Toutadmin zastępuje cały ten stos w cenie najtańszego z nich — a dane są wreszcie w jednym miejscu.',
  'pricing.gridTitle': 'Siatka, według zatrudnienia',
  'pricing.gridLede': 'Cena idzie za zatrudnieniem i niczym więcej. Powyżej stu pracowników stawka na osobę spada, a powyżej dwustu pięćdziesięciu przestaje rosnąć w ogóle.',
  'pricing.col.headcount': 'Zatrudnienie',
  'pricing.col.monthly': 'Miesięcznie',
  'pricing.col.perEmployee': 'Na pracownika',
  'pricing.unlimited': 'Bez limitu',
  'pricing.upTo': 'Do {count} pracowników',
  'pricing.under': 'Poniżej {count} pracowników',
  'pricing.once': 'jednorazowo',
  'pricing.lifetimeTitle': 'Po co licencja dożywotnia',
  'pricing.lifetimeBody': 'Dziesięć tysięcy euro raz, bez abonamentu i bez ograniczenia czasu: ta sama instancja, te same aktualizacje, żadnego pułapu zatrudnienia. Przy stu pracownikach zwraca się w dwadzieścia miesięcy, bez limitu zatrudnienia w siedem. To oferta dla tych, którzy wolą inwestycję od stałej pozycji w kosztach — i którzy nie chcą od nikogo zależeć, żeby dalej pracować.',
  'faq.q9': 'Co jeśli zatrudnienie zmieni się w ciągu roku?',
  'faq.a9': 'Cena idzie za nim w obie strony, od kolejnego miesiąca i nigdy wstecz. Zatrudnienie, które przenosi Cię przez próg, rozliczamy w następnym miesiącu; odejście, które sprowadza Cię niżej — tak samo. Nikt nie płaci za zamknięte konta.',
  'faq.q10': 'Czy licencja dożywotnia daje prawo do aktualizacji?',
  'faq.a10': 'Tak, bez ograniczenia czasu: na tym polega słowo «dożywotnia». Dostajesz te same wersje co plany miesięczne i możesz trzymać bazę u siebie. Licencja nie obejmuje wsparcia priorytetowego, które pozostaje osobną usługą.',
};
