/* pt — traduit du français. Toute clé du français doit exister ici :
   le build refuse de construire une langue incomplète. */
module.exports = {
  'locale.name': 'Português',
  'site.name': 'Toutadmin',
  'site.tagline': 'O CMS que administra toda a empresa',
  'nav.product': 'Produto',
  'nav.features': 'Funcionalidades',
  'nav.screens': 'Os ecrãs',
  'nav.security': 'Segurança',
  'nav.pricing': 'Preços',
  'nav.contact': 'Contacto',
  'nav.demo': 'Pedir uma demo',
  'nav.menu': 'Menu',
  'nav.language': 'Idioma',
  'nav.theme': 'Tema',
  'nav.themeLight': 'Claro',
  'nav.themeDark': 'Escuro',
  'nav.themeSystem': 'Sistema',
  'hero.eyebrow': 'Software de gestão empresarial',
  'hero.title': 'Toda a sua empresa,\nnum único software.',
  'hero.lede': 'Pessoal, recursos humanos, finanças, operações, governação, conformidade, serviços gerais. Trinta e cinco espaços que falam entre si, uma única base de dados, nenhuma aplicação para colar. Em dezasseis idiomas, e 5 € por colaborador e por mês para gerir tudo.',
  'hero.ctaPrimary': 'Experimentar grátis',
  'hero.ctaSecondary': 'Ver as funcionalidades',
  'hero.note': 'Sem cartão bancário. Os seus dados continuam seus, e podem ficar consigo.',
  'hero.badge1': 'SaaS pronto em cinco minutos',
  'hero.badge2': 'ou alojado por si',
  'hero.badge3': 'RGPD desde a raiz',
  'stats.title': 'O que o produto cobre, em números',
  'stats.spaces': 'espaços de trabalho',
  'stats.spacesNote': 'do espaço do colaborador à vida societária',
  'stats.languages': 'idiomas de interface',
  'stats.languagesNote': 'árabe incluído, página espelhada',
  'stats.tests': 'testes de integração',
  'stats.testsNote': 'executados em cada entrega',
  'stats.modules': 'módulos ativáveis',
  'stats.modulesNote': 'contabilidade, salários, tesouraria, CRM…',
  'stats.deps': 'serviços externos necessários',
  'stats.depsNote': 'uma máquina, uma base de dados, mais nada',
  'stats.keys': 'etiquetas traduzidas',
  'stats.keysNote': 'até às caixas de confirmação',
  'pillars.title': 'Porquê Toutadmin em vez de cinco ferramentas coladas',
  'pillars.lede': 'Cinco programas que não falam entre si custam mais do que um só e fazem perder o que importa: a visão de conjunto. O Toutadmin parte do contrário — uma base de dados, espaços e direitos.',
  'pillars.1.title': 'Um só lugar, uma só verdade',
  'pillars.1.body': 'O orçamento de um departamento agrega sozinho as suas faturas e as despesas aprovadas dos seus membros. Uma receção de encomenda entra em armazém no mesmo gesto. Ninguém volta a digitar nada, por isso ninguém se contradiz.',
  'pillars.2.title': 'As permissões não são decorativas',
  'pillars.2.body': 'Cada rota traz a sua verificação no servidor, e as afetações são relidas a cada pedido. Uma saída corta o acesso de imediato, não quando o cookie expira. Aquilo que não pode ver nem sequer é procurado.',
  'pillars.3.title': 'Os prazos vêm ter consigo',
  'pillars.3.body': 'Pré-aviso de contrato, habilitação a renovar, exame médico, inspeção do veículo, mandato social, declaração de um fornecedor: um só motor reúne tudo e avisa a pessoa certa, uma vez, sem duplicados.',
  'pillars.4.title': 'Cada ecrã diz o que não faz',
  'pillars.4.body': 'Um módulo mostra o seu limite quando se ativa, não no fundo de um manual. Preferimos uma frase honesta a uma caixa assinalada: é o que evita as más surpresas ao terceiro mês.',
  'pillars.5.title': 'Dezasseis idiomas, a sério',
  'pillars.5.body': 'Não apenas o ecrã inicial: os estados, as mensagens de erro, as caixas de confirmação. O árabe espelha a página inteira, porque a folha de estilos só usa propriedades lógicas.',
  'pillars.6.title': 'Os seus dados, consigo se quiser',
  'pillars.6.body': 'Em SaaS está tudo pronto em cinco minutos. Nos planos pagos também pode alojar a base no seu próprio servidor: mesmo software, mesmas atualizações, dados dentro das suas paredes.',
  'tour.title': 'Software denso, não um brinquedo',
  'tour.lede': 'Ecrãs feitos para quem os tem abertos oito horas por dia: informação de relance, sem janelas modais inúteis, e o mesmo vocabulário em todo o lado.',
  'tour.hint': 'Clique num separador para mudar de ecrã.',
  'tour.all': 'Ver os 40 ecrãs',
  'features.title': 'Tudo o que o Toutadmin sabe fazer',
  'features.lede': 'A lista completa, domínio a domínio. Cada linha corresponde a código entregue e testado, não a uma intenção.',
  'features.legend': 'As funções marcadas «módulo» ativam-se na consola quando forem precisas.',
  'features.module': 'módulo',
  'features.seeAll': 'Ver a lista completa',
  'features.intro': 'Catorze domínios, mais de cento e trinta funções.',
  'features.ctaTitle': 'Falta alguma coisa?',
  'features.ctaBody': 'Diga-nos. O produto avança por lotes, e os pedidos das empresas que o usam passam à frente.',
  'screens.title': 'Os ecrãs, sem retoques',
  'screens.lede': 'Todas as capturas deste site saem de uma instância real preenchida com dados de demonstração. Sem maquetas, sem montagens.',
  'screens.light': 'Tema claro',
  'screens.dark': 'Tema escuro',
  'screens.member': 'Espaço do colaborador',
  'screens.admin': 'Administração e direção',
  'screens.modules': 'Módulos opcionais',
  'screens.open': 'Ampliar',
  'screens.close': 'Fechar',
  'screens.prev': 'Anterior',
  'screens.next': 'Seguinte',
  'security.title': 'A segurança não é uma opção paga',
  'security.lede': 'Tudo o que se segue está no produto, seja qual for o plano — incluindo o gratuito.',
  'security.1.title': 'Autenticação reforçada',
  'security.1.body': 'Palavras-passe cifradas (bcrypt), política de complexidade, bloqueio após falhas repetidas, dois fatores TOTP com códigos de recuperação, sessões revogáveis uma a uma ou todas de uma vez.',
  'security.2.title': 'Registo de auditoria selado',
  'security.2.body': 'Cada entrada leva a impressão da anterior. Alterar uma linha, ou retirar uma do meio, parte a cadeia nesse ponto, e a verificação diz qual. O que não faz: impedir a reescrita por quem controla o servidor — torna-a visível.',
  'security.3.title': 'Dados pessoais',
  'security.3.body': 'Registo de tratamentos, direito de acesso exportado fonte a fonte, apagamento que conserva o que a lei obriga a conservar e diz. A conta é anonimizada em vez de eliminada, para que os lançamentos que a referenciam continuem coerentes.',
  'security.4.title': 'Canal de denúncia interna',
  'security.4.body': 'Obrigatório em França a partir de cinquenta trabalhadores. Conteúdo cifrado na base de dados, legível apenas pelos responsáveis designados — não pelos administradores, já que uma denúncia pode visar um deles. Acompanhamento anónimo por código, sem conta e sem registo.',
  'security.5.title': 'Cópias de segurança verificadas',
  'security.5.body': 'Arquivo de hora a hora, verificação de integridade por manifesto, restauro que repõe base e ficheiros, externalização por FTPS ou Google Drive, e aviso aos administradores em caso de falha.',
  'security.6.title': 'Segredos cifrados',
  'security.6.body': 'Palavras-passe de serviços externos, tokens de API, segredos de webhooks: cifrados em AES-256-GCM, nunca mostrados de novo em claro, ilegíveis após qualquer alteração.',
  'security.hostTitle': 'SaaS, ou consigo',
  'security.hostBody': 'Em SaaS alojamos na Europa, cópias incluídas. Nos planos pagos o alojamento local é possível: instala no seu servidor, a base nunca sai das suas paredes, e recebe as mesmas atualizações. Basta uma máquina — Node 22 e SQLite, nenhuma base externa para administrar.',
  'security.limitsTitle': 'O que não pretendemos fazer',
  'security.limitsBody': 'A assinatura eletrónica é simples, não qualificada no sentido eIDAS. O cofre sela e data os documentos, mas uma marca temporal oponível a terceiros exige uma autoridade de certificação. Nenhuma submissão fiscal ou à segurança social: o software produz os dados, a entrega continua a cargo do seu contabilista. Está escrito aqui e não depois da assinatura.',
  'pricing.title': 'Preços legíveis, sem surpresas',
  'pricing.lede': 'Um só preço, por colaborador e por mês, para gerir toda a empresa. Sem módulos à la carte, sem suplemento por função: todo o produto está em todos os planos.',
  'pricing.perMonth': '/ mês',
  'pricing.free': 'Gratuito',
  'pricing.vat': 'Preços sem impostos. Sem período mínimo nos planos mensais.',
  'pricing.cta': 'Começar',
  'pricing.ctaCustom': 'Escrever-nos',
  'pricing.popular': 'O mais escolhido',
  'pricing.p1.name': 'Gratuito',
  'pricing.p1.for': 'Menos de 5 colaboradores',
  'pricing.p1.body': 'Todo o produto, gratuitamente, sem limite de tempo e sem funções cortadas. O plano para uma empresa jovem, uma associação ou um escritório a começar.',
  'pricing.p2.name': 'Subscrição',
  'pricing.p2.for': 'A partir de 5 colaboradores',
  'pricing.p2.body': '5 € por colaborador e por mês, depois 4 € de duzentos e cinquenta a quinhentos, e 3 € acima. Paga o efetivo que tem, não o que talvez venha a ter.',
  'pricing.p4.name': 'Licença vitalícia',
  'pricing.p4.for': 'Pagamento único',
  'pricing.p4.body': '10 000 € uma vez. Sem subscrição, sem limite de tempo, sem teto de efetivo. O software é seu enquanto o quiser usar.',
  'pricing.tableTitle': 'O que cada plano inclui',
  'pricing.col.feature': '',
  'pricing.yes': 'Incluído',
  'pricing.no': 'Não',
  'pricing.option': 'Opcional',
  'pricing.f.allSpaces': 'Os 35 espaços e os 7 módulos',
  'pricing.f.languages': 'Os 16 idiomas e as 3 paletas',
  'pricing.f.security': 'Segurança completa, registo selado, RGPD',
  'pricing.f.updates': 'Atualizações incluídas',
  'pricing.f.saas': 'Alojamento SaaS na Europa',
  'pricing.f.local': 'Alojamento local dos seus dados',
  'pricing.f.backupOff': 'Externalização das cópias',
  'pricing.f.support': 'Apoio',
  'pricing.f.supportMail': 'Por e-mail',
  'pricing.f.supportPrio': 'Prioritário',
  'pricing.f.supportDedicated': 'Interlocutor dedicado',
  'pricing.f.supportCommunity': 'Documentação',
  'pricing.f.migration': 'Migração dos seus dados',
  'pricing.f.sla': 'Compromisso de serviço (SLA)',
  'pricing.f.api': 'API de leitura e webhooks',
  'pricing.f.multisite': 'Vários locais, várias entidades',
  'pricing.countTitle': 'Como contamos os colaboradores',
  'pricing.countBody': 'As contas ativas, freelancers e estagiários incluídos, administradores excluídos. Uma conta fechada já não conta, mesmo mantendo acesso ao seu cofre. Passou um patamar? A alteração aplica-se no mês seguinte, nunca retroativamente — e desce da mesma forma.',
  'faq.title': 'Perguntas frequentes',
  'faq.q1': 'O plano gratuito tem limite de tempo?',
  'faq.a1': 'Não. Abaixo de cinco colaboradores o produto é gratuito sem limite de tempo e sem funções cortadas. Preferimos uma estrutura pequena que cresce com o software a uma versão de teste que se apaga ao fim de trinta dias.',
  'faq.q2': 'Posso alojar os meus dados no meu servidor?',
  'faq.a2': 'Sim, nos planos pagos. O software corre numa única máquina com Node 22 e SQLite: nem servidor de base de dados, nem serviço externo. Base, documentos e cópias ficam consigo.',
  'faq.q3': 'O que acontece se eu parar?',
  'faq.a3': 'Exporta a instância inteira em JSON, documentos incluídos, a partir da consola de administração. Nada fica retido: é a sua base, e sai consigo num formato legível.',
  'faq.q4': 'Substitui o meu contabilista?',
  'faq.a4': 'Não. A contabilidade por partidas dobradas, os salários e o IVA servem para manter os lançamentos e preparar os documentos. Não há prestação de contas nem submissão eletrónica: a exportação alimenta o seu gabinete.',
  'faq.q5': 'É preciso formar as equipas?',
  'faq.a5': 'O espaço do colaborador explica-se sozinho: férias, documentos, escala, diretório. Os espaços de administração pedem meio dia de arranque, que acompanhamos nos planos pagos.',
  'faq.q6': 'Posso ativar só uma parte do produto?',
  'faq.a6': 'Sim. Sete módulos — contabilidade, salários, faturação eletrónica, armazém e compras, tesouraria, imobilizado, CRM — estão desligados por omissão e ativam-se um a um. Enquanto um módulo está desligado, os seus endereços respondem 404.',
  'faq.q7': 'Como se migram os meus dados atuais?',
  'faq.a7': 'Uma importação em massa em CSV verifica cada linha antes de escrever, e não escreve nada se uma única linha for inválida. Nos planos pagos preparamos os ficheiros consigo.',
  'faq.q8': 'E as integrações com as nossas ferramentas?',
  'faq.a8': 'Uma API REST de leitura com âmbitos e webhooks de saída assinados estão incluídos em todos os planos. Para trocas específicas — RH, ERP, faturação — escreva-nos: esse trabalho é orçamentado caso a caso.',
  'contact.title': 'Falemos da sua empresa',
  'contact.lede': 'Uma demonstração dura trinta minutos, sobre os seus casos e não sobre dados inventados. Escreva-nos o que procura resolver.',
  'contact.emailLabel': 'Por e-mail',
  'contact.demoTitle': 'Pedir uma demonstração',
  'contact.demoBody': 'Indique o seu nome, a empresa, o efetivo e o que hoje lhe cria problemas. Respondemos num dia útil.',
  'contact.write': 'Escrever à equipa',
  'contact.docTitle': 'Ler a documentação',
  'contact.docBody': 'O site de documentação detalha a instalação, a configuração, a segurança, a API e o glossário completo nos dezasseis idiomas.',
  'contact.docCta': 'Abrir a documentação',
  'contact.selfTitle': 'Instalar você mesmo',
  'contact.selfBody': 'Node 22, uma máquina, cinco minutos: o assistente cria a base, a conta de administrador e verifica o ambiente.',
  'contact.selfCta': 'Ver os requisitos',
  'cta.title': 'Comece grátis e mude de plano quando crescer',
  'cta.body': 'Abaixo de cinco colaboradores é tudo gratuito. Acima, 5 € por colaborador e por mês — degressivo a partir de duzentos e cinquenta — ou 10 000 € uma vez pela licença vitalícia. Nenhum cartão para experimentar.',
  'cta.primary': 'Criar a minha instância',
  'cta.secondary': 'Falar com alguém',
  'foot.product': 'Produto',
  'foot.company': 'Sobre nós',
  'foot.resources': 'Recursos',
  'foot.legal': 'Avisos legais',
  'foot.docs': 'Documentação',
  'foot.status': 'O que está coberto',
  'foot.rights': 'Todos os direitos reservados.',
  'foot.madeWith': 'Node 22 · Express · SQLite. Nenhuma dependência inútil.',
  'foot.langTitle': 'Este site existe em dezasseis idiomas',
  'dom.socle.title': 'Base e organização',
  'dom.socle.lede': 'O que sustenta o resto: as contas, as afetações e o vocabulário comum a todos os espaços.',
  'dom.socle.items': [
    'Contas e papéis acumuláveis: administrador, RH, gestão, informática, responsável de denúncias',
    'Chefia deduzida do enquadramento real, nunca concedida à mão',
    'Departamentos e equipas, várias chefias por perímetro, afetações relidas a cada pedido',
    'Organigrama visual, chefias incluídas, e as pessoas sem qualquer afetação',
    'Diretório com pesquisa e filtros, visibilidade gerida apenas pela administração',
    'Mensagens internas, e endereço profissional configurado pela administração',
    'Pesquisa global isolada na origem: o que não pode ver não é sequer procurado',
    'Centro de notificações por pessoa, com aviso de leitura',
    'Importação em massa em CSV: pré-visualização controlada, escrita tudo ou nada',
    'Assistente de instalação, definições da instância, sete módulos ativáveis',
    '16 idiomas, 3 paletas, tema claro/escuro/sistema, interface adaptável',
  ],
  'dom.espace.title': 'Espaço do colaborador',
  'dom.espace.lede': 'A página que todos abrem de manhã: o que lhes diz respeito, e nada mais.',
  'dom.espace.items': [
    'Painel pessoal: chefia, notícias, pedidos, documentos por confirmar',
    'Férias, folgas, ausências e teletrabalho: dias úteis calculados, fins de semana excluídos',
    'Saldo de férias atualizado, histórico dos ajustes fundamentados',
    'Recibos de vencimento consultáveis e guardados cinquenta anos no cofre',
    'Agenda pessoal e agenda partilhada de equipa',
    'Escala da semana, prevenção, permanências',
    'Ferramentas atribuídas com credenciais próprias — nenhuma palavra-passe de terceiros guardada',
    'Perfil: foto, apresentação, telefone, idioma, palavra-passe, fecho das sessões',
    'Marcação por cronómetro para freelancers, apenas uma em curso de cada vez',
    'Declaração de interesses e de ofertas, visível apenas para si',
  ],
  'dom.rh.title': 'Recursos humanos',
  'dom.rh.lede': 'O processo do colaborador, da entrada à saída, com os prazos que traz.',
  'dom.rh.items': [
    'Aprovação de pedidos com dedução do saldo, recusa fundamentada, anulação que devolve os dias',
    'Recibos: criação, acompanhamento do pagamento, geração em lote',
    'Documentos da empresa com confirmação de receção nominal',
    'Formação: catálogo, sessões, inscrições, custo e duração',
    'Entrevistas anuais: campanha, guião, relatório',
    'Entrada e saída: listas de verificação seguidas, responsável e prazo por tarefa',
    'Competências e habilitações, com data de reciclagem e aviso antecipado',
    'Reuniões individuais: resumo partilhado, notas da chefia mantidas à parte',
    'Cofre digital acessível após a saída, documentos selados pela sua impressão',
    'Assinatura eletrónica simples: circuito ordenado, impressão, selo, certificado',
    'Contratos a termo: a conta fecha-se sozinha no dia previsto',
  ],
  'dom.talent.title': 'Recrutamento e talentos',
  'dom.talent.lede': 'Das candidaturas ao primeiro dia, sem folha de cálculo pelo meio.',
  'dom.talent.items': [
    'Ofertas de emprego e candidaturas seguidas por etapa',
    'Receção de CV: PDF, DOCX ou texto, escritos fora do repositório',
    'Extração do conteúdo e base de CV pesquisável',
    'Critérios ponderados, pontuação, limiar, classificação das candidaturas',
    'Um candidato aceite passa diretamente para o percurso de entrada',
    'Inquéritos internos e barómetro social, anónimos por construção',
    'Abaixo de cinco respostas nenhum resultado é mostrado',
  ],
  'dom.sst.title': 'Saúde, segurança e representação',
  'dom.sst.lede': 'As obrigações que se mantêm por escrito e se lembram sozinhas.',
  'dom.sst.items': [
    'Avaliação de riscos: unidades de trabalho, perigos, cotação, medidas, revisão datada',
    'Registo de acidentes de trabalho e quase-acidentes, dias de baixa',
    'Equipamentos de proteção: entrega nominal, validade, substituição',
    'Exames médicos: admissão, periódico, regresso, a pedido',
    'Representação: eleições, caderno eleitoral, voto anónimo, mandatos e o seu termo',
    'Reuniões do órgão, benefícios e serviços aos trabalhadores',
    'O espaço de gestão fecha-se sozinho no fim do mandato',
  ],
  'dom.finance.title': 'Finanças e gestão',
  'dom.finance.lede': 'Os terceiros, os contratos, o dinheiro que entra e o que sai.',
  'dom.finance.items': [
    'Clientes e fornecedores, ficha completa: contactos, contratos, faturas',
    'Contratos e sobretudo pré-avisos: a data limite para denunciar é calculada e avisada',
    'Faturas nos dois sentidos, total calculado, atraso deduzido do vencimento',
    'Orçamentos por departamento e exercício, consumo agregado automaticamente',
    'Despesas: apresentação, aprovação, reembolso — nunca uma sem a outra',
    'Documentos de conformidade de terceiros, datados e avisados quarenta e cinco dias antes',
    'Avaliações de fornecedores pontuadas: vale a última revisão, não a média',
    'Multimoeda com a taxa fixada na emissão de cada documento',
    'Faturação recorrente: a subscrição é o molde, a fatura é o documento',
    'Leitura automática das faturas recebidas e recolha IMAP de uma caixa contabilística',
  ],
  'dom.compta.title': 'Contabilidade, salários e IVA',
  'dom.compta.lede': 'Módulos desligados por omissão, que se ligam quando precisar.',
  'dom.compta.items': [
    'Contabilidade por partidas dobradas: plano de contas, diários, balancete, razão',
    'Um lançamento desequilibrado é recusado, e a mensagem diz por quanto',
    'Uma fatura passa a lançamento com um clique; exportação CSV para o gabinete',
    'Motor de salários: tabelas configuráveis, do bruto ao líquido, encargos, custo empresa',
    'Recibo detalhado linha a linha, geração em lote, simulador',
    'Declarações de IVA: liquidado, dedutível, repartição por taxa, crédito a reportar',
    'Uma declaração entregue não se recalcula: é um documento, não um painel',
    'Faturação eletrónica: verificação EN 16931 e exportação do XML CII',
    'Tesouraria: contas, movimentos, reconciliação, previsão a doze semanas',
    'Imobilizado: amortização linear e degressiva, valor líquido contabilístico',
  ],
  'dom.achats.title': 'Compras, armazém e cobranças',
  'dom.achats.lede': 'O que se encomenda, o que chega, o que é faturado — e o que nos devem.',
  'dom.achats.items': [
    'Pedidos de compra validados pela chefia e depois pela gestão acima do limiar',
    'Encomendas, receções e reconciliação a três: encomendado, recebido, faturado',
    'Receber mais do que o encomendado é recusado; um desvio de faturação é nomeado, não bloqueado',
    'Artigos, movimentos, limiar de alerta: o stock é a soma dos movimentos',
    'Uma linha ligada a um artigo entra em armazém no momento da receção',
    'Balanço por antiguidade dos clientes, por escalão de atraso',
    'Avisos escalonados: lembrete, insistência, interpelação, conforme o já enviado',
    'Cada aviso registado com o seu nível e a sua data',
  ],
  'dom.projets.title': 'Projetos, tempo e rentabilidade',
  'dom.projets.lede': 'Saber em que ponto está um projeto, e quanto custou realmente.',
  'dom.projets.items': [
    'Projetos ligados a um cliente, um departamento, uma equipa e um responsável',
    'Marcos datados e tarefas em colunas por estado, com prioridade e estimativa',
    'Tempo imputado ao projeto e à tarefa, no máximo 24 h por registo',
    'Rentabilidade: horas, custo à taxa horária, margem restante, parte do orçamento consumida',
    'Três círculos de direitos: a gestão, o responsável, os membros',
    'Tempo por pessoa e saúde dos projetos no painel de direção',
  ],
  'dom.support.title': 'Apoio e conhecimento',
  'dom.support.lede': 'Os pedidos internos e de clientes no mesmo circuito, e as respostas que ficam.',
  'dom.support.items': [
    'Tickets internos e de clientes, prioridade, origem, atribuição',
    'Prazo de primeira resposta deduzido da prioridade, recalculado desde a abertura',
    'Notas internas invisíveis para quem pede, e que não contam como resposta',
    'Separação por categoria: um pedido de RH não sai dos RH',
    'Base de conhecimento por categoria, pesquisa em texto integral, alcance ajustável',
    'Indicadores: tickets abertos, em atraso, prazo médio',
  ],
  'dom.ops.title': 'Operações e serviços gerais',
  'dom.ops.lede': 'As escalas, a qualidade, as salas, os veículos, a receção.',
  'dom.ops.items': [
    'Escala por pessoa e por dia: turnos, prevenção, permanências, teletrabalho',
    'Sobreposição ou ausência já concedida: o turno é recusado ao ser criado',
    'Rotações reutilizáveis, turnos noturnos, publicação da semana',
    'Quem está de prevenção neste momento, com o seu número',
    'Qualidade: não conformidades, causas raiz, ações corretivas e verificação de eficácia',
    'Auditorias internas: constatações, síntese, uma constatação promovida a não conformidade',
    'Equipamentos atribuídos e devolvidos, com histórico dos detentores',
    'Salas e reservas, sobreposição recusada nomeando quem a ocupa',
    'Frota: manutenção, inspeção, seguro, sinistros, quilometragem',
    'Receção: registo de visitantes, lista dos presentes, correio recebido e enviado',
  ],
  'dom.direction.title': 'Direção e governação',
  'dom.direction.lede': 'O que a direção olha, e o que decide.',
  'dom.direction.items': [
    'Painel: efetivo, ausentes, faturado, margem, massa salarial, tesouraria, apoio',
    'Objetivos e resultados-chave, cada um na sua escala, mesmo decrescente',
    'Reuniões: convocatória, ordem de trabalhos, presenças marcadas, ata',
    'Registo das decisões com o seu fundamento — o que se procura dois anos depois',
    'Ações atribuídas com responsável e prazo, ligadas à sua decisão',
    'Registo de riscos: cotação bruta e residual, matriz 5 × 5, tratamento, revisão',
    'Eventos da empresa: lotação, lista de espera automática, folha de presenças, orçamento',
    'Prazos de todos os espaços reunidos numa única lista ordenada',
  ],
  'dom.it.title': 'Informática e desenvolvimento',
  'dom.it.lede': 'O parque de software, os acessos, os incidentes, e o que a equipa entrega.',
  'dom.it.items': [
    'Parque de software: licenças tratadas como restrição, custo anualizado, renovações',
    'Revisão dos acessos: primeiro as contas fechadas, depois os direitos de administração',
    'Incidentes informáticos, com hora, e tempo médio de reposição efetivamente medido',
    'Catálogo de serviços: criticidade, responsável, repositório, documentação',
    'Registo de entregas por ambiente e indicadores de entrega',
    'Cópias de segurança: arquivo horário, integridade verificada, restauro, externalização',
    'API REST de leitura com âmbitos, webhooks de saída assinados',
    'Exportação integral da instância em JSON, documentos incluídos, segredos excluídos',
  ],
  'dom.conformite.title': 'Conformidade, societário e dados pessoais',
  'dom.conformite.lede': 'O que uma empresa tem de conseguir provar, mantido ao longo do tempo.',
  'dom.conformite.items': [
    'Registo de sócios: participação deduzida dos movimentos, cessão escrita em duas pernas',
    'Mandatos sociais com duração, revogação e termo avisado com antecedência',
    'Assembleias gerais: quórum em participações, deliberações, votos, ata',
    'Delegações de poderes: objeto, limite, duração, termo avisado',
    'Conflitos de interesses e ofertas: cada um declara por si, a administração examina',
    'Canal interno de denúncia cifrado, responsáveis designados, acompanhamento anónimo por código',
    'Registo de auditoria com hora, exportável e selado por encadeamento de impressões',
    'RGPD: registo de tratamentos, direito de acesso exportado, apagamento fundamentado',
    'Circuitos de aprovação configuráveis: formulários, limiares, aprovadores por função',
  ],
  'shot.membre-espace': 'Espaço do colaborador',
  'shot.membre-equipe': 'Espaço da chefia',
  'shot.membre-demandes': 'Pedidos internos',
  'shot.membre-agenda': 'Agenda pessoal e partilhada',
  'shot.membre-salles': 'Salas e reservas',
  'shot.membre-messagerie': 'Mensagens internas',
  'shot.membre-connaissances': 'Base de conhecimento',
  'shot.membre-coffre-fort': 'Cofre digital',
  'shot.membre-profil': 'Perfil e segurança da conta',
  'shot.membre-juridique-membre': 'As minhas declarações',
  'shot.annuaire': 'Diretório da empresa',
  'shot.organigramme': 'Organigrama',
  'shot.connexion': 'Ecrã de acesso',
  'shot.pilotage': 'Painel de direção',
  'shot.admin': 'Consola de administração',
  'shot.rh': 'Recursos humanos',
  'shot.gestion': 'Gestão administrativa e financeira',
  'shot.direction': 'Direção e governação',
  'shot.projets': 'Projetos, marcos e rentabilidade',
  'shot.support': 'Apoio e tickets',
  'shot.planning': 'Escalas, rotações e prevenção',
  'shot.qualite': 'Qualidade e auditorias internas',
  'shot.sante-securite': 'Saúde e segurança no trabalho',
  'shot.informatique': 'Parque de software e acessos',
  'shot.developpement': 'Serviços e entregas',
  'shot.evenements': 'Eventos da empresa',
  'shot.juridique': 'Vida societária e conformidade',
  'shot.alertes': 'Canal de denúncia interna',
  'shot.securite': 'Consola de segurança',
  'shot.rgpd': 'Dados pessoais',
  'shot.parapheur': 'Pasta de assinaturas',
  'shot.sauvegardes': 'Cópias e restauro',
  'shot.comptabilite': 'Contabilidade por partidas dobradas',
  'shot.paie': 'Motor de salários',
  'shot.tresorerie': 'Tesouraria e previsão',
  'shot.immobilisations': 'Imobilizado e amortizações',
  'shot.crm': 'CRM comercial',
  'shot.stock': 'Armazém e compras',
  'shot.pilotage-sombre': 'Direção — tema escuro',
  'shot.membre-espace-sombre': 'Espaço do colaborador — tema escuro',
  'shot.gestion-sombre': 'Gestão — tema escuro',
  'shot.projets-sombre': 'Projetos — tema escuro',
  'shot.juridique-sombre': 'Vida societária — tema escuro',
  'shot.securite-sombre': 'Segurança — tema escuro',
  'tour.pilotage': 'Efetivo, faturado, margem, tesouraria, apoio: o que a direção olha, numa página. Um travessão marca um dado ausente — nunca um zero que passaria por um número.',
  'tour.membre-espace': 'A página que cada um abre de manhã: a sua chefia, as notícias que lhe dizem respeito, os seus pedidos, os documentos por confirmar, as suas ferramentas e credenciais.',
  'tour.rh': 'Pedidos a tratar, saldos, recibos, documentos, formação, entrevistas: o processo do colaborador mantém-se aqui, e os prazos sobem sozinhos.',
  'tour.gestion': 'Terceiros, contratos e pré-avisos, faturas nos dois sentidos, orçamentos por departamento, despesas, cobranças. O consumo de um orçamento soma-se sozinho.',
  'tour.projets': 'Marcos, tarefas em colunas, tempo gasto e rentabilidade face ao orçamento. O custo não se digita: deduz-se das horas e da taxa horária.',
  'tour.juridique': 'Capital, mandatos sociais, assembleias e atas, delegações, declarações de interesses. O que uma empresa tem de conseguir provar, mantido ao longo do tempo.',
  'pricing.perEmployee': '5 € por colaborador e por mês',
  'pricing.perEmployeeShort': 'por colaborador / mês',
  'pricing.argTitle': 'Cinco euros por colaborador, para tudo',
  'pricing.argBody': 'Uma ferramenta de RH, um programa de contabilidade, um gestor de projetos, um sistema de tickets, um cofre de recibos: cinco subscrições a 8 ou 15 € por utilizador, cinco bases que não falam entre si, cinco faturas. O Toutadmin substitui a pilha inteira pelo preço da mais barata — e os dados ficam finalmente no mesmo sítio.',
  'pricing.gridTitle': 'A grelha, por efetivo',
  'pricing.gridLede': 'O preço segue o efetivo e mais nada: 5 € por colaborador até duzentos e quarenta e nove, 4 € de duzentos e cinquenta a quinhentos, 3 € acima. Passar um escalão baixa a fatura de todos, não apenas dos recém-chegados.',
  'pricing.col.headcount': 'Efetivo',
  'pricing.col.monthly': 'Por mês',
  'pricing.col.perEmployee': 'Por colaborador',
  'pricing.upTo': 'Até {count} colaboradores',
  'pricing.under': 'Menos de {count} colaboradores',
  'pricing.once': 'pagamento único',
  'pricing.lifetimeTitle': 'Porquê uma licença vitalícia',
  'pricing.lifetimeBody': 'Dez mil euros uma vez, sem subscrição e sem limite de tempo: a mesma instância, as mesmas atualizações, sem teto de efetivo. Com cem colaboradores amortiza-se em vinte meses; com quinhentos, em cinco. É a oferta para quem prefere um investimento a uma linha de custo recorrente — e para quem não quer depender de ninguém para continuar a trabalhar.',
  'faq.q9': 'O que acontece se o meu efetivo mudar a meio do ano?',
  'faq.a9': 'O preço acompanha, nos dois sentidos, a partir do mês seguinte e nunca com efeito retroativo. Uma contratação que o faça passar um patamar é faturada no mês seguinte; uma saída que o faça descer, também. Ninguém paga por contas fechadas.',
  'faq.q10': 'A licença vitalícia dá direito às atualizações?',
  'faq.a10': 'Sim, sem limite de tempo: é o sentido de «vitalícia». Recebe as mesmas versões dos planos mensais e pode alojar a base consigo. O que a licença não inclui é o apoio prioritário, que continua a ser um serviço à parte.',
  'pricing.someEmployees': '{count} colaboradores',
};
