/* tr — traduit du français. Toute clé du français doit exister ici :
   le build refuse de construire une langue incomplète. */
module.exports = {
  'locale.name': 'Türkçe',
  'site.name': 'Toutadmin',
  'site.tagline': 'Tüm şirketi yöneten CMS',
  'nav.product': 'Ürün',
  'nav.features': 'Özellikler',
  'nav.screens': 'Ekranlar',
  'nav.security': 'Güvenlik',
  'nav.pricing': 'Fiyatlar',
  'nav.contact': 'İletişim',
  'nav.demo': 'Demo isteyin',
  'nav.menu': 'Menü',
  'nav.language': 'Dil',
  'nav.theme': 'Tema',
  'nav.themeLight': 'Açık',
  'nav.themeDark': 'Koyu',
  'nav.themeSystem': 'Sistem',
  'hero.eyebrow': 'Kurumsal yönetim yazılımı',
  'hero.title': 'Tüm şirketiniz,\ntek bir yazılımda.',
  'hero.lede': 'Personel, insan kaynakları, finans, operasyon, yönetişim, uyum, idari işler. Birbiriyle konuşan otuz beş çalışma alanı, tek bir veritabanı, birbirine yapıştırılacak hiçbir uygulama yok. On altı dilde ve on çalışana kadar ücretsiz.',
  'hero.ctaPrimary': 'Ücretsiz deneyin',
  'hero.ctaSecondary': 'Özellikleri görün',
  'hero.note': 'Kredi kartı yok. Verileriniz sizin kalır — ve sizde de kalabilir.',
  'hero.badge1': 'SaaS beş dakikada hazır',
  'hero.badge2': 'ya da kendi sunucunuzda',
  'hero.badge3': 'Tasarımdan gelen KVKK/GDPR uyumu',
  'stats.title': 'Ürünün kapsadıkları, rakamlarla',
  'stats.spaces': 'çalışma alanı',
  'stats.spacesNote': 'çalışanın kendi sayfasından şirket hukukuna',
  'stats.languages': 'arayüz dili',
  'stats.languagesNote': 'Arapça dahil, sayfa tersine çevrilir',
  'stats.tests': 'entegrasyon testi',
  'stats.testsNote': 'her sürümde çalıştırılır',
  'stats.modules': 'açılabilir modül',
  'stats.modulesNote': 'muhasebe, bordro, nakit, CRM…',
  'stats.deps': 'dış servis gerekiyor',
  'stats.depsNote': 'bir makine, bir veritabanı, başka bir şey yok',
  'stats.keys': 'çevrilmiş etiket',
  'stats.keysNote': 'onay kutularına kadar',
  'pillars.title': 'Neden birbirine yapıştırılmış beş araç yerine Toutadmin',
  'pillars.lede': 'Birbiriyle konuşmayan beş program tek bir programdan pahalıya gelir ve en önemlisini kaybettirir: bütünün görüntüsünü. Toutadmin tersinden başlar — tek veritabanı, alanlar, yetkiler.',
  'pillars.1.title': 'Tek yer, tek gerçek',
  'pillars.1.body': 'Bir birimin bütçesi kendi faturalarını ve üyelerinin onaylanmış masraflarını kendiliğinden toplar. Bir mal kabulü aynı hareketle stoka girer. Kimse bir şeyi yeniden yazmaz, dolayısıyla kimse kendisiyle çelişmez.',
  'pillars.2.title': 'Yetkiler süs değildir',
  'pillars.2.body': 'Her yol kendi sunucu tarafı denetimini taşır ve bağlılıklar her istekte yeniden okunur. Bir ayrılış erişimi hemen keser — çerez süresi dolduğunda değil. Görmeye hakkınız olmayan şey hiç aranmaz bile.',
  'pillars.3.title': 'Vadeler size gelir',
  'pillars.3.body': 'Sözleşme ihbar süreleri, yenilenecek yetkinlikler, sağlık muayeneleri, araç muayenesi, şirket organ görevleri, tedarikçi belgeleri: tek bir mekanizma hepsini toplar ve doğru kişiyi bir kez, tekrarsız uyarır.',
  'pillars.4.title': 'Her ekran yapmadığını söyler',
  'pillars.4.body': 'Bir modül sınırını açıldığı anda gösterir, bir kılavuzun dibinde değil. Dürüst bir cümleyi işaretlenmiş bir kutuya tercih ederiz: üçüncü aydaki kötü sürprizi önleyen tam da budur.',
  'pillars.5.title': 'On altı dil, gerçekten',
  'pillars.5.body': 'Yalnızca giriş ekranı değil: durumlar, hata iletileri, onay kutuları. Arapça tüm sayfayı ters çevirir, çünkü stil dosyası yalnızca mantıksal özellikler kullanır.',
  'pillars.6.title': 'Verileriniz, isterseniz sizde',
  'pillars.6.body': 'SaaS\'ta her şey beş dakikada hazır. Ücretli planlarda veritabanını kendi sunucunuzda da tutabilirsiniz: aynı yazılım, aynı güncellemeler, veriler sizin duvarlarınızın içinde.',
  'tour.title': 'Yoğun bir yazılım, oyuncak değil',
  'tour.lede': 'Günde sekiz saat açık tutanlar için yapılmış ekranlar: bir bakışta bilgi, gereksiz kip pencereleri yok ve her yerde aynı sözlük.',
  'tour.hint': 'Ekranı değiştirmek için bir sekmeye tıklayın.',
  'tour.all': '40 ekranın tümünü görün',
  'features.title': 'Toutadmin\'in yapabildiği her şey',
  'features.lede': 'Alan alan tam liste. Her satır teslim edilmiş ve test edilmiş koda karşılık gelir, bir niyete değil.',
  'features.legend': '«Modül» işaretli işlevler gerektiğinde konsoldan açılır.',
  'features.module': 'modül',
  'features.seeAll': 'Tam listeyi görün',
  'features.intro': 'On dört alan, yüz otuzdan fazla işlev.',
  'features.ctaTitle': 'Eksik bir şey mi var?',
  'features.ctaBody': 'Bize söyleyin. Ürün partiler hâlinde ilerler ve onu kullanan şirketlerin istekleri öne geçer.',
  'screens.title': 'Ekranlar, rötuşsuz',
  'screens.lede': 'Bu sitedeki tüm görüntüler, örnek verilerle doldurulmuş gerçek bir kurulumdan çıkmıştır. Maket yok, montaj yok.',
  'screens.light': 'Açık tema',
  'screens.dark': 'Koyu tema',
  'screens.member': 'Çalışan alanı',
  'screens.admin': 'Yönetim ve sevk',
  'screens.modules': 'İsteğe bağlı modüller',
  'screens.open': 'Büyüt',
  'screens.close': 'Kapat',
  'screens.prev': 'Önceki',
  'screens.next': 'Sonraki',
  'security.title': 'Güvenlik ücretli bir seçenek değildir',
  'security.lede': 'Aşağıdakilerin tamamı üründe vardır, hangi plan olursa olsun — ücretsiz plan dahil.',
  'security.1.title': 'Sıkılaştırılmış kimlik doğrulama',
  'security.1.body': 'Karma ile saklanan parolalar (bcrypt), karmaşıklık kuralları, tekrarlanan hatalardan sonra kilitleme, kurtarma kodlu TOTP iki adımlı doğrulama, oturumlar tek tek veya topluca iptal edilebilir.',
  'security.2.title': 'Mühürlenmiş denetim günlüğü',
  'security.2.body': 'Her kayıt bir öncekinin parmak izini taşır. Bir satırı değiştirmek ya da ortadan birini çıkarmak zinciri tam o noktada kırar ve doğrulama hangisi olduğunu söyler. Yapmadığı şey: sunucuyu elinde tutanın yeniden yazmasını engellemek — onu görünür kılar.',
  'security.3.title': 'Kişisel veriler',
  'security.3.body': 'İşleme kayıt defteri, erişim hakkı kaynak kaynak dışa aktarılır, silme yasanın saklamayı zorunlu kıldığını saklar ve bunu söyler. Hesap silinmek yerine anonimleştirilir, böylece ona atıf yapan kayıtlar tutarlı kalır.',
  'security.4.title': 'İç bildirim kanalı',
  'security.4.body': 'Fransa\'da elli çalışandan itibaren zorunlu. İçerik veritabanında şifrelenir, yalnızca atanmış sorumlular okuyabilir — yöneticiler değil, çünkü bir bildirim onlardan birini hedef alabilir. Kodla anonim takip, hesap açmadan ve kayda geçmeden.',
  'security.5.title': 'Doğrulanmış yedekler',
  'security.5.body': 'Saatlik arşiv, bildirim dosyasıyla bütünlük denetimi, veritabanını ve dosyaları geri koyan kurtarma, FTPS veya Google Drive\'a dışa taşıma ve başarısızlıkta yöneticilere uyarı.',
  'security.6.title': 'Şifrelenmiş sırlar',
  'security.6.body': 'Üçüncü taraf servis parolaları, API belirteçleri, webhook sırları: AES-256-GCM ile şifrelenir, bir daha açık gösterilmez, değiştirildiğinde okunamaz hâle gelir.',
  'security.hostTitle': 'SaaS ya da sizde',
  'security.hostBody': 'SaaS\'ta Avrupa\'da barındırıyoruz, yedekler dahil. Ücretli planlarda yerel barındırma mümkündür: kendi sunucunuza kurarsınız, veritabanı duvarlarınızdan hiç çıkmaz ve aynı güncellemeleri alırsınız. Tek makine yeter — Node 22 ve SQLite, yönetilecek dış veritabanı yok.',
  'security.limitsTitle': 'Yaptığımızı iddia etmediklerimiz',
  'security.limitsBody': 'Elektronik imza basittir, eIDAS anlamında nitelikli değildir. Kasa belgeleri mühürler ve tarihlendirir, ama üçüncü kişilere karşı ileri sürülebilir bir zaman damgası sertifika otoritesi gerektirir. Vergi ya da sosyal güvenlik bildirimi yok: yazılım veriyi üretir, gönderimi mali müşavirinizin işidir. Bu, imzadan sonra değil, burada yazılıdır.',
  'pricing.title': 'Okunur fiyatlar, sürpriz yok',
  'pricing.lede': 'Fiyat çalışan sayısına bağlıdır, işlev sayısına değil: ürünün tamamı her plandadır.',
  'pricing.perMonth': '/ ay',
  'pricing.free': 'Ücretsiz',
  'pricing.custom': 'Özel',
  'pricing.vat': 'Fiyatlar vergi hariçtir, süre taahhüdü yoktur.',
  'pricing.cta': 'Başlayın',
  'pricing.ctaCustom': 'Bize yazın',
  'pricing.popular': 'En çok seçilen',
  'pricing.p1.name': 'Keşif',
  'pricing.p1.for': '10 çalışandan az',
  'pricing.p1.body': 'Ürünün tamamı, ücretsiz, süre sınırı olmadan. Genç bir şirket, bir dernek ya da bir büro için plan.',
  'pricing.p2.name': 'Ekip',
  'pricing.p2.for': '50 çalışandan az',
  'pricing.p2.body': 'Aynı ürün, istenirse yerel barındırma, e-posta desteği ve dışa taşınan yedekler.',
  'pricing.p3.name': 'Şirket',
  'pricing.p3.for': '100 çalışana kadar',
  'pricing.p3.body': 'Yapılanmış bir KOBİ için: öncelikli destek, veri aktarımında eşlik ve kurulumunuzu tanıyan bir muhatap.',
  'pricing.p4.name': 'Özel',
  'pricing.p4.for': '100 çalışandan fazla',
  'pricing.p4.body': 'Birden çok lokasyon, size ait bir altyapı, yazılacak entegrasyonlar, bir hizmet taahhüdü: konuşur ve fiyatlandırırız.',
  'pricing.tableTitle': 'Her planın içeriği',
  'pricing.col.feature': '',
  'pricing.yes': 'Dahil',
  'pricing.no': 'Hayır',
  'pricing.option': 'İsteğe bağlı',
  'pricing.f.allSpaces': '35 alan ve 7 modül',
  'pricing.f.languages': '16 dil ve 3 renk paleti',
  'pricing.f.security': 'Tam güvenlik, mühürlü günlük, GDPR',
  'pricing.f.updates': 'Güncellemeler dahil',
  'pricing.f.saas': 'Avrupa\'da SaaS barındırma',
  'pricing.f.local': 'Verilerinizin yerel barındırılması',
  'pricing.f.backupOff': 'Yedeklerin dışa taşınması',
  'pricing.f.support': 'Destek',
  'pricing.f.supportMail': 'E-posta ile',
  'pricing.f.supportPrio': 'Öncelikli',
  'pricing.f.supportDedicated': 'Özel muhatap',
  'pricing.f.supportCommunity': 'Belgeler',
  'pricing.f.migration': 'Verilerinizin aktarımı',
  'pricing.f.sla': 'Hizmet taahhüdü (SLA)',
  'pricing.f.api': 'Okuma API\'si ve webhook\'lar',
  'pricing.f.multisite': 'Birden çok lokasyon ve tüzel kişi',
  'pricing.countTitle': 'Çalışanları nasıl sayıyoruz',
  'pricing.countBody': 'Etkin hesaplar, serbest çalışanlar ve stajyerler dahil, yöneticiler hariç. Kapatılmış bir hesap artık sayılmaz, kasasına erişimi sürse bile. Bir eşiği mi aştınız? Plan değişikliği ertesi ay geçerli olur, geriye dönük asla.',
  'faq.title': 'Sık sorulan sorular',
  'faq.q1': 'Ücretsiz plan süreli mi?',
  'faq.a1': 'Hayır. On çalışanın altında ürün süresiz ücretsizdir ve hiçbir işlev kısıtlı değildir. Otuz günde sönen bir deneme sürümü yerine, yazılımla birlikte büyüyen küçük bir yapıyı tercih ederiz.',
  'faq.q2': 'Verilerimi kendi sunucumda barındırabilir miyim?',
  'faq.a2': 'Evet, ücretli planlarda. Yazılım Node 22 ve SQLite ile tek bir makinede çalışır: ne veritabanı sunucusu ne de dış servis. Veritabanı, belgeler ve yedekler sizde kalır.',
  'faq.q3': 'Bırakırsam ne olur?',
  'faq.a3': 'Yönetim konsolundan tüm kurulumu belgelerle birlikte JSON olarak dışa aktarırsınız. Hiçbir şey rehin tutulmaz: veritabanı sizindir ve okunabilir bir biçimde sizinle gider.',
  'faq.q4': 'Mali müşavirimin yerini alır mı?',
  'faq.a4': 'Hayır. Çift taraflı muhasebe, bordro ve KDV kayıtlarınızı tutmak ve belgeleri hazırlamak içindir. Ne beyanname ne elektronik gönderim vardır: dışa aktarım müşavirinizi besler.',
  'faq.q5': 'Ekipleri eğitmek gerekir mi?',
  'faq.a5': 'Çalışan alanı kendini anlatır: izinler, belgeler, çalışma planı, rehber. Yönetim alanları yarım günlük bir alışma ister; bunu Şirket ve Özel planlarda birlikte yaparız.',
  'faq.q6': 'Ürünün yalnızca bir bölümünü açabilir miyim?',
  'faq.a6': 'Evet. Yedi modül — muhasebe, bordro, e-fatura, stok ve satın alma, nakit, duran varlıklar, CRM — varsayılan olarak kapalıdır ve tek tek açılır. Bir modül kapalıyken adresleri 404 yanıtı verir.',
  'faq.q7': 'Mevcut verilerimin aktarımı nasıl olur?',
  'faq.a7': 'CSV toplu içe aktarma her satırı yazmadan önce denetler ve tek bir satır geçersizse hiçbir şey yazmaz. Şirket ve Özel planlarda dosyaları sizinle birlikte hazırlarız.',
  'faq.q8': 'Peki araçlarımızla entegrasyon?',
  'faq.a8': 'Kapsamlı bir okuma REST API\'si ve imzalı giden webhook\'lar dahildir. Özel alışverişler — İK sistemi, ERP, faturalama — için Özel plan vardır.',
  'contact.title': 'Şirketinizi konuşalım',
  'contact.lede': 'Bir gösterim otuz dakika sürer ve uydurma veriler yerine sizin durumlarınız üzerinden yapılır. Neyi çözmek istediğinizi yazın.',
  'contact.emailLabel': 'E-posta ile',
  'contact.demoTitle': 'Gösterim isteyin',
  'contact.demoBody': 'Adınızı, şirketinizi, çalışan sayınızı ve bugün sizi zorlayan şeyi belirtin. Bir iş günü içinde yanıtlıyoruz.',
  'contact.write': 'Ekibe yazın',
  'contact.docTitle': 'Belgeleri okuyun',
  'contact.docBody': 'Belge sitesi kurulumu, yapılandırmayı, güvenliği, API\'yi ve on altı dildeki tam sözlüğü ayrıntılarıyla anlatır.',
  'contact.docCta': 'Belgeleri aç',
  'contact.selfTitle': 'Kendiniz kurun',
  'contact.selfBody': 'Node 22, bir makine, beş dakika: sihirbaz veritabanını ve yönetici hesabını oluşturur, ortamı denetler.',
  'contact.selfCta': 'Gereksinimleri görün',
  'cta.title': 'Ücretsiz başlayın, büyüdükçe plan değiştirin',
  'cta.body': 'On çalışanın altında her şey ücretsizdir. Üstünde fiyatlar üç satıra sığar. Denemek için kart gerekmez.',
  'cta.primary': 'Kurulumumu oluştur',
  'cta.secondary': 'Biriyle konuşun',
  'foot.product': 'Ürün',
  'foot.company': 'Hakkımızda',
  'foot.resources': 'Kaynaklar',
  'foot.legal': 'Yasal',
  'foot.docs': 'Belgeler',
  'foot.status': 'Neler kapsanıyor',
  'foot.rights': 'Tüm hakları saklıdır.',
  'foot.madeWith': 'Node 22 · Express · SQLite. Gereksiz hiçbir bağımlılık yok.',
  'foot.langTitle': 'Bu site on altı dilde mevcut',
  'dom.socle.title': 'Temel ve organizasyon',
  'dom.socle.lede': 'Geri kalanı taşıyan şey: hesaplar, bağlılıklar ve tüm alanların paylaştığı sözlük.',
  'dom.socle.items': [
    'Hesaplar ve birleşebilen roller: yönetici, İK, mali işler, bilgi işlem, bildirim sorumlusu',
    'Yönetici sıfatı gerçek bağlılıktan türetilir, elle asla verilmez',
    'Birimler ve ekipler, alan başına birden çok yönetici, bağlılıklar her istekte yeniden okunur',
    'Görsel organizasyon şeması, yönetim dahil, ve hiçbir yere bağlı olmayan kişiler',
    'Arama ve süzgeçli rehber, görünürlüğü yalnızca yönetim belirler',
    'İç mesajlaşma ve yönetimce yapılandırılan kurumsal adres',
    'Kaynakta ayrılmış genel arama: görmeye hakkınız olmayan aranmaz bile',
    'Kişi başına bildirim merkezi, okundu bilgisiyle',
    'CSV toplu içe aktarma: denetlenmiş önizleme, ya hep ya hiç yazma',
    'Kurulum sihirbazı, kurulum ayarları, açılabilir yedi modül',
    '16 dil, 3 palet, açık/koyu/sistem teması, uyarlanabilir arayüz',
  ],
  'dom.espace.title': 'Çalışan alanı',
  'dom.espace.lede': 'Herkesin sabah açtığı sayfa: kendisini ilgilendiren şeyler, başka bir şey değil.',
  'dom.espace.items': [
    'Kişisel panel: yönetici, duyurular, talepler, onaylanacak belgeler',
    'İzin, mazeret, devamsızlık ve uzaktan çalışma: iş günleri hesaplanır, hafta sonları dışlanır',
    'Güncel izin bakiyesi, gerekçeli düzeltmelerin geçmişi',
    'Bordrolar görüntülenebilir ve kasada elli yıl saklanır',
    'Kişisel ajanda ve paylaşılan ekip ajandası',
    'Haftalık çalışma planı, nöbetler, sürekli görevler',
    'Kendi kullanıcı adıyla atanmış araçlar — hiçbir üçüncü taraf parolası saklanmaz',
    'Profil: fotoğraf, tanıtım, telefon, dil, parola, tüm oturumları kapatma',
    'Serbest çalışanlar için kronometreyle zaman kaydı, aynı anda yalnızca bir tane',
    'Çıkar ve hediye bildirimi, yalnızca kendine görünür',
  ],
  'dom.rh.title': 'İnsan kaynakları',
  'dom.rh.lede': 'Çalışanın dosyası, gelişinden ayrılışına, beraberinde getirdiği vadelerle.',
  'dom.rh.items': [
    'Bakiyeden düşerek talep onayı, gerekçeli ret, günleri geri veren iptal',
    'Bordrolar: oluşturma, ödeme takibi, toplu üretim',
    'Adına okundu bilgisiyle şirket belgeleri',
    'Eğitim: katalog, oturumlar, kayıtlar, maliyet ve süre',
    'Yıllık görüşmeler: kampanya, şablon, tutanak',
    'Giriş ve çıkış: izlenen kontrol listeleri, görev başına sorumlu ve süre',
    'Yetkinlikler ve yetki belgeleri, yenileme tarihi ve önceden uyarı ile',
    'Birebir görüşmeler: paylaşılan özet, yöneticinin notları ayrı tutulur',
    'Ayrılıştan sonra da erişilebilen dijital kasa, parmak iziyle mühürlenmiş belgeler',
    'Basit elektronik imza: sıralı akış, parmak izi, mühür, belge',
    'Belirli süreli sözleşmeler: hesap gününde kendiliğinden kapanır',
  ],
  'dom.talent.title': 'İşe alım ve yetenek',
  'dom.talent.lede': 'Başvurudan ilk güne, arada hiçbir hesap tablosu olmadan.',
  'dom.talent.items': [
    'İş ilanları ve aşama aşama izlenen başvurular',
    'Özgeçmiş alımı: PDF, DOCX veya metin, depo dışına yazılır',
    'İçerik çıkarma ve aranabilir özgeçmiş havuzu',
    'Ağırlıklı ölçütler, puan, eşik, başvuru sıralaması',
    'Kabul edilen aday doğrudan işe giriş yoluna geçer',
    'İç anketler ve çalışan barometresi, yapısı gereği anonim',
    'Beş yanıtın altında hiçbir sonuç gösterilmez',
  ],
  'dom.sst.title': 'İş sağlığı, güvenliği ve temsil',
  'dom.sst.lede': 'Yazılı tutulması gereken ve kendini hatırlatan yükümlülükler.',
  'dom.sst.items': [
    'Risk değerlendirmesi: çalışma birimleri, tehlikeler, puanlama, önlemler, tarihli gözden geçirme',
    'İş kazaları ve ramak kala olayları kaydı, iş göremezlik günleri',
    'Koruyucu donanım: adına teslim, geçerlilik süresi, yenileme',
    'Sağlık muayeneleri: işe giriş, periyodik, işe dönüş, talep üzerine',
    'Temsil: seçimler, seçmen listesi, anonim oylama, görevler ve sona ermeleri',
    'Kurul toplantıları, çalışanlara sağlanan haklar ve hizmetler',
    'Yönetim alanı görev süresi bitince kendiliğinden kapanır',
  ],
  'dom.finance.title': 'Finans ve idare',
  'dom.finance.lede': 'Üçüncü taraflar, sözleşmeler, giren para ve çıkan para.',
  'dom.finance.items': [
    'Müşteriler ve tedarikçiler, tam kayıt: kişiler, sözleşmeler, faturalar',
    'Sözleşmeler ve özellikle ihbar süreleri: fesih için son tarih hesaplanır ve uyarılır',
    'İki yönde faturalar, KDV dahil tutar hesaplanır, gecikme vadeden türetilir',
    'Birim ve mali yıl bazında bütçeler, harcama otomatik toplanır',
    'Masraf beyanları: sunum, onay, ödeme — biri olmadan diğeri asla',
    'Üçüncü tarafların uygunluk belgeleri, tarihli ve kırk beş gün önceden uyarılı',
    'Puanlanmış tedarikçi değerlendirmeleri: ortalama değil, son değerlendirme geçerlidir',
    'Her belgenin düzenlendiği anda sabitlenen kurla çoklu para birimi',
    'Yinelenen faturalama: abonelik kalıptır, fatura belgedir',
    'Gelen faturaların otomatik okunması ve bir muhasebe posta kutusunun IMAP ile alınması',
  ],
  'dom.compta.title': 'Muhasebe, bordro ve KDV',
  'dom.compta.lede': 'Varsayılan olarak kapalı, ihtiyaç duyduğunuzda açılan modüller.',
  'dom.compta.items': [
    'Çift taraflı muhasebe: hesap planı, yevmiye defterleri, mizan, defteri kebir',
    'Denk olmayan bir kayıt reddedilir ve ileti farkın ne kadar olduğunu söyler',
    'Bir fatura tek tıkla kayda dönüşür; müşavir için CSV dışa aktarımı',
    'Bordro motoru: ayarlanabilir oranlar, brütten nete, işveren payı, işveren maliyeti',
    'Satır satır ayrıntılı bordro, toplu üretim, simülatör',
    'KDV beyanları: hesaplanan, indirilecek, oran bazında dağılım, devreden alacak',
    'Verilmiş bir beyan yeniden hesaplanmaz: o bir belgedir, bir panel değil',
    'E-fatura: EN 16931 denetimi ve CII XML dışa aktarımı',
    'Nakit: hesaplar, hareketler, mutabakat, on iki haftalık öngörü',
    'Duran varlıklar: doğrusal ve azalan amortisman, net defter değeri',
  ],
  'dom.achats.title': 'Satın alma, stok ve tahsilat',
  'dom.achats.lede': 'Sipariş edilen, gelen, faturalanan — ve bize borçlu olunan.',
  'dom.achats.items': [
    'Satın alma talepleri önce yöneticiden, eşiğin üstünde mali işlerden onay alır',
    'Siparişler, mal kabulleri ve üçlü mutabakat: sipariş, teslim, fatura',
    'Siparişten fazlasını teslim almak reddedilir; fatura farkı adlandırılır, engellenmez',
    'Ürünler, hareketler, uyarı eşiği: stok hareketlerin toplamıdır',
    'Bir ürüne bağlı satır, teslim alındığı anda stoka girer',
    'Gecikme aralıklarına göre müşteri yaşlandırma tablosu',
    'Kademeli hatırlatmalar: hatırlatma, ihtar, ihtarname, daha önce gönderilene göre',
    'Her hatırlatma düzeyi ve tarihiyle kaydedilir',
  ],
  'dom.projets.title': 'Projeler, zaman ve kârlılık',
  'dom.projets.lede': 'Bir projenin nerede olduğunu ve gerçekte ne kadara mal olduğunu bilmek.',
  'dom.projets.items': [
    'Bir müşteriye, birime, ekibe ve sorumluya bağlı projeler',
    'Tarihli kilometre taşları ve duruma göre sütunlarda görevler, öncelik ve tahminle',
    'Projeye ve göreve işlenen zaman, kayıt başına en çok 24 saat',
    'Kârlılık: saatler, saat ücretiyle maliyet, kalan marj, harcanan bütçe payı',
    'Üç yetki halkası: mali işler, sorumlu, üyeler',
    'Kişi başına zaman ve yönetim panosunda proje sağlığı',
  ],
  'dom.support.title': 'Destek ve bilgi',
  'dom.support.lede': 'İç ve müşteri talepleri tek bir akışta, ve kalan yanıtlar.',
  'dom.support.items': [
    'İç ve müşteri kayıtları, öncelik, kaynak, atama',
    'Önceliğe göre türetilen ilk yanıt süresi, açılıştan itibaren yeniden hesaplanır',
    'Talep sahibine görünmeyen ve yanıt sayılmayan iç notlar',
    'Kategoriye göre ayrım: bir İK talebi İK\'dan çıkmaz',
    'Kategoriye göre bilgi tabanı, tam metin arama, ayarlanabilir kapsam',
    'Göstergeler: açık kayıtlar, geciken, ortalama süre',
  ],
  'dom.ops.title': 'Operasyon ve idari işler',
  'dom.ops.lede': 'Çalışma planı, kalite, salonlar, araçlar, karşılama.',
  'dom.ops.items': [
    'Kişi ve gün bazında plan: vardiyalar, nöbetler, sürekli görevler, uzaktan çalışma',
    'Çakışma ya da daha önce onaylanmış devamsızlık: aralık oluşturulurken reddedilir',
    'Yeniden kullanılabilir vardiya döngüleri, gece vardiyaları, haftanın yayımlanması',
    'Şu anda kimin nöbetçi olduğu, numarasıyla',
    'Kalite: uygunsuzluklar, kök nedenler, düzeltici faaliyetler ve etkinlik doğrulaması',
    'İç denetimler: bulgular, özet, uygunsuzluğa yükseltilen bir bulgu',
    'Zimmetlenen ve geri alınan ekipman, sahiplerinin geçmişiyle',
    'Salonlar ve rezervasyonlar, çakışma kimin kullandığını söyleyerek reddedilir',
    'Araç filosu: bakım, muayene, sigorta, hasarlar, kilometre',
    'Karşılama: ziyaretçi kaydı, binada bulunanlar listesi, gelen ve giden evrak',
  ],
  'dom.direction.title': 'Yönetim ve kurumsal yönetişim',
  'dom.direction.lede': 'Yönetimin baktığı ve karara bağladığı şeyler.',
  'dom.direction.items': [
    'Pano: çalışan sayısı, devamsızlar, faturalanan, marj, personel gideri, nakit, destek yükü',
    'Hedefler ve anahtar sonuçlar, her biri kendi ölçeğinde, azalan olanlar dahil',
    'Toplantılar: davet, gündem, işaretlenen katılım, tutanak',
    'Gerekçesiyle birlikte karar kaydı — iki yıl sonra aranan şey',
    'Sorumlusu ve süresiyle verilen görevler, kendi kararına bağlı',
    'Risk kaydı: brüt ve artık puan, 5 × 5 matris, işlem, gözden geçirme',
    'Şirket etkinlikleri: kontenjan, otomatik bekleme listesi, katılım imzası, bütçe',
    'Tüm alanlardan gelen vadeler tek bir sıralı listede',
  ],
  'dom.it.title': 'Bilgi işlem ve geliştirme',
  'dom.it.lede': 'Yazılım envanteri, erişimler, olaylar ve ekibin teslim ettikleri.',
  'dom.it.items': [
    'Yazılım envanteri: lisans sayısı bir kısıt olarak tutulur, yıllıklandırılmış maliyet, yenilemeler',
    'Erişim gözden geçirmesi: önce kapatılmış hesaplar, sonra yönetici yetkileri',
    'Zaman damgalı bilgi işlem olayları ve gerçekten ölçülen ortalama onarım süresi',
    'Servis kataloğu: kritiklik, sorumlu, depo, belgeler',
    'Ortam bazında sürüm kaydı ve teslimat göstergeleri',
    'Yedekler: saatlik arşiv, doğrulanmış bütünlük, kurtarma, dışa taşıma',
    'Kapsamlı okuma REST API\'si, imzalı giden webhook\'lar',
    'Kurulumun JSON olarak tam dışa aktarımı, belgeler dahil, sırlar hariç',
  ],
  'dom.conformite.title': 'Uyum, şirket hukuku ve kişisel veriler',
  'dom.conformite.lede': 'Bir şirketin kanıtlayabilmesi gerekenler, gün gün tutulur.',
  'dom.conformite.items': [
    'Pay defteri: paylar hareketlerden türetilir, devir iki ayaklı yazılır',
    'Süresi, azli ve önceden bildirilen bitişiyle şirket organ görevleri',
    'Genel kurullar: paylarda yeter sayı, kararlar, oylar, tutanak',
    'Yetki devirleri: konu, üst sınır, süre, bildirilen bitiş',
    'Çıkar çatışmaları ve hediyeler: herkes kendi adına bildirir, yönetim inceler',
    'Şifreli iç bildirim kanalı, atanmış sorumlular, kodla anonim takip',
    'Zaman damgalı, dışa aktarılabilir ve parmak izi zinciriyle mühürlenmiş denetim günlüğü',
    'GDPR: işleme kaydı, dışa aktarılan erişim hakkı, gerekçeli silme',
    'Yapılandırılabilir onay akışları: formlar, eşikler, göreve göre onaylayanlar',
  ],
  'shot.membre-espace': 'Çalışan alanı',
  'shot.membre-equipe': 'Yönetici alanı',
  'shot.membre-demandes': 'İç talepler',
  'shot.membre-agenda': 'Kişisel ve paylaşılan ajanda',
  'shot.membre-salles': 'Salonlar ve rezervasyonlar',
  'shot.membre-messagerie': 'İç mesajlaşma',
  'shot.membre-connaissances': 'Bilgi tabanı',
  'shot.membre-coffre-fort': 'Dijital kasa',
  'shot.membre-profil': 'Profil ve hesap güvenliği',
  'shot.membre-juridique-membre': 'Bildirimlerim',
  'shot.annuaire': 'Şirket rehberi',
  'shot.organigramme': 'Organizasyon şeması',
  'shot.connexion': 'Giriş ekranı',
  'shot.pilotage': 'Yönetim panosu',
  'shot.admin': 'Yönetim konsolu',
  'shot.rh': 'İnsan kaynakları',
  'shot.gestion': 'İdari ve mali yönetim',
  'shot.direction': 'Yönetim ve yönetişim',
  'shot.projets': 'Projeler, kilometre taşları ve kârlılık',
  'shot.support': 'Destek ve kayıtlar',
  'shot.planning': 'Plan, vardiyalar ve nöbetler',
  'shot.qualite': 'Kalite ve iç denetimler',
  'shot.sante-securite': 'İş sağlığı ve güvenliği',
  'shot.informatique': 'Yazılım envanteri ve erişimler',
  'shot.developpement': 'Servisler ve sürümler',
  'shot.evenements': 'Şirket etkinlikleri',
  'shot.juridique': 'Şirket hukuku ve uyum',
  'shot.alertes': 'İç bildirim kanalı',
  'shot.securite': 'Güvenlik konsolu',
  'shot.rgpd': 'Kişisel veriler',
  'shot.parapheur': 'İmza klasörü',
  'shot.sauvegardes': 'Yedekler ve kurtarma',
  'shot.comptabilite': 'Çift taraflı muhasebe',
  'shot.paie': 'Bordro motoru',
  'shot.tresorerie': 'Nakit ve öngörü',
  'shot.immobilisations': 'Duran varlıklar ve amortisman',
  'shot.crm': 'Ticari CRM',
  'shot.stock': 'Stok ve satın alma',
  'shot.pilotage-sombre': 'Yönetim — koyu tema',
  'shot.membre-espace-sombre': 'Çalışan alanı — koyu tema',
  'shot.gestion-sombre': 'Yönetim — koyu tema',
  'shot.projets-sombre': 'Projeler — koyu tema',
  'shot.juridique-sombre': 'Şirket hukuku — koyu tema',
  'shot.securite-sombre': 'Güvenlik — koyu tema',
  'tour.pilotage': 'Çalışan sayısı, faturalanan, marj, nakit, destek: yönetimin baktığı her şey tek sayfada. Bir tire eksik veriyi işaretler — rakam sanılabilecek bir sıfırı asla.',
  'tour.membre-espace': 'Herkesin sabah açtığı sayfa: yöneticisi, kendisini ilgilendiren duyurular, talepleri, onaylanacak belgeleri, araçları ve kullanıcı adları.',
  'tour.rh': 'İşlenecek talepler, bakiyeler, bordrolar, belgeler, eğitim, görüşmeler: çalışanın dosyası burada tutulur ve vadeler kendiliğinden yukarı çıkar.',
  'tour.gestion': 'Üçüncü taraflar, sözleşmeler ve ihbar süreleri, iki yönde faturalar, birim bütçeleri, masraflar, tahsilat. Bir bütçenin harcaması kendiliğinden toplanır.',
  'tour.projets': 'Kilometre taşları, sütunlarda görevler, harcanan zaman ve bütçeye karşı kârlılık. Maliyet yazılmaz: saatlerden ve saat ücretinden çıkar.',
  'tour.juridique': 'Sermaye, şirket organ görevleri, genel kurullar ve tutanaklar, yetki devirleri, çıkar bildirimleri. Bir şirketin kanıtlayabilmesi gerekenler, gün gün tutulur.',
};
