/* vi — traduit du français. Toute clé du français doit exister ici :
   le build refuse de construire une langue incomplète. */
module.exports = {
  'locale.name': 'Tiếng Việt',
  'site.name': 'Toutadmin',
  'site.tagline': 'CMS điều hành toàn bộ doanh nghiệp',
  'nav.product': 'Sản phẩm',
  'nav.features': 'Tính năng',
  'nav.screens': 'Màn hình',
  'nav.security': 'Bảo mật',
  'nav.pricing': 'Bảng giá',
  'nav.contact': 'Liên hệ',
  'nav.demo': 'Demo',
  'nav.menu': 'Menu',
  'nav.language': 'Ngôn ngữ',
  'nav.theme': 'Giao diện',
  'nav.themeLight': 'Sáng',
  'nav.themeDark': 'Tối',
  'nav.themeSystem': 'Hệ thống',
  'hero.eyebrow': 'Phần mềm quản trị doanh nghiệp',
  'hero.title': 'Toàn bộ doanh nghiệp,\ntrong một phần mềm duy nhất.',
  'hero.lede': 'Nhân sự, quản trị nhân lực, tài chính, vận hành, quản trị công ty, tuân thủ, hành chính. Ba mươi lăm không gian nói chuyện được với nhau, một cơ sở dữ liệu duy nhất, không phải dán các ứng dụng lại với nhau. Mười sáu ngôn ngữ, và 5 € mỗi nhân viên mỗi tháng để quản hết.',
  'hero.ctaPrimary': 'Dùng thử miễn phí',
  'hero.ctaSecondary': 'Xem các tính năng',
  'hero.note': 'Không cần thẻ ngân hàng. Dữ liệu vẫn là của bạn — và có thể ở lại chỗ bạn.',
  'hero.badge1': 'SaaS sẵn sàng trong năm phút',
  'hero.badge2': 'hoặc tự lưu trữ tại chỗ',
  'hero.badge3': 'Tuân thủ GDPR ngay từ thiết kế',
  'stats.title': 'Sản phẩm bao phủ những gì, bằng con số',
  'stats.spaces': 'không gian nghiệp vụ',
  'stats.spacesNote': 'từ trang riêng của nhân viên đến sổ sách pháp lý',
  'stats.languages': 'ngôn ngữ giao diện',
  'stats.languagesNote': 'gồm tiếng Ả Rập, trang được lật chiều',
  'stats.tests': 'bài kiểm thử tích hợp',
  'stats.testsNote': 'chạy ở mỗi lần phát hành',
  'stats.modules': 'phân hệ bật được',
  'stats.modulesNote': 'kế toán, tiền lương, dòng tiền, CRM…',
  'stats.deps': 'dịch vụ bên ngoài cần có',
  'stats.depsNote': 'một máy, một cơ sở dữ liệu, không gì khác',
  'stats.keys': 'nhãn đã dịch',
  'stats.keysNote': 'đến tận hộp thoại xác nhận',
  'pillars.title': 'Vì sao chọn Toutadmin thay vì năm công cụ chắp vá',
  'pillars.lede': 'Năm phần mềm không nói chuyện với nhau thì tốn kém hơn một, và làm mất điều quan trọng nhất: cái nhìn tổng thể. Toutadmin đi từ chiều ngược lại — một cơ sở dữ liệu, các không gian, và quyền hạn.',
  'pillars.1.title': 'Một chỗ, một sự thật',
  'pillars.1.body': 'Ngân sách của một phòng tự cộng hoá đơn của phòng và chi phí đã duyệt của các thành viên. Một lần nhận hàng vào kho ngay trong cùng thao tác. Không ai nhập lại điều gì, nên không ai mâu thuẫn với ai.',
  'pillars.2.title': 'Quyền hạn không phải để trang trí',
  'pillars.2.body': 'Mỗi đường dẫn đều mang chốt kiểm tra phía máy chủ, và các liên kết tổ chức được đọc lại ở từng yêu cầu. Một người nghỉ việc là mất quyền truy cập ngay, không đợi cookie hết hạn. Thứ bạn không được xem thì cũng không được tìm.',
  'pillars.3.title': 'Các mốc hạn tự tìm đến bạn',
  'pillars.3.body': 'Thời hạn báo trước của hợp đồng, chứng chỉ phải gia hạn, khám sức khoẻ, đăng kiểm xe, nhiệm kỳ người quản lý, giấy tờ của nhà cung cấp: một bộ máy duy nhất gom tất cả và báo đúng người, một lần, không trùng lặp.',
  'pillars.4.title': 'Mỗi màn hình nói rõ nó không làm gì',
  'pillars.4.body': 'Một phân hệ cho thấy giới hạn của nó ngay lúc bật, chứ không giấu ở cuối tài liệu. Chúng tôi thích một câu trung thực hơn một ô đã tick: chính điều đó tránh được bất ngờ khó chịu ở tháng thứ ba.',
  'pillars.5.title': 'Mười sáu ngôn ngữ, thật sự',
  'pillars.5.body': 'Không chỉ màn hình đầu tiên: trạng thái, thông báo lỗi, hộp thoại xác nhận. Tiếng Ả Rập lật toàn bộ trang, vì bảng kiểu chỉ dùng các thuộc tính logic.',
  'pillars.6.title': 'Dữ liệu của bạn, ở chỗ bạn nếu muốn',
  'pillars.6.body': 'Với SaaS, mọi thứ sẵn sàng trong năm phút. Ở các gói trả phí, bạn còn có thể đặt cơ sở dữ liệu trên máy chủ của mình: cùng phần mềm, cùng bản cập nhật, dữ liệu nằm trong tường nhà bạn.',
  'tour.title': 'Phần mềm đậm đặc, không phải đồ chơi',
  'tour.lede': 'Những màn hình làm cho người mở chúng tám tiếng mỗi ngày: thông tin thấy ngay, không có cửa sổ bật lên vô ích, và cùng một bộ từ vựng ở mọi nơi.',
  'tour.hint': 'Bấm vào một thẻ để đổi màn hình.',
  'tour.all': 'Xem cả 40 màn hình',
  'features.title': 'Tất cả những gì Toutadmin làm được',
  'features.lede': 'Danh sách đầy đủ, theo từng lĩnh vực. Mỗi dòng ứng với mã đã bàn giao và đã kiểm thử, không phải một dự định.',
  'features.legend': 'Các chức năng ghi «phân hệ» được bật từ bảng quản trị khi cần.',
  'features.module': 'phân hệ',
  'features.seeAll': 'Xem danh sách đầy đủ',
  'features.intro': 'Mười bốn lĩnh vực, hơn một trăm ba mươi chức năng.',
  'features.ctaTitle': 'Còn thiếu điều gì?',
  'features.ctaBody': 'Hãy cho chúng tôi biết. Sản phẩm tiến theo từng đợt, và yêu cầu của các doanh nghiệp đang dùng được ưu tiên trước.',
  'screens.title': 'Màn hình, không chỉnh sửa',
  'screens.lede': 'Mọi ảnh chụp trên trang này đều lấy từ một bản cài thật có dữ liệu minh hoạ. Không dựng mẫu, không ghép ảnh.',
  'screens.light': 'Giao diện sáng',
  'screens.dark': 'Giao diện tối',
  'screens.member': 'Không gian của nhân viên',
  'screens.admin': 'Quản trị và điều hành',
  'screens.modules': 'Phân hệ tuỳ chọn',
  'screens.open': 'Phóng to',
  'screens.close': 'Đóng',
  'screens.prev': 'Trước',
  'screens.next': 'Sau',
  'security.title': 'Bảo mật không phải là tuỳ chọn trả tiền',
  'security.lede': 'Tất cả những gì dưới đây đều có trong sản phẩm, ở mọi gói — kể cả gói miễn phí.',
  'security.1.title': 'Xác thực được siết chặt',
  'security.1.body': 'Mật khẩu băm (bcrypt), chính sách độ phức tạp, khoá tài khoản sau nhiều lần sai, xác thực hai bước TOTP kèm mã dự phòng, phiên đăng nhập thu hồi được từng cái hoặc tất cả cùng lúc.',
  'security.2.title': 'Nhật ký kiểm toán được niêm phong',
  'security.2.body': 'Mỗi mục mang dấu vân của mục liền trước. Sửa một dòng, hay rút một dòng ở giữa, sẽ làm đứt chuỗi đúng tại chỗ đó, và việc kiểm tra chỉ ra là dòng nào. Điều nó không làm: ngăn người nắm máy chủ viết lại — nó chỉ khiến việc đó lộ ra.',
  'security.3.title': 'Dữ liệu cá nhân',
  'security.3.body': 'Sổ đăng ký hoạt động xử lý, quyền truy cập được xuất theo từng nguồn, và việc xoá vẫn giữ lại phần luật buộc phải giữ và nói rõ điều đó. Tài khoản được ẩn danh thay vì xoá hẳn, để các bút toán tham chiếu đến nó vẫn nhất quán.',
  'security.4.title': 'Kênh cảnh báo nội bộ',
  'security.4.body': 'Bắt buộc tại Pháp từ năm mươi nhân viên. Nội dung được mã hoá trong cơ sở dữ liệu và chỉ người phụ trách được chỉ định mới đọc được — không phải quản trị viên, vì một tố giác có thể nhắm vào chính họ. Theo dõi ẩn danh bằng mã, không cần tài khoản và không ghi nhật ký.',
  'security.5.title': 'Sao lưu đã được kiểm chứng',
  'security.5.body': 'Lưu trữ mỗi giờ, kiểm tra toàn vẹn bằng bản kê, khôi phục cả cơ sở dữ liệu lẫn tệp, chuyển ra ngoài qua FTPS hoặc Google Drive, và cảnh báo cho quản trị viên khi thất bại.',
  'security.6.title': 'Bí mật được mã hoá',
  'security.6.body': 'Mật khẩu dịch vụ bên thứ ba, token API, khoá bí mật của webhook: mã hoá AES-256-GCM, không bao giờ hiển thị lại dạng rõ, và không đọc được sau khi bị can thiệp.',
  'security.hostTitle': 'SaaS, hoặc đặt tại chỗ',
  'security.hostBody': 'Với SaaS, chúng tôi lưu trữ tại châu Âu, gồm cả bản sao lưu. Ở các gói trả phí, việc tự lưu trữ là khả thi: bạn cài trên máy chủ của mình, cơ sở dữ liệu không bao giờ rời khỏi tường nhà bạn, và bạn nhận cùng những bản cập nhật. Một máy là đủ — Node 22 và SQLite, không có cơ sở dữ liệu bên ngoài nào phải quản trị.',
  'security.limitsTitle': 'Những gì chúng tôi không nhận là làm được',
  'security.limitsBody': 'Chữ ký điện tử ở mức đơn giản, không phải chữ ký đủ điều kiện theo eIDAS. Két số niêm phong và ghi ngày cho tài liệu, nhưng một dấu thời gian đối kháng được với bên thứ ba đòi hỏi một tổ chức chứng thực. Không có kê khai thuế hay bảo hiểm xã hội: phần mềm tạo ra dữ liệu, việc nộp vẫn là việc của kế toán của bạn. Điều này được viết ở đây, chứ không phải sau khi ký hợp đồng.',
  'pricing.title': 'Giá rõ ràng, không bất ngờ',
  'pricing.lede': 'Một mức giá duy nhất — mỗi nhân viên, mỗi tháng — để quản trị cả doanh nghiệp. Không mua lẻ từng phân hệ, không phụ phí theo tính năng: toàn bộ sản phẩm có trong mọi gói.',
  'pricing.perMonth': '/ tháng',
  'pricing.free': 'Miễn phí',
  'pricing.vat': 'Giá chưa gồm thuế. Các gói tháng không ràng buộc thời hạn.',
  'pricing.cta': 'Bắt đầu',
  'pricing.ctaCustom': 'Liên hệ với chúng tôi',
  'pricing.popular': 'Được chọn nhiều nhất',
  'pricing.p1.name': 'Miễn phí',
  'pricing.p1.for': 'Dưới 5 nhân viên',
  'pricing.p1.body': 'Toàn bộ sản phẩm, miễn phí, không giới hạn thời gian và không cắt bớt tính năng nào. Gói dành cho doanh nghiệp mới, hội đoàn hoặc văn phòng vừa khởi sự.',
  'pricing.p2.name': 'Thuê bao',
  'pricing.p2.for': 'Từ 5 nhân viên trở lên',
  'pricing.p2.body': '5 € mỗi nhân viên mỗi tháng, rồi 4 € từ hai trăm năm mươi đến năm trăm, và 3 € trên mức đó. Bạn trả cho số người đang có, không phải cho số người có thể sẽ có.',
  'pricing.p4.name': 'Giấy phép trọn đời',
  'pricing.p4.for': 'Thanh toán một lần',
  'pricing.p4.body': '10 000 € một lần. Không thuê bao, không giới hạn thời gian, không trần nhân sự. Phần mềm là của bạn chừng nào bạn còn muốn dùng.',
  'pricing.tableTitle': 'Mỗi gói gồm những gì',
  'pricing.col.feature': '',
  'pricing.yes': 'Có',
  'pricing.no': 'Không',
  'pricing.option': 'Tuỳ chọn',
  'pricing.f.allSpaces': '35 không gian và 7 phân hệ',
  'pricing.f.languages': '16 ngôn ngữ và 3 bảng màu',
  'pricing.f.security': 'Bảo mật đầy đủ, nhật ký niêm phong, GDPR',
  'pricing.f.updates': 'Bao gồm cập nhật',
  'pricing.f.saas': 'Lưu trữ SaaS tại châu Âu',
  'pricing.f.local': 'Tự lưu trữ dữ liệu của bạn',
  'pricing.f.backupOff': 'Chuyển sao lưu ra ngoài',
  'pricing.f.support': 'Hỗ trợ',
  'pricing.f.supportMail': 'Qua thư điện tử',
  'pricing.f.supportPrio': 'Ưu tiên',
  'pricing.f.supportDedicated': 'Đầu mối riêng',
  'pricing.f.supportCommunity': 'Tài liệu',
  'pricing.f.migration': 'Chuyển dữ liệu của bạn',
  'pricing.f.sla': 'Cam kết mức dịch vụ (SLA)',
  'pricing.f.api': 'API đọc và webhook',
  'pricing.f.multisite': 'Nhiều địa điểm, nhiều pháp nhân',
  'pricing.countTitle': 'Chúng tôi đếm nhân viên thế nào',
  'pricing.countBody': 'Các tài khoản đang hoạt động, gồm cả người làm tự do và thực tập sinh, trừ quản trị viên. Tài khoản đã đóng thì không còn được tính, dù vẫn giữ quyền vào két của mình. Vượt một ngưỡng? Thay đổi áp dụng từ tháng sau, không bao giờ hồi tố — và khi xuống cũng vậy.',
  'faq.title': 'Câu hỏi thường gặp',
  'faq.q1': 'Gói miễn phí có giới hạn thời gian không?',
  'faq.a1': 'Không. Dưới năm nhân viên, sản phẩm miễn phí không giới hạn thời gian và không cắt xén tính năng nào. Chúng tôi thích một tổ chức nhỏ lớn lên cùng phần mềm hơn là một bản dùng thử tắt sau ba mươi ngày.',
  'faq.q2': 'Tôi có thể đặt dữ liệu trên máy chủ của mình không?',
  'faq.a2': 'Có, ở các gói trả phí. Phần mềm chạy trên một máy duy nhất với Node 22 và SQLite: không cần máy chủ cơ sở dữ liệu, không cần dịch vụ bên ngoài. Cơ sở dữ liệu, tài liệu và bản sao lưu đều ở lại chỗ bạn.',
  'faq.q3': 'Nếu tôi ngừng sử dụng thì sao?',
  'faq.a3': 'Bạn xuất toàn bộ bản cài ra JSON, kèm tài liệu, từ bảng quản trị. Không có gì bị giữ lại: đó là cơ sở dữ liệu của bạn, và nó đi theo bạn ở một định dạng đọc được.',
  'faq.q4': 'Phần mềm có thay thế kế toán của tôi không?',
  'faq.a4': 'Không. Kế toán kép, tiền lương và thuế GTGT ở đây để ghi sổ và chuẩn bị chứng từ. Không có báo cáo tài chính pháp định, cũng không có nộp điện tử: bản xuất là thứ đưa cho văn phòng kế toán của bạn.',
  'faq.q5': 'Có cần đào tạo đội ngũ không?',
  'faq.a5': 'Không gian của nhân viên tự nó dễ hiểu: nghỉ phép, tài liệu, lịch trực, danh bạ. Các không gian quản trị cần nửa ngày làm quen, và chúng tôi đồng hành ở các gói trả phí.',
  'faq.q6': 'Tôi có thể chỉ bật một phần sản phẩm không?',
  'faq.a6': 'Có. Bảy phân hệ — kế toán, tiền lương, hoá đơn điện tử, kho và mua hàng, dòng tiền, tài sản cố định, CRM — mặc định tắt và được bật từng cái một. Khi một phân hệ còn tắt, các địa chỉ của nó trả về 404.',
  'faq.q7': 'Việc chuyển dữ liệu hiện có diễn ra thế nào?',
  'faq.a7': 'Một lần nhập hàng loạt bằng CSV kiểm tra từng dòng trước khi ghi, và không ghi gì cả nếu chỉ một dòng không hợp lệ. Ở các gói trả phí, chúng tôi chuẩn bị tệp cùng bạn.',
  'faq.q8': 'Còn việc kết nối với công cụ của chúng tôi?',
  'faq.a8': 'Một API REST chỉ đọc theo phạm vi và các webhook gửi đi có chữ ký đã có trong mọi gói. Với các trao đổi riêng — hệ thống nhân sự, ERP, hoá đơn — hãy viết cho chúng tôi: phần việc đó được báo giá theo từng trường hợp.',
  'contact.title': 'Hãy nói về doanh nghiệp của bạn',
  'contact.lede': 'Một buổi demo kéo dài ba mươi phút, đi theo tình huống của bạn chứ không phải dữ liệu bịa ra. Hãy viết cho chúng tôi điều bạn muốn giải quyết.',
  'contact.emailLabel': 'Qua thư điện tử',
  'contact.demoTitle': 'Yêu cầu một buổi demo',
  'contact.demoBody': 'Cho biết tên bạn, doanh nghiệp, số nhân sự và điều đang gây khó khăn hôm nay. Chúng tôi trả lời trong vòng một ngày làm việc.',
  'contact.write': 'Viết cho đội ngũ',
  'contact.docTitle': 'Đọc tài liệu',
  'contact.docBody': 'Trang tài liệu mô tả chi tiết việc cài đặt, cấu hình, bảo mật, API và toàn bộ bảng thuật ngữ trong mười sáu ngôn ngữ.',
  'contact.docCta': 'Mở tài liệu',
  'contact.selfTitle': 'Tự cài đặt',
  'contact.selfBody': 'Node 22, một máy, năm phút: trình trợ giúp tạo cơ sở dữ liệu, tài khoản quản trị và kiểm tra môi trường.',
  'contact.selfCta': 'Xem yêu cầu hệ thống',
  'cta.title': 'Bắt đầu miễn phí, đổi gói khi bạn lớn lên',
  'cta.body': 'Dưới năm nhân viên thì mọi thứ miễn phí. Trên mức đó, 5 € mỗi nhân viên mỗi tháng — giảm dần từ hai trăm năm mươi — hoặc 10 000 € một lần cho giấy phép trọn đời. Dùng thử không cần thẻ.',
  'cta.primary': 'Tạo bản cài của tôi',
  'cta.secondary': 'Nói chuyện với một người',
  'foot.product': 'Sản phẩm',
  'foot.company': 'Giới thiệu',
  'foot.resources': 'Tài nguyên',
  'foot.legal': 'Pháp lý',
  'foot.docs': 'Tài liệu',
  'foot.status': 'Phạm vi bao phủ',
  'foot.rights': 'Bảo lưu mọi quyền.',
  'foot.madeWith': 'Node 22 · Express · SQLite. Không một phụ thuộc thừa.',
  'foot.langTitle': 'Trang này có bằng mười sáu ngôn ngữ',
  'dom.socle.title': 'Nền tảng và tổ chức',
  'dom.socle.lede': 'Thứ đỡ lấy mọi phần còn lại: tài khoản, liên kết tổ chức, và bộ từ vựng chung cho mọi không gian.',
  'dom.socle.items': [
    'Tài khoản và các vai trò cộng dồn: quản trị, nhân sự, tài chính, tin học, người phụ trách cảnh báo',
    'Vai trò quản lý được suy ra từ cơ cấu thực tế, không bao giờ cấp bằng tay',
    'Phòng ban và nhóm, nhiều quản lý cho mỗi phạm vi, liên kết được đọc lại ở từng yêu cầu',
    'Sơ đồ tổ chức trực quan gồm cả cấp quản lý, và những người chưa gắn vào đâu',
    'Danh bạ có tìm kiếm và bộ lọc, khả năng hiển thị chỉ do bộ phận quản trị quyết định',
    'Tin nhắn nội bộ và địa chỉ công vụ do bộ phận quản trị cấu hình',
    'Tìm kiếm toàn cục được tách ngay từ nguồn: thứ bạn không được xem thì không được tìm',
    'Trung tâm thông báo cho từng người, có báo đã đọc',
    'Nhập hàng loạt bằng CSV: xem trước có kiểm tra, ghi tất cả hoặc không ghi gì',
    'Trình cài đặt, thiết lập bản cài, bảy phân hệ bật được',
    '16 ngôn ngữ, 3 bảng màu, giao diện sáng/tối/hệ thống, bố cục co giãn',
  ],
  'dom.espace.title': 'Không gian của nhân viên',
  'dom.espace.lede': 'Trang mà ai cũng mở vào buổi sáng: những gì liên quan đến mình, và không gì khác.',
  'dom.espace.items': [
    'Bảng tổng quan cá nhân: quản lý, tin tức, đơn từ, tài liệu chờ xác nhận',
    'Nghỉ phép, nghỉ bù, vắng mặt và làm việc từ xa: ngày làm việc được tính, cuối tuần bị loại',
    'Số ngày phép còn lại luôn cập nhật, kèm lịch sử điều chỉnh có lý do',
    'Phiếu lương xem được và lưu giữ năm mươi năm trong két số',
    'Lịch cá nhân và lịch dùng chung của nhóm',
    'Lịch trực trong tuần, trực sẵn sàng, trực thường xuyên',
    'Công cụ được cấp kèm tài khoản riêng — không lưu mật khẩu của dịch vụ bên ngoài',
    'Hồ sơ: ảnh, giới thiệu, điện thoại, ngôn ngữ, mật khẩu, đóng mọi phiên',
    'Chấm công bằng đồng hồ bấm giờ cho người làm tự do, mỗi lúc chỉ một lượt',
    'Kê khai lợi ích và quà tặng, chỉ chính mình nhìn thấy',
  ],
  'dom.rh.title': 'Quản trị nhân lực',
  'dom.rh.lede': 'Hồ sơ nhân viên, từ lúc đến cho tới lúc đi, cùng những mốc hạn đi kèm.',
  'dom.rh.items': [
    'Duyệt đơn có trừ số dư, từ chối có nêu lý do, huỷ thì hoàn lại ngày phép',
    'Phiếu lương: tạo lập, theo dõi chi trả, phát hành hàng loạt',
    'Tài liệu công ty có xác nhận đã nhận ghi rõ tên người',
    'Đào tạo: danh mục, đợt học, đăng ký, chi phí và thời lượng',
    'Đánh giá hằng năm: đợt, khung nội dung, biên bản',
    'Tiếp nhận và nghỉ việc: danh mục kiểm tra được theo dõi, có người phụ trách và hạn cho từng việc',
    'Năng lực và chứng chỉ, kèm ngày tái đào tạo và cảnh báo sớm',
    'Trao đổi một-một: bản tóm tắt chia sẻ, ghi chú của quản lý giữ riêng',
    'Két số vẫn mở được sau khi nghỉ, tài liệu được niêm phong bằng dấu vân',
    'Chữ ký điện tử đơn giản: luồng ký có thứ tự, dấu vân, con dấu, giấy chứng nhận',
    'Hợp đồng có thời hạn: tài khoản tự đóng đúng ngày',
  ],
  'dom.talent.title': 'Tuyển dụng và nhân tài',
  'dom.talent.lede': 'Từ hồ sơ ứng tuyển đến ngày đầu đi làm, không cần bảng tính ở giữa.',
  'dom.talent.items': [
    'Tin tuyển dụng và hồ sơ ứng tuyển được theo dõi theo từng bước',
    'Nhận CV: PDF, DOCX hoặc văn bản, ghi ra ngoài kho mã nguồn',
    'Trích xuất nội dung và kho CV tìm kiếm được',
    'Tiêu chí có trọng số, điểm, ngưỡng, xếp hạng hồ sơ',
    'Ứng viên được chọn chuyển thẳng sang quy trình tiếp nhận',
    'Khảo sát nội bộ và chỉ số bầu không khí, ẩn danh ngay từ cấu trúc',
    'Dưới năm câu trả lời thì không hiển thị kết quả nào',
  ],
  'dom.sst.title': 'An toàn, sức khoẻ và đại diện người lao động',
  'dom.sst.lede': 'Những nghĩa vụ phải ghi thành văn bản, và tự nhắc lấy mình.',
  'dom.sst.items': [
    'Đánh giá rủi ro: đơn vị làm việc, mối nguy, điểm, biện pháp, lần rà soát có ghi ngày',
    'Sổ tai nạn lao động và sự cố suýt xảy ra, số ngày nghỉ',
    'Trang bị bảo hộ: cấp phát ghi tên, thời hạn sử dụng, thay mới',
    'Khám sức khoẻ: khi tuyển, định kỳ, khi trở lại làm việc, theo yêu cầu',
    'Đại diện: bầu cử, danh sách cử tri, bỏ phiếu kín, nhiệm kỳ và ngày hết hạn',
    'Cuộc họp của tổ chức đại diện, phúc lợi và dịch vụ cho người lao động',
    'Không gian quản lý tự đóng khi nhiệm kỳ kết thúc',
  ],
  'dom.finance.title': 'Tài chính và hành chính',
  'dom.finance.lede': 'Đối tác, hợp đồng, tiền vào và tiền ra.',
  'dom.finance.items': [
    'Khách hàng và nhà cung cấp, hồ sơ đầy đủ: người liên hệ, hợp đồng, hoá đơn',
    'Hợp đồng và nhất là thời hạn báo trước: ngày cuối để chấm dứt được tính và nhắc trước',
    'Hoá đơn hai chiều, tổng tiền được tính, chậm trả suy ra từ ngày đến hạn',
    'Ngân sách theo phòng và theo năm tài chính, phần đã dùng tự cộng dồn',
    'Đề nghị thanh toán chi phí: nộp, duyệt, hoàn tiền — không bao giờ có cái này mà thiếu cái kia',
    'Giấy tờ tuân thủ của đối tác, có ngày và được báo trước bốn mươi lăm ngày',
    'Đánh giá nhà cung cấp bằng điểm: lấy lần rà soát gần nhất, không lấy trung bình',
    'Đa tiền tệ với tỷ giá cố định tại thời điểm phát hành từng chứng từ',
    'Xuất hoá đơn định kỳ: gói thuê bao là khuôn, hoá đơn là chứng từ',
    'Đọc tự động hoá đơn nhận được và lấy hộp thư kế toán qua IMAP',
  ],
  'dom.compta.title': 'Kế toán, tiền lương và thuế GTGT',
  'dom.compta.lede': 'Các phân hệ mặc định tắt, bật lên khi bạn cần.',
  'dom.compta.items': [
    'Kế toán kép: hệ thống tài khoản, sổ nhật ký, bảng cân đối thử, sổ cái',
    'Bút toán lệch bị từ chối, và thông báo nói rõ lệch bao nhiêu',
    'Hoá đơn thành bút toán chỉ bằng một cú nhấp; xuất CSV cho văn phòng kế toán',
    'Bộ tính lương: biểu tỷ lệ cấu hình được, từ gộp đến thực nhận, phần của doanh nghiệp, chi phí sử dụng lao động',
    'Phiếu lương chi tiết từng dòng, phát hành hàng loạt, công cụ mô phỏng',
    'Tờ khai thuế GTGT: đầu ra, đầu vào, chia theo thuế suất, số được chuyển tiếp',
    'Tờ khai đã nộp thì không tính lại: đó là chứng từ, không phải bảng theo dõi',
    'Hoá đơn điện tử: kiểm tra EN 16931 và xuất XML CII',
    'Dòng tiền: tài khoản, biến động, đối chiếu, dự báo mười hai tuần',
    'Tài sản cố định: khấu hao đường thẳng và giảm dần, giá trị còn lại',
  ],
  'dom.achats.title': 'Mua hàng, kho và thu hồi công nợ',
  'dom.achats.lede': 'Cái gì được đặt, cái gì đến, cái gì được xuất hoá đơn — và người ta nợ ta những gì.',
  'dom.achats.items': [
    'Đề nghị mua hàng do quản lý duyệt, vượt ngưỡng thì tới bộ phận tài chính',
    'Đơn đặt hàng, nhận hàng và đối chiếu ba chiều: đã đặt, đã nhận, đã xuất hoá đơn',
    'Nhận nhiều hơn số đã đặt sẽ bị từ chối; chênh lệch hoá đơn được nêu tên chứ không chặn thanh toán',
    'Mặt hàng, biến động, ngưỡng cảnh báo: tồn kho là tổng các biến động',
    'Dòng gắn với một mặt hàng vào kho ngay khi nhận',
    'Bảng tuổi nợ khách hàng theo từng khoảng quá hạn',
    'Nhắc nợ theo cấp: nhắc nhẹ, nhắc nợ, thư yêu cầu, tuỳ theo những gì đã gửi',
    'Mỗi lần nhắc đều được ghi lại kèm cấp độ và ngày',
  ],
  'dom.projets.title': 'Dự án, thời gian và hiệu quả',
  'dom.projets.lede': 'Biết một dự án đang ở đâu, và thực sự đã tốn bao nhiêu.',
  'dom.projets.items': [
    'Dự án gắn với một khách hàng, một phòng, một nhóm và một người phụ trách',
    'Mốc có ngày và công việc xếp theo cột trạng thái, kèm mức ưu tiên và ước lượng',
    'Thời gian ghi vào dự án và công việc, tối đa 24 giờ mỗi lần ghi',
    'Hiệu quả: số giờ, chi phí theo đơn giá giờ, lợi nhuận còn lại, phần ngân sách đã dùng',
    'Ba vòng quyền: bộ phận quản lý, người phụ trách, các thành viên',
    'Thời gian theo từng người, và sức khoẻ dự án trên bảng của ban lãnh đạo',
  ],
  'dom.support.title': 'Hỗ trợ và tri thức',
  'dom.support.lede': 'Yêu cầu nội bộ và yêu cầu của khách hàng trong cùng một luồng, và những câu trả lời còn lại.',
  'dom.support.items': [
    'Phiếu nội bộ và phiếu khách hàng, mức ưu tiên, nguồn, người được giao',
    'Hạn trả lời đầu tiên suy ra từ mức ưu tiên, tính lại từ lúc mở phiếu',
    'Ghi chú nội bộ người gửi không nhìn thấy, và không tính là câu trả lời',
    'Ngăn cách theo nhóm: yêu cầu nhân sự không ra khỏi bộ phận nhân sự',
    'Kho tri thức theo nhóm, tìm kiếm toàn văn, phạm vi điều chỉnh được',
    'Chỉ số: phiếu đang mở, phiếu trễ hạn, thời gian trung bình',
  ],
  'dom.ops.title': 'Vận hành và hành chính',
  'dom.ops.lede': 'Lịch trực, chất lượng, phòng họp, xe cộ, lễ tân.',
  'dom.ops.items': [
    'Lịch theo từng người và từng ngày: ca, trực sẵn sàng, trực thường xuyên, làm từ xa',
    'Trùng giờ hoặc đã duyệt nghỉ: khoảng thời gian bị từ chối ngay khi tạo',
    'Mẫu ca dùng lại được, ca đêm, công bố lịch tuần',
    'Ai đang trực lúc này, kèm số điện thoại',
    'Chất lượng: điểm không phù hợp, nguyên nhân gốc, hành động khắc phục và kiểm chứng hiệu lực',
    'Đánh giá nội bộ: phát hiện, tổng hợp, nâng một phát hiện thành điểm không phù hợp',
    'Thiết bị được cấp và thu hồi, kèm lịch sử người giữ',
    'Phòng họp và đặt chỗ, trùng giờ bị từ chối kèm tên người đang giữ',
    'Đội xe: bảo dưỡng, đăng kiểm, bảo hiểm, sự cố, số ki-lô-mét',
    'Lễ tân: sổ khách, danh sách người đang có mặt, thư đến và thư đi',
  ],
  'dom.direction.title': 'Lãnh đạo và quản trị công ty',
  'dom.direction.lede': 'Điều ban lãnh đạo nhìn vào, và điều họ quyết định.',
  'dom.direction.items': [
    'Bảng tổng quan: nhân sự, người vắng, doanh thu xuất hoá đơn, lợi nhuận gộp, quỹ lương, dòng tiền, tải hỗ trợ',
    'Mục tiêu và kết quả then chốt, mỗi cái theo thang riêng, kể cả thang giảm dần',
    'Cuộc họp: triệu tập, chương trình, điểm danh, biên bản',
    'Sổ quyết định kèm lý do — đúng thứ người ta đi tìm sau hai năm',
    'Việc được giao kèm người phụ trách và hạn, gắn với quyết định của nó',
    'Sổ rủi ro: điểm ban đầu và điểm còn lại, ma trận 5 × 5, cách xử lý, lần rà soát',
    'Sự kiện công ty: sức chứa, danh sách chờ tự động, điểm danh, ngân sách',
    'Mốc hạn của mọi không gian gom vào một danh sách đã sắp xếp',
  ],
  'dom.it.title': 'Tin học và phát triển',
  'dom.it.lede': 'Kho phần mềm, quyền truy cập, sự cố, và những gì đội ngũ bàn giao.',
  'dom.it.items': [
    'Kho phần mềm: số giấy phép coi như một ràng buộc, chi phí quy năm, các lần gia hạn',
    'Rà soát quyền truy cập: trước hết là tài khoản đã đóng, rồi tới quyền quản trị',
    'Sự cố hệ thống có mốc giờ, và thời gian khôi phục trung bình được đo thật',
    'Danh mục dịch vụ: mức trọng yếu, người phụ trách, kho mã, tài liệu',
    'Sổ phát hành theo môi trường và các chỉ số bàn giao',
    'Sao lưu: lưu trữ mỗi giờ, toàn vẹn đã kiểm chứng, khôi phục, chuyển ra ngoài',
    'API REST chỉ đọc theo phạm vi, webhook gửi đi có chữ ký',
    'Xuất toàn bộ bản cài ra JSON, gồm tài liệu, trừ các bí mật',
  ],
  'dom.conformite.title': 'Tuân thủ, pháp lý doanh nghiệp và dữ liệu cá nhân',
  'dom.conformite.lede': 'Những gì một doanh nghiệp phải chứng minh được, ghi lại ngay khi phát sinh.',
  'dom.conformite.items': [
    'Sổ vốn góp: phần nắm giữ suy ra từ các giao dịch, chuyển nhượng ghi đủ hai chiều',
    'Chức danh quản lý kèm thời hạn, việc bãi nhiệm và ngày kết thúc được báo trước',
    'Đại hội đồng: túc số tính theo cổ phần, nghị quyết, biểu quyết, biên bản',
    'Uỷ quyền: phạm vi, hạn mức, thời hạn, ngày hết hiệu lực được nhắc',
    'Xung đột lợi ích và quà tặng: mỗi người tự kê khai, bộ phận quản trị xem xét',
    'Kênh cảnh báo nội bộ được mã hoá, người phụ trách được chỉ định, theo dõi ẩn danh bằng mã',
    'Nhật ký kiểm toán có giờ, xuất được và niêm phong bằng chuỗi dấu vân',
    'GDPR: sổ đăng ký xử lý, quyền truy cập xuất được, việc xoá có căn cứ',
    'Luồng phê duyệt cấu hình được: biểu mẫu, ngưỡng, người duyệt theo chức năng',
  ],
  'shot.membre-espace': 'Không gian của nhân viên',
  'shot.membre-equipe': 'Không gian của quản lý',
  'shot.membre-demandes': 'Đơn từ nội bộ',
  'shot.membre-agenda': 'Lịch cá nhân và lịch chung',
  'shot.membre-salles': 'Phòng họp và đặt chỗ',
  'shot.membre-messagerie': 'Tin nhắn nội bộ',
  'shot.membre-connaissances': 'Kho tri thức',
  'shot.membre-coffre-fort': 'Két số',
  'shot.membre-profil': 'Hồ sơ và bảo mật tài khoản',
  'shot.membre-juridique-membre': 'Kê khai của tôi',
  'shot.annuaire': 'Danh bạ công ty',
  'shot.organigramme': 'Sơ đồ tổ chức',
  'shot.connexion': 'Màn hình đăng nhập',
  'shot.pilotage': 'Bảng điều hành',
  'shot.admin': 'Bảng quản trị',
  'shot.rh': 'Quản trị nhân lực',
  'shot.gestion': 'Quản trị hành chính và tài chính',
  'shot.direction': 'Lãnh đạo và quản trị công ty',
  'shot.projets': 'Dự án, mốc và hiệu quả',
  'shot.support': 'Hỗ trợ và phiếu yêu cầu',
  'shot.planning': 'Lịch trực, ca và trực sẵn sàng',
  'shot.qualite': 'Chất lượng và đánh giá nội bộ',
  'shot.sante-securite': 'An toàn và sức khoẻ lao động',
  'shot.informatique': 'Kho phần mềm và quyền truy cập',
  'shot.developpement': 'Dịch vụ và các lần phát hành',
  'shot.evenements': 'Sự kiện công ty',
  'shot.juridique': 'Pháp lý doanh nghiệp và tuân thủ',
  'shot.alertes': 'Kênh cảnh báo nội bộ',
  'shot.securite': 'Bảng bảo mật',
  'shot.rgpd': 'Dữ liệu cá nhân',
  'shot.parapheur': 'Cặp ký duyệt',
  'shot.sauvegardes': 'Sao lưu và khôi phục',
  'shot.comptabilite': 'Kế toán kép',
  'shot.paie': 'Bộ tính lương',
  'shot.tresorerie': 'Dòng tiền và dự báo',
  'shot.immobilisations': 'Tài sản cố định và khấu hao',
  'shot.crm': 'CRM bán hàng',
  'shot.stock': 'Kho và mua hàng',
  'shot.accueil': 'Lễ tân, khách và thư từ',
  'shot.flotte': 'Đội xe',
  'shot.parcours': 'Lộ trình và năng lực',
  'shot.import': 'Nhập dữ liệu',
  'shot.integrations': 'Giao diện và kết nối',
  'shot.pieces': 'Chứng từ nhận được',
  'shot.facturation': 'Hóa đơn điện tử',
  'shot.recherche': 'Tìm kiếm toàn hệ thống',
  'shot.notifications': 'Trung tâm thông báo',
  'shot.membre-cse': 'Hội đồng người lao động',
  'shot.pilotage-sombre': 'Điều hành — giao diện tối',
  'shot.membre-espace-sombre': 'Không gian nhân viên — giao diện tối',
  'shot.gestion-sombre': 'Quản trị — giao diện tối',
  'shot.projets-sombre': 'Dự án — giao diện tối',
  'shot.juridique-sombre': 'Pháp lý doanh nghiệp — giao diện tối',
  'shot.securite-sombre': 'Bảo mật — giao diện tối',
  'tour.pilotage': 'Nhân sự, doanh thu xuất hoá đơn, lợi nhuận gộp, dòng tiền, hỗ trợ: tất cả những gì ban lãnh đạo nhìn vào, trên một trang. Dấu gạch ngang nghĩa là thiếu dữ liệu — không bao giờ là số 0 dễ bị hiểu thành một con số.',
  'tour.membre-espace': 'Trang mà ai cũng mở vào buổi sáng: quản lý của mình, tin tức liên quan đến mình, đơn từ của mình, tài liệu chờ xác nhận, công cụ và tài khoản được cấp.',
  'tour.rh': 'Đơn chờ xử lý, số dư phép, phiếu lương, tài liệu, đào tạo, đánh giá: hồ sơ nhân viên được giữ ở đây, và các mốc hạn tự nổi lên.',
  'tour.gestion': 'Đối tác, hợp đồng và thời hạn báo trước, hoá đơn hai chiều, ngân sách phòng ban, chi phí, thu hồi công nợ. Phần ngân sách đã dùng tự cộng lấy.',
  'tour.projets': 'Các mốc, công việc xếp theo cột, thời gian đã bỏ ra và hiệu quả so với ngân sách. Chi phí không phải gõ tay: nó suy ra từ số giờ và đơn giá giờ.',
  'tour.juridique': 'Vốn, chức danh quản lý, đại hội và biên bản, uỷ quyền, kê khai lợi ích. Những gì doanh nghiệp phải chứng minh được, ghi lại ngay khi phát sinh.',
  'pricing.perEmployee': '5 € mỗi nhân viên mỗi tháng',
  'pricing.perEmployeeShort': 'mỗi nhân viên / tháng',
  'pricing.argTitle': 'Năm euro mỗi nhân viên, cho tất cả',
  'pricing.argBody': 'Một công cụ nhân sự, một phần mềm kế toán, một trình quản lý dự án, một hệ thống phiếu hỗ trợ, một két giữ phiếu lương: năm khoản thuê bao 8 đến 15 € mỗi người dùng, năm cơ sở dữ liệu không nói chuyện với nhau, năm hoá đơn. Toutadmin thay cả chồng đó bằng giá của cái rẻ nhất — và dữ liệu cuối cùng nằm chung một chỗ.',
  'pricing.gridTitle': 'Bảng giá theo số nhân viên',
  'pricing.gridLede': 'Giá chỉ chạy theo số nhân viên: 5 € mỗi người đến hai trăm bốn mươi chín, 4 € từ hai trăm năm mươi đến năm trăm, 3 € trên mức đó. Vượt một bậc thì hoá đơn giảm cho tất cả, chứ không riêng người mới vào.',
  'pricing.col.headcount': 'Số nhân viên',
  'pricing.col.monthly': 'Mỗi tháng',
  'pricing.col.perEmployee': 'Mỗi nhân viên',
  'pricing.upTo': 'Tối đa {count} nhân viên',
  'pricing.under': 'Dưới {count} nhân viên',
  'pricing.once': 'trả một lần',
  'pricing.lifetimeTitle': 'Vì sao có giấy phép trọn đời',
  'pricing.lifetimeBody': 'Mười nghìn euro một lần, không thuê bao và không giới hạn thời gian: vẫn bản cài đó, vẫn những bản cập nhật đó, không có trần số nhân viên. Ở quy mô một trăm người, nó hoàn vốn sau hai mươi tháng; ở năm trăm người, sau năm tháng. Đây là lựa chọn cho ai thích một khoản đầu tư hơn một dòng chi phí lặp lại — và cho ai không muốn phụ thuộc vào bất kỳ ai để tiếp tục làm việc.',
  'faq.q9': 'Nếu giữa năm số nhân viên thay đổi thì sao?',
  'faq.a9': 'Giá đi theo, cả hai chiều, từ tháng kế tiếp và không bao giờ hồi tố. Một lần tuyển dụng đẩy bạn qua ngưỡng sẽ tính vào tháng sau; một người nghỉ kéo bạn xuống lại cũng vậy. Không ai phải trả cho những tài khoản đã đóng.',
  'faq.q10': 'Giấy phép trọn đời có kèm cập nhật không?',
  'faq.a10': 'Có, và không giới hạn thời gian: «trọn đời» nghĩa là vậy. Bạn nhận đúng những phiên bản như các gói tháng, và có thể tự lưu trữ cơ sở dữ liệu. Thứ giấy phép không bao gồm là hỗ trợ ưu tiên — đó vẫn là một dịch vụ riêng.',
  'pricing.someEmployees': '{count} nhân viên',
  'nav.docs': 'Tài liệu',
  'menu.title': 'Toàn bộ trang',
  'menu.close': 'Đóng sơ đồ trang',
  'menu.domains': 'Mười bốn lĩnh vực',
  'menu.home.d': 'Sản phẩm bao phủ những gì, bằng con số, và một cái nhìn qua các màn hình.',
  'menu.features.d': 'Danh sách đầy đủ, theo từng lĩnh vực: hơn một trăm ba mươi chức năng đã bàn giao và kiểm thử.',
  'menu.screens.d': 'Bốn mươi ảnh chụp từ một bản cài thật, ở cả giao diện sáng và tối.',
  'menu.security.d': 'Xác thực, nhật ký niêm phong, dữ liệu cá nhân, kênh cảnh báo, sao lưu — và những giới hạn được thừa nhận.',
  'menu.pricing.d': 'Giá theo nhân viên, bảng theo số nhân sự và giấy phép trọn đời.',
  'menu.contact.d': 'Yêu cầu một buổi demo trên tình huống của bạn, hoặc viết cho chúng tôi.',
  'menu.docs.d': 'Cài đặt, cấu hình, bảo mật, API và bảng thuật ngữ đầy đủ. Trang riêng.',
  'menu.home': 'Trang chủ',
  'menu.group.product': 'Sản phẩm',
  'menu.group.decide': 'Để quyết định',
  'menu.group.more': 'Đi xa hơn',
};
