/* zh — traduit du français. Toute clé du français doit exister ici :
   le build refuse de construire une langue incomplète. */
module.exports = {
  'locale.name': '中文',
  'site.name': 'Toutadmin',
  'site.tagline': '管理整个企业的 CMS',
  'nav.product': '产品',
  'nav.features': '功能',
  'nav.screens': '界面',
  'nav.security': '安全',
  'nav.pricing': '价格',
  'nav.contact': '联系',
  'nav.demo': '演示',
  'nav.menu': '菜单',
  'nav.language': '语言',
  'nav.theme': '主题',
  'nav.themeLight': '浅色',
  'nav.themeDark': '深色',
  'nav.themeSystem': '跟随系统',
  'hero.eyebrow': '企业管理软件',
  'hero.title': '整个公司，\n装进一套软件。',
  'hero.lede': '人员、人力资源、财务、运营、治理、合规、后勤。三十五个彼此对话的工作空间，一个数据库，不必把应用拼接起来。支持十六种语言，每位员工每月 5 欧元，管好整家公司。',
  'hero.ctaPrimary': '免费试用',
  'hero.ctaSecondary': '查看功能',
  'hero.note': '无需银行卡。数据仍然属于您，也可以留在您自己那里。',
  'hero.badge1': 'SaaS 五分钟就绪',
  'hero.badge2': '或由您自行托管',
  'hero.badge3': '从设计起即合规',
  'stats.title': '产品覆盖范围，用数字说话',
  'stats.spaces': '个工作空间',
  'stats.spacesNote': '从员工自己的页面到公司法务登记',
  'stats.languages': '种界面语言',
  'stats.languagesNote': '含阿拉伯语，整页镜像',
  'stats.tests': '项集成测试',
  'stats.testsNote': '每次发布都会执行',
  'stats.modules': '个可启用模块',
  'stats.modulesNote': '会计、薪酬、资金、CRM…',
  'stats.deps': '项外部服务需求',
  'stats.depsNote': '一台机器、一个数据库，别无其他',
  'stats.keys': '条已翻译文案',
  'stats.keysNote': '连确认对话框也在内',
  'pillars.title': '为什么选 Toutadmin，而不是五个拼起来的工具',
  'pillars.lede': '五个互不对话的软件比一个更贵，还让人失去最要紧的东西：全局。Toutadmin 从相反的方向出发——一个数据库、若干空间、一套权限。',
  'pillars.1.title': '一个地方，一个事实',
  'pillars.1.body': '部门预算会自行汇总本部门的发票和成员已批准的报销。收货在同一个动作里进入库存。没有人重新录入，因此没有人自相矛盾。',
  'pillars.2.title': '权限不是装饰',
  'pillars.2.body': '每条路由在服务端都带着自己的守卫，归属关系在每次请求时重新读取。离职会立刻切断访问，而不是等 Cookie 过期。您无权查看的内容根本不会被检索。',
  'pillars.3.title': '到期提醒主动找上门',
  'pillars.3.body': '合同通知期、需要复训的资质、体检、车辆年检、公司职务任期、供应商证明：同一个引擎把它们汇拢，只提醒该提醒的人一次，不重复。',
  'pillars.4.title': '每个界面都说明它不做什么',
  'pillars.4.body': '模块在启用时就展示自己的边界，而不是埋在手册末尾。我们宁要一句诚实的话，也不要一个打勾的方框：正是这一点避免了第三个月的坏消息。',
  'pillars.5.title': '十六种语言，货真价实',
  'pillars.5.body': '不只是首页：状态、错误提示、确认对话框都翻译到位。阿拉伯语会把整页镜像，因为样式表只使用逻辑属性。',
  'pillars.6.title': '您的数据，愿意的话就放在您那里',
  'pillars.6.body': 'SaaS 模式下五分钟即可就绪。付费方案还可以把数据库放在您自己的服务器上：同样的软件、同样的更新，数据不出您的大门。',
  'tour.title': '密实的软件，不是玩具',
  'tour.lede': '为每天开着八小时的人而做的界面：信息一眼可见，没有多余的弹窗，各处用词一致。',
  'tour.hint': '点击标签切换界面。',
  'tour.all': '查看全部 40 个界面',
  'features.title': 'Toutadmin 能做的一切',
  'features.lede': '完整清单，按领域排列。每一行都对应已交付并经过测试的代码，而不是设想。',
  'features.legend': '标注「模块」的功能可在需要时从控制台启用。',
  'features.module': '模块',
  'features.seeAll': '查看完整清单',
  'features.intro': '十四个领域，一百三十多项功能。',
  'features.ctaTitle': '还缺什么吗？',
  'features.ctaBody': '告诉我们。产品按批次推进，正在使用它的企业提出的需求排在前面。',
  'screens.title': '未经修饰的界面',
  'screens.lede': '本站所有截图均来自填有演示数据的真实实例。没有效果图，没有拼接。',
  'screens.light': '浅色主题',
  'screens.dark': '深色主题',
  'screens.member': '员工工作空间',
  'screens.admin': '管理与经营',
  'screens.modules': '可选模块',
  'screens.open': '放大',
  'screens.close': '关闭',
  'screens.prev': '上一张',
  'screens.next': '下一张',
  'security.title': '安全不是付费选项',
  'security.lede': '下面的一切都在产品里，无论哪种方案——包括免费方案。',
  'security.1.title': '加固的身份验证',
  'security.1.body': '密码哈希存储（bcrypt）、复杂度策略、多次失败后锁定、带恢复码的 TOTP 双因素认证，会话可逐个或一次性全部注销。',
  'security.2.title': '封印的审计日志',
  'security.2.body': '每条记录都带着上一条的指纹。改动一行，或从中间抽走一行，就会在那个位置断开链条，校验会指出是哪一条。它不做的事：阻止掌握服务器的人重写日志——它只是让重写变得可见。',
  'security.3.title': '个人数据',
  'security.3.body': '处理活动登记册、按来源逐项导出的访问权、保留法律要求保留的部分并明确说明的删除。账户被匿名化而非删除，好让引用它的记录保持一致。',
  'security.4.title': '内部举报渠道',
  'security.4.body': '在法国，五十名员工起属强制要求。内容在数据库中加密，只有被指定的联络人可读——管理员不可读，因为举报可能正指向其中某位。凭代码匿名跟进，不需要账户，也不写入日志。',
  'security.5.title': '经过校验的备份',
  'security.5.body': '每小时归档、按清单校验完整性、可恢复数据库与文件、通过 FTPS 或 Google Drive 异地保存，失败时向管理员发出告警。',
  'security.6.title': '加密的密钥',
  'security.6.body': '第三方服务密码、API 令牌、Webhook 密钥：以 AES-256-GCM 加密，之后绝不再明文显示，被篡改后即不可读。',
  'security.hostTitle': 'SaaS，或放在您那里',
  'security.hostBody': 'SaaS 模式下我们在欧洲托管，含备份。付费方案支持本地托管：您安装在自己的服务器上，数据库绝不出门，并获得同样的更新。一台机器足矣——Node 22 与 SQLite，无需维护外部数据库。',
  'security.limitsTitle': '我们不声称能做的事',
  'security.limitsBody': '电子签名是简单签名，并非 eIDAS 意义上的合格签名。保险库会给文件加封并标注日期，但可对抗第三方的时间戳需要认证机构。不做任何税务或社保申报：软件生成数据，报送仍由您的会计负责。这些写在这里，而不是签约之后。',
  'pricing.title': '清楚的价格，没有意外',
  'pricing.lede': '一个价格——按员工、按月——管理整家公司。没有按模块选购，没有按功能加价：每种方案都包含完整产品。',
  'pricing.perMonth': '/ 月',
  'pricing.free': '免费',
  'pricing.vat': '价格不含税。月付方案没有最短期限约定。',
  'pricing.cta': '开始使用',
  'pricing.ctaCustom': '联系我们',
  'pricing.popular': '最多人选择',
  'pricing.p1.name': '免费',
  'pricing.p1.for': '少于 5 人',
  'pricing.p1.body': '完整产品，免费，不限时长，功能不打折。适合刚起步的公司、社团或事务所。',
  'pricing.p2.name': '订阅',
  'pricing.p2.for': '5 人起',
  'pricing.p2.body': '每位员工每月 5 欧元，两百五十至五百人为 4 欧元，超过五百人为 3 欧元。你按现有人数付费，而不是按将来也许会有的人数。',
  'pricing.p4.name': '终身授权',
  'pricing.p4.for': '一次性付款',
  'pricing.p4.body': '一次性 10,000 欧元。不订阅、不限时间、不限人数。只要你还想用，软件就是你的。',
  'pricing.tableTitle': '每种方案包含什么',
  'pricing.col.feature': '',
  'pricing.yes': '包含',
  'pricing.no': '否',
  'pricing.option': '可选',
  'pricing.f.allSpaces': '全部 35 个空间与 7 个模块',
  'pricing.f.languages': '16 种语言与 3 套配色',
  'pricing.f.security': '完整安全能力、封印日志、GDPR',
  'pricing.f.updates': '包含更新',
  'pricing.f.saas': '欧洲 SaaS 托管',
  'pricing.f.local': '您的数据本地托管',
  'pricing.f.backupOff': '备份异地保存',
  'pricing.f.support': '支持',
  'pricing.f.supportMail': '邮件支持',
  'pricing.f.supportPrio': '优先支持',
  'pricing.f.supportDedicated': '专属对接人',
  'pricing.f.supportCommunity': '文档',
  'pricing.f.migration': '数据迁移',
  'pricing.f.sla': '服务等级承诺（SLA）',
  'pricing.f.api': '只读 API 与 Webhook',
  'pricing.f.multisite': '多站点、多法人主体',
  'pricing.countTitle': '我们如何计算员工人数',
  'pricing.countBody': '活跃账户，含自由职业者与实习生，不含管理员。已关闭的账户不再计入，即便它仍可访问自己的保险库。跨过某个档位？变更自次月生效，绝不追溯——人数下降时同理。',
  'faq.title': '常见问题',
  'faq.q1': '免费方案有时间限制吗？',
  'faq.a1': '没有。五人以下，产品永久免费，功能不打折。比起三十天后失效的试用版，我们更愿意看到一家小机构随软件一起长大。',
  'faq.q2': '我可以把数据放在自己的服务器上吗？',
  'faq.a2': '可以，付费方案支持。软件在一台机器上以 Node 22 与 SQLite 运行：既没有数据库服务器，也没有外部服务。数据库、文档和备份都留在您那里。',
  'faq.q3': '如果我不再使用会怎样？',
  'faq.a3': '您可以在管理控制台把整个实例连同文档导出为 JSON。没有任何东西被扣留：那是您的数据库，会以可读格式随您离开。',
  'faq.q4': '它能取代我的会计吗？',
  'faq.a4': '不能。复式记账、薪酬和增值税用于记录账务、准备凭证。既没有法定报表，也没有电子报送：导出的数据交给您的会计。',
  'faq.q5': '需要培训团队吗？',
  'faq.a5': '员工空间无需讲解：请假、文件、排班、通讯录。管理类空间需要半天上手，我们在付费方案中提供陪同。',
  'faq.q6': '我可以只启用产品的一部分吗？',
  'faq.a6': '可以。七个模块——会计、薪酬、电子发票、库存与采购、资金、固定资产、CRM——默认关闭，可逐个启用。模块关闭期间，其地址返回 404。',
  'faq.q7': '现有数据如何迁移？',
  'faq.a7': 'CSV 批量导入会在写入前逐行校验，只要有一行无效就什么都不写。在付费方案中，我们与您一起准备文件。',
  'faq.q8': '与我们现有工具的对接呢？',
  'faq.a8': '带作用域的只读 REST API 和带签名的出站 Webhook 包含在所有方案中。若需特定对接——人事系统、ERP、开票——请写信给我们：这类工作按具体情况报价。',
  'contact.title': '聊聊您的公司',
  'contact.lede': '一次演示三十分钟，围绕您自己的场景，而不是编造的数据。写下您想解决的问题。',
  'contact.emailLabel': '通过邮件',
  'contact.demoTitle': '申请演示',
  'contact.demoBody': '请写明姓名、公司、人数，以及今天最让您头疼的事。我们在一个工作日内回复。',
  'contact.write': '写信给团队',
  'contact.docTitle': '阅读文档',
  'contact.docBody': '文档站点详述安装、配置、安全、API 以及十六种语言的完整术语表。',
  'contact.docCta': '打开文档',
  'contact.selfTitle': '自行安装',
  'contact.selfBody': 'Node 22、一台机器、五分钟：安装向导创建数据库和管理员账户，并检查运行环境。',
  'contact.selfCta': '查看前置条件',
  'cta.title': '免费开始，长大了再换方案',
  'cta.body': '五人以下，一切免费。超过之后，每位员工每月 5 欧元（两百五十人起递减），或一次性 10,000 欧元买终身授权。试用无需银行卡。',
  'cta.primary': '创建我的实例',
  'cta.secondary': '找人聊聊',
  'foot.product': '产品',
  'foot.company': '关于',
  'foot.resources': '资源',
  'foot.legal': '法律声明',
  'foot.docs': '文档',
  'foot.status': '覆盖范围',
  'foot.rights': '保留所有权利。',
  'foot.madeWith': 'Node 22 · Express · SQLite。没有一个多余的依赖。',
  'foot.langTitle': '本站提供十六种语言',
  'dom.socle.title': '底座与组织',
  'dom.socle.lede': '支撑其余一切的东西：账户、归属关系，以及所有空间共用的词汇。',
  'dom.socle.items': [
    '账户与可叠加的角色：管理员、人力资源、财务、信息技术、举报联络人',
    '主管身份由实际管辖关系推导得出，从不手工授予',
    '部门与团队，同一范围可有多位主管，归属关系每次请求重新读取',
    '可视化组织结构图，含管理层，并显示无任何归属的人员',
    '可搜索、可筛选的通讯录，可见性只由管理方控制',
    '内部消息，以及由管理方配置的工作邮箱',
    '全局搜索在源头即已隔离：您无权查看的内容根本不会被检索',
    '按人区分的通知中心，带已读回执',
    'CSV 批量导入：受控预览，要么全写入要么不写入',
    '安装向导、实例设置、七个可启用模块',
    '16 种语言、3 套配色、浅色/深色/跟随系统主题、自适应界面',
  ],
  'dom.espace.title': '员工工作空间',
  'dom.espace.lede': '每个人早上打开的那一页：与自己有关的内容，别无其他。',
  'dom.espace.items': [
    '个人看板：主管、公告、申请、待确认的文件',
    '休假、调休、缺勤与远程办公申请：自动计算工作日，排除周末',
    '实时的假期余额，以及带原因的调整记录',
    '工资单可查阅，并在保险库中保存五十年',
    '个人日历与团队共享日历',
    '本周排班、值班、驻守',
    '分配的工具带各自的账号——不存储任何第三方密码',
    '个人资料：照片、简介、电话、语言、密码、注销全部会话',
    '自由职业者的秒表计时，同一时间只能有一条进行中',
    '利益与礼品申报，只有本人可见',
  ],
  'dom.rh.title': '人力资源',
  'dom.rh.lede': '员工档案，从入职到离职，以及随之而来的各种期限。',
  'dom.rh.items': [
    '审批时自动扣减余额、拒绝须说明理由、撤销则自动返还天数',
    '工资单：生成、发放跟踪、批量出具',
    '公司文件带具名的接收确认',
    '培训：目录、场次、报名、费用与时长',
    '年度面谈：发起、提纲、记录',
    '入职与离职：可跟踪的清单，每项任务都有责任人和期限',
    '技能与资质，带复训日期和提前提醒',
    '一对一面谈：共享摘要，主管的私人笔记单独保存',
    '离职后仍可访问的数字保险库，文件以指纹封存',
    '简单电子签名：有序流程、指纹、封印、证明',
    '定期合同：账户到期当天自行关闭',
  ],
  'dom.talent.title': '招聘与人才',
  'dom.talent.lede': '从投递到第一天上班，中间不需要表格。',
  'dom.talent.items': [
    '招聘岗位与按阶段跟踪的应聘',
    '简历接收：PDF、DOCX 或纯文本，写在代码库之外',
    '内容抽取与可检索的简历库',
    '加权标准、评分、阈值、应聘排序',
    '录用的候选人直接转入入职流程',
    '内部问卷与员工氛围指数，从结构上即匿名',
    '回答少于五份时不展示任何结果',
  ],
  'dom.sst.title': '健康、安全与职工代表',
  'dom.sst.lede': '必须书面留存、并会自己提醒你的义务。',
  'dom.sst.items': [
    '风险评估：作业单元、危害、评级、措施、带日期的复核',
    '工伤与未遂事故登记，停工天数',
    '防护装备：具名发放、有效期、更换',
    '体检：入职、定期、复工、按需',
    '职工代表：选举、选民名册、匿名投票、任期及其届满',
    '委员会会议、面向员工的福利与服务',
    '任期结束时，管理空间自行关闭',
  ],
  'dom.finance.title': '财务与行政',
  'dom.finance.lede': '往来单位、合同、进来的钱和出去的钱。',
  'dom.finance.items': [
    '客户与供应商，完整档案：联系人、合同、发票',
    '合同，尤其是通知期：自动计算解约最后期限并提前提醒',
    '双向发票，含税金额自动计算，逾期由到期日推导',
    '按部门与会计年度的预算，消耗额自动汇总',
    '报销单：提交、审批、付款——缺一不可',
    '往来单位的合规文件，带日期并在到期前四十五天提醒',
    '供应商评分：以最近一次评估为准，而非平均值',
    '多币种，汇率在每份单据开具时固定',
    '周期性开票：订阅是模子，发票是单据',
    '自动识别收到的发票，并通过 IMAP 收取会计邮箱',
  ],
  'dom.compta.title': '会计、薪酬与增值税',
  'dom.compta.lede': '默认关闭的模块，需要时再启用。',
  'dom.compta.items': [
    '复式记账：会计科目表、日记账、试算平衡表、总账',
    '不平衡的分录会被拒绝，提示会说明差额是多少',
    '发票一键生成分录；可导出 CSV 交给会计',
    '薪酬引擎：可配置费率、从税前到税后、雇主部分、用人成本',
    '逐行明细的工资单、批量生成、模拟器',
    '增值税申报：销项、进项、按税率拆分、可结转的留抵',
    '已申报的报表不再重算：那是单据，不是看板',
    '电子发票：EN 16931 校验与 CII XML 导出',
    '资金：账户、流水、对账、十二周预测',
    '固定资产：直线与余额递减折旧、账面净值',
  ],
  'dom.achats.title': '采购、库存与催收',
  'dom.achats.lede': '订了什么、来了什么、开了什么票——以及别人欠我们什么。',
  'dom.achats.items': [
    '采购申请先由主管审批，超过阈值再由财务审批',
    '采购订单、收货与三方匹配：已订、已收、已开票',
    '收货多于订货会被拒绝；开票差异只标注，不阻断付款',
    '物料、出入库、警戒线：库存是出入库的总和',
    '关联物料的行项在收货那一刻即入库',
    '按逾期区间划分的客户账龄表',
    '分级催收：提醒、催告、正式函，依据此前已发出的内容',
    '每次催收都记录级别与日期',
  ],
  'dom.projets.title': '项目、工时与盈利',
  'dom.projets.lede': '知道项目走到哪一步，以及它究竟花了多少。',
  'dom.projets.items': [
    '项目关联客户、部门、团队与负责人',
    '带日期的里程碑，以及按状态分列的任务，含优先级与预估',
    '工时记到项目与任务上，单条最多 24 小时',
    '盈利：工时、按时薪计的成本、剩余利润、预算消耗比例',
    '三层权限：财务、负责人、成员',
    '按人统计工时，以及管理看板上的项目健康度',
  ],
  'dom.support.title': '支持与知识库',
  'dom.support.lede': '内部与客户请求走同一条流程，答案也留得下来。',
  'dom.support.items': [
    '内部与客户工单，优先级、来源、指派',
    '首次响应时限由优先级推导，并从开单时刻重新计算',
    '内部备注对提交人不可见，也不计为回复',
    '按类别隔离：人事类请求不会离开人事',
    '按类别分的知识库、全文检索、可调节的可见范围',
    '指标：未结工单、逾期工单、平均时长',
  ],
  'dom.ops.title': '运营与后勤',
  'dom.ops.lede': '排班、质量、会议室、车辆、前台。',
  'dom.ops.items': [
    '按人按天排班：班次、值班、驻守、远程办公',
    '时间冲突或已批准的缺勤：创建时即被拒绝',
    '可复用的轮班模板、夜班、周计划发布',
    '此刻谁在值班，以及他的电话',
    '质量：不符合项、根本原因、纠正措施与有效性验证',
    '内部审核：发现项、结论，可将发现项升级为不符合项',
    '设备的发放与收回，附持有人历史',
    '会议室与预订，冲突时拒绝并说明占用者',
    '车队：保养、年检、保险、事故、里程',
    '前台：访客登记、在楼人员名单、收发信件',
  ],
  'dom.direction.title': '管理层与治理',
  'dom.direction.lede': '管理层看什么，以及决定什么。',
  'dom.direction.items': [
    '看板：人数、缺勤、已开票、毛利、人工成本、资金、支持负荷',
    '目标与关键结果，各自的刻度，也支持递减型',
    '会议：召集、议程、出勤点名、纪要',
    '带理由的决议登记册——两年后要找的正是理由',
    '有责任人和期限的行动项，挂在各自的决议上',
    '风险登记册：原始与剩余评级、5 × 5 矩阵、处置、复审',
    '公司活动：名额、自动候补名单、签到、预算',
    '所有空间的到期事项汇入同一份排序清单',
  ],
  'dom.it.title': '信息技术与研发',
  'dom.it.lede': '软件资产、访问权限、事件，以及团队交付的东西。',
  'dom.it.items': [
    '软件资产：授权席位作为硬约束，年化成本，续订',
    '应用访问复核：先看已关闭的账户，再看管理员权限',
    '带时间戳的 IT 事件，以及真正测量出来的平均恢复时长',
    '服务清单：重要程度、负责人、代码库、文档',
    '按环境的发布记录与交付指标',
    '备份：每小时归档、校验完整性、恢复、异地保存',
    '带作用域的只读 REST API，带签名的出站 Webhook',
    '整个实例导出为 JSON，含文档，不含密钥',
  ],
  'dom.conformite.title': '合规、公司法务与个人数据',
  'dom.conformite.lede': '公司必须能够证明的东西，随时记录在案。',
  'dom.conformite.items': [
    '股权登记册：持股由变动推导，转让写成一进一出两笔',
    '公司职务任期，带期限、解任与提前提示的届满',
    '股东会：以股份计的法定人数、决议、表决、纪要',
    '授权委托：事项、金额上限、期限、届满提醒',
    '利益冲突与礼品：各自申报，管理方复核',
    '加密的内部举报渠道、指定联络人、凭代码匿名跟进',
    '带时间戳、可导出并以指纹链封印的审计日志',
    'GDPR：处理登记册、可导出的访问权、有理有据的删除',
    '可配置的审批流程：表单、阈值、按职能设定的审批人',
  ],
  'shot.membre-espace': '员工工作空间',
  'shot.membre-equipe': '主管工作空间',
  'shot.membre-demandes': '内部申请',
  'shot.membre-agenda': '个人与共享日历',
  'shot.membre-salles': '会议室与预订',
  'shot.membre-messagerie': '内部消息',
  'shot.membre-connaissances': '知识库',
  'shot.membre-coffre-fort': '数字保险库',
  'shot.membre-profil': '个人资料与账户安全',
  'shot.membre-juridique-membre': '我的申报',
  'shot.annuaire': '公司通讯录',
  'shot.organigramme': '组织结构图',
  'shot.connexion': '登录界面',
  'shot.pilotage': '管理看板',
  'shot.admin': '管理控制台',
  'shot.rh': '人力资源',
  'shot.gestion': '行政与财务管理',
  'shot.direction': '管理层与治理',
  'shot.projets': '项目、里程碑与盈利',
  'shot.support': '支持与工单',
  'shot.planning': '排班、轮班与值班',
  'shot.qualite': '质量与内部审核',
  'shot.sante-securite': '职业健康与安全',
  'shot.informatique': '软件资产与访问权限',
  'shot.developpement': '服务与发布',
  'shot.evenements': '公司活动',
  'shot.juridique': '公司法务与合规',
  'shot.alertes': '内部举报渠道',
  'shot.securite': '安全控制台',
  'shot.rgpd': '个人数据',
  'shot.parapheur': '签署夹',
  'shot.sauvegardes': '备份与恢复',
  'shot.comptabilite': '复式记账',
  'shot.paie': '薪酬引擎',
  'shot.tresorerie': '资金与预测',
  'shot.immobilisations': '固定资产与折旧',
  'shot.crm': '销售 CRM',
  'shot.stock': '库存与采购',
  'shot.accueil': '前台、访客与信件',
  'shot.flotte': '车队管理',
  'shot.parcours': '发展路径与技能',
  'shot.import': '数据导入',
  'shot.integrations': '接口与连接器',
  'shot.pieces': '收到的单据',
  'shot.facturation': '电子发票',
  'shot.recherche': '全局搜索',
  'shot.notifications': '通知中心',
  'shot.membre-cse': '职工委员会',
  'shot.pilotage-sombre': '管理看板 — 深色主题',
  'shot.membre-espace-sombre': '员工空间 — 深色主题',
  'shot.gestion-sombre': '行政财务 — 深色主题',
  'shot.projets-sombre': '项目 — 深色主题',
  'shot.juridique-sombre': '公司法务 — 深色主题',
  'shot.securite-sombre': '安全 — 深色主题',
  'tour.pilotage': '人数、已开票、毛利、资金、支持：管理层要看的一切，集中在一页。短横线表示数据缺失——绝不用一个会被当成数字的零。',
  'tour.membre-espace': '每个人早上打开的那一页：自己的主管、与自己有关的公告、自己的申请、待确认的文件、自己的工具和账号。',
  'tour.rh': '待处理的申请、假期余额、工资单、文件、培训、面谈：员工档案在这里维护，到期事项自己浮上来。',
  'tour.gestion': '往来单位、合同与通知期、双向发票、部门预算、报销、催收。预算的消耗额会自己汇总。',
  'tour.projets': '里程碑、分列的任务、投入工时，以及与预算对照的盈利。成本不是录入的：它由工时和时薪推导而来。',
  'tour.juridique': '股本、公司职务、股东会与纪要、授权委托、利益申报。公司必须能够证明的东西，随时记录在案。',
  'pricing.perEmployee': '每位员工每月 5 欧元',
  'pricing.perEmployeeShort': '每位员工 / 每月',
  'pricing.argTitle': '每位员工五欧元，涵盖一切',
  'pricing.argBody': '一套人事工具、一套会计软件、一个项目管理器、一个工单系统、一个工资单保险库：五份每用户 8 到 15 欧元的订阅，五个互不对话的数据库，五张账单。Toutadmin 以其中最便宜的那份价格，替掉了整堆——而数据终于待在同一个地方。',
  'pricing.gridTitle': '按人数的价格表',
  'pricing.gridLede': '价格只跟着人数走：两百四十九人以内每人 5 欧元，两百五十至五百人每人 4 欧元，超过五百人每人 3 欧元。跨过一档，账单对所有人都下降，而不只是对新来的人。',
  'pricing.col.headcount': '人数',
  'pricing.col.monthly': '每月',
  'pricing.col.perEmployee': '人均',
  'pricing.upTo': '最多 {count} 人',
  'pricing.under': '少于 {count} 人',
  'pricing.once': '一次性',
  'pricing.lifetimeTitle': '为什么要买终身授权',
  'pricing.lifetimeBody': '一次性一万欧元，不订阅、不限时间：同样的实例、同样的更新，人数没有上限。一百人规模下二十个月回本，五百人规模下五个月。这是给那些宁要一次投入也不要长期费用科目的人——也给那些不愿依赖任何人才能继续工作的人。',
  'faq.q9': '如果年中人数发生变化怎么办？',
  'faq.a9': '价格会跟着变，两个方向都一样：自次月起生效，绝不追溯。让你跨过档位的新招聘，下个月计费；让你回落的离职，同样如此。没有人为已关闭的账户付费。',
  'faq.q10': '终身授权包含更新吗？',
  'faq.a10': '包含，且不限时间——这正是「终身」的含义。你拿到的版本与月付方案相同，也可以把数据库放在自己那里。授权不包含的是优先支持，那仍是一项单独的服务。',
  'pricing.someEmployees': '{count} 人',
  'nav.docs': '文档',
  'menu.title': '整站导览',
  'menu.close': '关闭站点地图',
  'menu.domains': '十四个领域',
  'menu.home.d': '产品覆盖范围的数字，以及界面的概览。',
  'menu.features.d': '按领域排列的完整清单：一百三十多项已交付并经过测试的功能。',
  'menu.screens.d': '来自真实实例的四十张截图，含浅色与深色主题。',
  'menu.security.d': '身份验证、封印日志、个人数据、举报渠道、备份——以及我们承认的边界。',
  'menu.pricing.d': '按员工计价、按人数的价格表，以及终身授权。',
  'menu.contact.d': '就你自己的场景申请演示，或写信给我们。',
  'menu.docs.d': '安装、配置、安全、API 与完整术语表。独立站点。',
  'menu.home': '首页',
  'menu.group.product': '产品',
  'menu.group.decide': '用于决策',
  'menu.group.more': '更进一步',
};
